### ISSUE TITLE
Installation instructions should mention installing Nix is not invasive

### ISSUE THREAD

**Issue by Blaisorblade** [NixOS/nixos-homepage#100]
I considered installing Nix to test Stack's nix integration (https://github.com/commercialhaskell/stack/pull/2537#issuecomment-250848907) but was afraid it'd set up a different GHC and create potential configuration conflicts. Given my upcoming deadlines, it makes sense to be most conservative (I've used Gentoo as my main Linux distro time ago and customized lots of it, but these days I have another job to focus on).

It turns out it only installs `nix-` prefixed binaries, so there's no such risk, but the download page could tell me that.

More in general, I'd like to know what happens by installing Nix before I do decide to install it.

**Comment by Blaisorblade** [comment]
So it turns out that installing Nix is invasive, as it literally breaks Homebrew by setting `SSL_CERT_FILE`, see https://github.com/NixOS/nix/issues/921.

**Comment by garbas** [comment]
closing since this discussion was moved to other repos.
