### ISSUE TITLE
How nix{,os} works page has a grub screenshot

### ISSUE THREAD

**Issue by gilice** [NixOS/nixos-homepage#1010]
Since Grub is no longer the default bootloader appiied with `nix-generate-config` (replaced by `systemd-boot`), the screenshot should be updated.

(Fun fact: the screenshot is almost 10 years old!)

Page links: https://nixos.org/guides/how-nix-works.html#rollbacks
Suggested edit: replace with a screenshot of systemd-boot

**Comment by brnl** [comment]
![image](https://github.com/NixOS/nixos-homepage/assets/3243133/167766c3-1a6c-4008-b811-5327221fe771)

^ Does this work for you? I just cropped to 1024 px wide, maintaining aspect ratio. The original is also small in size.
