### ISSUE TITLE
There is no information on how to run the installer

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixos-homepage#1013]
**Introduce your stance**

The Homepage currently says: 

> The minimal installation ISO image does not contain the graphical user interface, and is therefore a lot smaller. You have to run the installer from the console. It contains a number of rescue tools

(under `Download > Minimal ISO image`)

Emphasis: "run the installer from the console".

But it does not say _how_ to actually run the installer.

**Page links**

https://nixos.org/download.html

---

Reported to me in person by @p-fruck

**Comment by fricklerhandwerk** [comment]
This looks like it simply needs a link to the installation section of the NixOS manual. Feel free to open a PR and ping me there.
