### ISSUE TITLE
redirect to latest release ISO shouldn't be permanent

### ISSUE THREAD

**Issue by eladyn** [NixOS/nixos-homepage#1015]
**Introduce your stance**
Yesterday, I downloaded the latest minimal installation ISO for 64bit Intel/AMD. Today, I wanted to check, whether the sha256sum of the file was correct, but the checksum targeted a different file. Redownloading the ISO returned the same file as the day before.

**Describe the issue**
The problem here is, that for example https://channels.nixos.org/nixos-22.11/latest-nixos-minimal-x86_64-linux.iso does a `301` Permanent Redirect to the currently latest ISO. This causes the browser to cache the location of the redirect, the first time I visit the link, and there's no easy way to notice that or prevent that as a user.

(In my case, a new ISO was published between downloading the ISO and downloading the checksum, so the cached permanent redirects of the ISO and the SHA256 pointed to different versions.)

**Page links**
- https://nixos.org/download.html

**Additional context**
```console
# curl -I https://channels.nixos.org/nixos-22.11/latest-nixos-minimal-x86_64-linux.iso
HTTP/2 301 
location: https://releases.nixos.org/nixos/22.11/nixos-22.11.3092.970402e6147/nixos-minimal-22.11.3092.970402e6147-x86_64-linux.iso
server: AmazonS3
via: 1.1 varnish, 1.1 varnish
access-control-allow-origin: *
accept-ranges: bytes
date: Mon, 13 Mar 2023 12:48:35 GMT
age: 892
x-served-by: cache-iad-kjyo7100164-IAD, cache-muc13949-MUC
x-cache: HIT, HIT
x-cache-hits: 5, 1
x-timer: S1678711715.242567,VS0,VE0
content-length: 0
```

**Comment by dasisdormax** [comment]
I think I was affected by this as well.

I just wanted to report the Gnome ISO and checksum pointing to different versions, but this might be the reason instead.

**Comment by rsulli55** [comment]
Also just ran into this on the plasma version.  Checksum is looking for `nixos-plasma5-23.05.3701.e9b4b56e5a20-x86_64-linux.iso`, but firefox downloaded `nixos-plasma5-23.05.3686.55ac2a9d2024-x86_64-linux.iso `

**Comment by colons** [comment]
does anyone know who controls what kind of redirect is done here? this seems like a really simple and clearly-correct fix, and it's one that has affected enough people that at least five have now reported it (#420 / #745 / #886 / #1015 / #1181); it has doubtless been noticed by many more, and treated as evidence of corruption by at least a few

**Comment by fricklerhandwerk** [comment]
@delroth the infra team may know more. This is definitely declared *somewhere* in some repo.

**Comment by delroth** [comment]
This is https://github.com/NixOS/nixos-channel-scripts/issues/42 where people already figured out the same thing as I just did (we should switch to bucket-level redirect rules instead of object-level redirects, since the latter can only use 301s).

**Comment by colons** [comment]
(for the record: yes this seems to be fixed in real browsers too)
