### ISSUE TITLE
Download page is missing links to any older ISOs

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixos-homepage#102]
Looking at https://nixos.org/nixos/download.html, there is seemly no way to obtain anything other than the latest ISO.

Where can I find links to other releases?

**Comment by chris-martin** [comment]
(In case I need to justify this...) I see why we want people on the newest version, and I know that old releases are unsupported, but there are a lot of reasons why someone might need to use a previous version. For example, [nixos-in-place](https://github.com/jeaye/nixos-in-place/issues/26) doesn't work anymore, so I'd like to test with an older release, just for debugging to find out whether it's a change in NixOS that caused the problem.

**Comment by domenkozar** [comment]
Since migration to S3, we have to generate a new index for all history.

**Comment by edolstra** [comment]
You can find old releases by listing the nix-releases S3 bucket (or https://d3g5gsiof5omrk.cloudfront.net/, the Cloudfront distribution). Unfortunately S3 doesn't provide user-friendly listings...

**Comment by domenkozar** [comment]
We can fix this by generating a parsable JSON that can be later used to provide history:

https://github.com/NixOS/nixos-channel-scripts/issues/10

**Comment by garbas** [comment]
this was now fixed, you can find older releases under https://releases.nixos.org/nixos
