### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#1020]
**Introduce your stance**
I noticed that there are multiple places for the same information. It is unclear what to share on e.g. social media.

**Describe the issue**
When looking for information on creating custom ISOs, there are 2 different links

https://nixos.org/guides/building-bootable-iso-image.html

https://nixos.org/manual/nixos/stable/#sec-building-cd (broken https://github.com/NixOS/nixos-homepage/issues/1019)

**Page links**
https://nixos.org/learn.html

**Additional context**
Also check for similar issues.

- [ ] I already created a Pull Request

**Comment by fricklerhandwerk** [comment]
Not relevant any more since the guides are fully moved to nix.dev.
