### ISSUE TITLE
The event funding page doesn't specify how to get reimbursed

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nixos-homepage#1034]
**Introduce your stance**

https://nixos.org/community/event-funding.html tells how to apply for funding for a given event, but not how to send the bills and get the reimbursement after it has been approved.

cc @domenkozar 

**Page links**

https://nixos.org/community/event-funding.html

- [ ] I already created a Pull Request

**Comment by zimbatm** [comment]
Fixed by #1036
