### ISSUE TITLE
Learn page is broken

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixos-homepage#1058]
**Describe the glitch**

Guide links cannot be seen.

**Screenshots**

![image](https://github.com/NixOS/nixos-homepage/assets/314564/a46add2d-b59f-45f2-95b8-cae3ddc61134)

**Comment by nh2** [comment]
Can confirm, was observed by multiple NixOS Zurich meetup ZHF hackathon visitors today, in multiple browsers.

**Comment by fricklerhandwerk** [comment]
Closed by #1054. @zmitchell (or me if that fails) will set up redirects so existing links/bookmarks stay alive.
