### ISSUE TITLE
consolidate all manuals into a Guide to the Nix ecosystem

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixos-homepage#106]
The manuals for nix, nixpkgs, disnix and nixops are hardly discoverable from the front page. Moreover, it is often not easy, given a question about one of the nix\* tools, where its answer will lie: changing the behavior of nixos might involve using a function from nix's base library. The manual linked from the front page should be a "Guide to the Nix ecosystem" linking to the other manuals, and there should be more links between the various manuals, at least in the "descending" direction (ie nixops > nixos > nixpkgs > nix).

**Comment by garbas** [comment]
This has now been partially address on Learn page, where we made manual more discoverable, by exposing parts of the table of content of the manuals.

"Get started" button on the landing page will most likely point to some of the guides that are being worked on as part of #443.
