### ISSUE TITLE
Could't reproduce the redis minimal example

### ISSUE THREAD

**Issue by qwqawawow** [NixOS/nixos-homepage#1073]
**Introduce your stance**
The content of the example

**Describe the issue**
The redis minimal example is not 
not reproducible on the latest channel
nix-build 
`/nix/store/wnsxnkv86ax8f7r2r0qb25bcymg7n9s8-binutils-2.40/bin/ld: cannot find -lssl: No such file or directory              /nix/store/wnsxnkv86ax8f7r2r0qb25bcymg7n9s8-binutils-2.40/bin/ld: cannot find -lcrypto: No such file or directory
collect2: error: ld returned 1 exit status                    make[1]: *** [Makefile:374: redis-server] Error 1
make[1]: Leaving directory '/tmp/nix-build-redis-7.0.11.drv-0/redis-7.0.11/src'
make: *** [Makefile:6: all] Error 2`

**Page links**
https://nixos-homepage.netlify.app/#asciinema-demo-cover
https://github.com/NixOS/nixos-homepage/blob/master/demos/cover.scenario

**Additional context**

- [ ] I already created a Pull Request

**Comment by garbas** [comment]
@qwqawawow Thank you for reporting this and sorry for waiting, I've missed this issue somehow. I nobody beats me I'm going to look at it today/tomorrow.

**Comment by qwqawawow** [comment]
> @qwqawawow Thank you for reporting this and sorry for waiting, I've missed this issue somehow. I nobody beats me I'm going to look at it today/tomorrow.

@garbas 
Sir, I'm sorry to disturb you. Is there any news? I am a student and have no experience in building such image or any Cpp software

**Comment by jiaqiwang969** [comment]
I also meet this problem. 
Find same in below links. But not be solved yet
https://discourse.nixos.org/t/nix-docker-buildlayeredimage-musl-static-build-issue/15153/2

**Comment by qwqawawow** [comment]
> Actually, I try to fix it by add "buildInputs = old.buildInputs ++ [ staticOpenssl]". It fixs the error. "staticOpenssl" is build very similar like redis.
> 
> however, the size is 60M, which is not minimal at all.
> 

You can use pkgsStatic.redis and remove Systemd.
And u need to skip test on building pkgsStatic.jemalloc
