### ISSUE TITLE
Remove NixOS weekly from Blog

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixos-homepage#1093]
**Describe the issue**
The [Blog](https://nixos.org/blog/) link shows NixOS weekly as the first entry, but NixOS weekly is effectively deprecated and hasn't been updated in over 2 years.

I think NixOS weekly should be removed the Blog tab and the Announcements should instead be the first thing people see.

**Page links**
https://nixos.org/blog/

- [ ] I already created a Pull Request

**Comment by Abhijay007** [comment]
hi, @infinisil can I work on this issue?
