### ISSUE TITLE
Manuals have no variants that make offline reading easy

### ISSUE THREAD

**Issue by afrepues** [NixOS/nixos-homepage#110]
It would be very useful to make available variants of the manuals that are easy to use for offline access (PDF, ePUB).

I am willing to work on this, but might need some guidance.

**Comment by garbas** [comment]
@afrepues are you still interested in working on this issue? For now I'm closing this, but you are interested please open it and lets continue having a discussion.

**Comment by afrepues** [comment]
@garbas now is that I saw this, I am still interested, what would be the next steps?

**Comment by garbas** [comment]
@afrepues I would wait what will be the outcome of [RFC 64](https://github.com/NixOS/rfcs/pull/64). It looks like the deadline to make decision is being set.
