### ISSUE TITLE
"Getting Nix" page has incomplete verification instructions

### ISSUE THREAD

**Issue by jamesgecko** [NixOS/nixos-homepage#111]
On the [Getting Nix](https://nixos.org/nix/download.html) page, the command `gpg2 --verify ./install.sig` fails on macOS with the message:

```
gpg: assuming signed data in './install'
gpg: Signature made Mon Oct  3 14:16:28 2016 EDT using RSA key ID 6D7198DE
gpg: Can't check signature: No public key
```

[The internet says](https://stackoverflow.com/questions/25074877/cant-check-signature-public-key-not-found) I'm getting this error because I don't have the public key used to generate the signature. I'm having difficulty finding such a public key on the website.

The documentation should include information about where to find Nix's public key.

**Comment by gevans** [comment]
I ran into this problem too. You can fix this by using `gpg --recv-keys`:

```
$ gpg --recv-keys B541D55301270E0BCF15CA5D8170B4726D7198DE
gpg: requesting key 6D7198DE from hkps server hkps.pool.sks-keyservers.net
gpg: key 6D7198DE: public key "Eelco Dolstra <edolstra@gmail.com>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   5  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 5u
gpg: next trustdb check due at 2018-08-19
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

$ gpg --verify install.sig install
gpg: Signature made Fri Jan 13 02:35:59 2017 PST using RSA key ID 6D7198DE
gpg: Good signature from "Eelco Dolstra <edolstra@gmail.com>" [unknown]
gpg:                 aka "Eelco Dolstra <eelco.dolstra@logicblox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B541 D553 0127 0E0B CF15  CA5D 8170 B472 6D71 98DE
```

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by coderfromhere** [comment]
@domenkozar @edolstra 

What happened to the verification step in the docs and the PGP signature in release folders? It's no longer part of the release distribution starting from [`2.12.1`](https://releases.nixos.org/?prefix=nix/nix-2.12.1/).

**Comment by fricklerhandwerk** [comment]
Releases are no longer signed.
