### ISSUE TITLE
Mastodon icon missing in the footer

### ISSUE THREAD

**Issue by badboy** [NixOS/nixos-homepage#1114]
**Describe the glitch**
The Mastodon link in the footer has no icon.

**Screenshots**

![nixos org footer](https://github.com/NixOS/nixos-homepage/assets/2129/907c32cb-4a8f-49c7-a734-b156bda58577)

**Additional context**

The link was added in https://github.com/NixOS/nixos-homepage/pull/1043.
In the comments there it was noticed the icon is missing, but nothing was done about it.

**Comment by badboy** [comment]
While we're at it: might be worth adding something like "Official Account" in the mastodon bio.

**Comment by drupol** [comment]
I also have this issue.

**Comment by drupol** [comment]
Issue fixed in https://github.com/NixOS/nixos-common-styles/pull/27
