### ISSUE TITLE
Download page: open the OS specific tab on page load 

### ISSUE THREAD

**Issue by roberth** [NixOS/nixos-homepage#1115]
**Introduce your stance**

MacOS users generally want to install Nix on their own system. I can't exclude the possibility that they want to install it on Ubuntu, but that's what the tab menu is for.

**Describe the issue**

When opening the download page on Safari, it shows the Linux instructions.

This comes across as inattentive, even if it's not a huge problem.

**Page links**

https://nixos.org/download

**Additional context**

Probably there's a more clever way to check for macOS rather than just Safari.

**Comment by VedantWankhade** [comment]
I would like to implement this if no one else is already working on it.

**Comment by thilobillerbeck** [comment]
Thx, I assigned you

**Comment by VedantWankhade** [comment]
https://github.com/NixOS/nixos-homepage/blob/7a083dfaf12c2fda27d02ebabd80f574c29cce3d/src/components/pages/download/DownloadAccordion.astro#L69

The initial active tab is set here. Adding logic to set it according to the user's OS should do the trick.
I am assuming the following requirements:
1. If the user is on windows, it should open the windows tab
2. If the user is on macos, it should open the macos tab
3. For all other cases (including linux desktop or any mobile OS), it should default to the linux tab

Please let me know if the above assumptions are correct.

**Comment by thilobillerbeck** [comment]
Yes, that should be fine 👍

**Comment by VedantWankhade** [comment]
Thanks! I have created a pr - #1368
