### ISSUE TITLE
Hourly CI updates broken due to protected main branch

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixos-homepage#1138]
Since about 3 weeks ago the hourly CI updates and deploys started failing due to branch protection seemingly being turned on at that point. This leads to the unstable manuals on the homepage being very outdated.

This is the first CI update failure: https://github.com/NixOS/nixos-homepage/actions/runs/6386890594/job/17334343347

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Changes must be made through a pull request.        
To https://github.com/NixOS/nixos-homepage
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/NixOS/nixos-homepage'
```

Should be fixed by just turning off branch protection again.

Ping @NixOS/marketing-team

**Comment by garbas** [comment]
thank you @infinisil I've removed the protection.

**Comment by infinisil** [comment]
The update failed, but I submitted a fix here: https://github.com/NixOS/nixos-homepage/pull/1142

**Comment by infinisil** [comment]
Yet again branch protection has been turned on, breaking the regular updates.. https://github.com/NixOS/nixos-homepage/actions/runs/8855609505/job/24320730665

**Comment by infinisil** [comment]
The last succeeding build was [1.5 months ago](https://github.com/NixOS/nixos-homepage/actions/runs/8225739597)! This is why I'm not finding any updates to the manuals recently :disappointed:

**Comment by thilobillerbeck** [comment]
unfortunately I don't have the rights to fix this, tagging @garbas here

**Comment by infinisil** [comment]
Update on this: So there's a new separate workflow that only runs _weekly_ now and opens _PR's_ instead of pushing directly. And apparently the old workflow that ran daily and does direct pushes hasn't been removed yet. Makes all sense now!

It is unfortunate that even the unstable manual only gets updated once a week now.. Originally it was once an _hour_!
