### ISSUE TITLE
Enable IPv6 support on CloudFront / cache.nixos.org

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-homepage#116]
CloudFront now supports ipv6 in multiple edge locations, and appears to be in all edges we use: https://ipv6deployedtoyouredgelocation.com/index.html

Users should be able to fetch substitutions using IPv6 to access our cache.

**Comment by davidak** [comment]
The link is dead and i think we use Fastly now instead of CloudFront.

https://ready.chair6.net/?url=cache.nixos.org sais that IPv6 connection works.

So can this get closed?
