### ISSUE TITLE
(Astro rework) DaisyUI themes and components

### ISSUE THREAD

**Issue by kacperwyczawski** [NixOS/nixos-homepage#1162]
DaisyUI supports custom themes and colors. IMO it would be better to declare nix brand colors using DaisyUIs semantic color names. This way, colors could be used in tailwinds utility classes, almost like before, and also these colors would be used in DaisyUI components giving us nice consistency. See DaisyUI docs for more details: [Colors](https://daisyui.com/docs/colors/) and [Themes](https://daisyui.com/docs/themes/). Also, this way it would be easier to implement dark theme.

Furthermore, some simple components could be implemented by customizing DaisyUI components using either tailwinds `@apply` or DaisyUI theme variables. This way it would be easier to apply additional utility classes when needed, and it would give us more flexibility & simplicity. Additionaly it would work well with custom themes described above. For example, by customizing default DaisyUI `btn` component it would be possible to just slap `btn` class on `<a>`, `<button>`, `<input type="button">`, etc. instead of creating Astro component that have to implement all those html elements. Moreover we could add `btn-primary/secondary` to quickly change styles based on defined theme, without additional code. Relevant links:
- https://daisyui.com/docs/customize/
- https://daisyui.com/docs/themes/#-5

**Comment by thilobillerbeck** [comment]
since we'll drop DaisyUI this is not relevant anymore
