### ISSUE TITLE
Enable IPv6 for NixOS.org

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-homepage#117]
AWS is slowly rolling out support for VPC instances to have IPv6 and IPv4 addresses. Currently, the support is only in US-East (Ohio) but when it becomes available in the region nixos.org is hosted in,  we should support it.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html

Users should be able to view the NixOS.org website using IPv6.

**Comment by mweinelt** [comment]
With an IPv6-only setup I'd currently be unable to fetch https://nixos.org/channels/nixos-unstable, breaking `nixos-rebuild switch --upgrade`.

However that URL just forwards to a bunch of CloudFront host, that have dualstack support.

**Comment by Mic92** [comment]
eu-west-1 (where nixos.org is hosted) also has ipv6 since some time.

**Comment by andir** [comment]
Would totally appreciate IPv6 reachability. Wanted to use NixOS in my IPv6 only environment and then hit the legacy IP wall :/

**Comment by Mic92** [comment]
Things todo:

- [ ] Add ipv6 support for AWS in [nixops](https://github.com/NixOS/nixops/)
- [ ] Allocate ipv6 subnet in [nixos-homepage](https://github.com/NixOS/nixos-homepage//)

**Comment by vcunat** [comment]
Another nice-to-have: DNSSEC.  (For many cheap hosters, including mine, it's just about clicking in a checkbox.)

**Comment by Mic92** [comment]
United domains where this domain appears to be hosted, does not offer that.

**Comment by tambry** [comment]
It's been a while. Any news on this?

**Comment by edolstra** [comment]
No. AFAIK NixOps doesn't have the necessary support for IPv6 on EC2 yet.

**Comment by edolstra** [comment]
Closing for https://github.com/NixOS/nixos-org-configurations/issues/29.
