### ISSUE TITLE
Give the channels cloudfront endpoint a CNAME under nixos.org

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixos-homepage#118]
It appears that the cloudfront endpoint for nixos.org/channels is different from the one on cache.nixos.org. It'd be helpful for certain whitelisting/consistency uses (mostly behind restrictive firewalls) if there was a cname for it under channels.nixos.org or something like that.

**Comment by copumpkin** [comment]
cc @edolstra @rbvermaa in case you're not monitoring this repo much

**Comment by davidak** [comment]
@copumpkin is it still the case? How can i test it?

When i click one channel, it links to `releases.nixos.org`, e.g. https://releases.nixos.org/nixos/18.09/nixos-18.09.1985.749a3a0d00b

**Comment by edolstra** [comment]
Yeah, I think we can close this.
