### ISSUE TITLE
nixos-homepage has no license

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-homepage#121]
Someone was talking about sending patches to this repo, but isn't able to unless a license is clearly specified, due to their work.

**Comment by ToxicFrog** [comment]
That might have been me, but even if it wasn't, it's an issue for me too.

**Comment by edolstra** [comment]
Anybody have a preference for a license? Maybe CC BY-SA?

**Comment by ToxicFrog** [comment]
I thought CC-* were discouraged for code? Why not the same license as nixpkgs (MIT, looks like?)

**Comment by edolstra** [comment]
Our homepage is mostly not code.

**Comment by grahamc** [comment]
CC BY-SA seems fine to me.

**Comment by davidak** [comment]
I also think CC BY-SA is a good license for websites. Should i create a PR with it?
