### ISSUE TITLE
Asciinema demo contains not reproducible examples

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixos-homepage#1221]
**Introduce your stance**

There has been a broken build reported recently in the unofficial Discord, following the ["Demo"](https://nixos.org/#asciinema-demo-cover).

**Describe the issue**

The succesfull build of the expression defined in `redis-minimal.nix` in that demo can not be reproduced anymore with nixpkgs newer than `nixos-21.09`. The ressource itself is unclear about which `nixpkgs` was used for this, therefore I brute-forced all channels between 2020 and today.

**Page links**

* the demo: https://nixos.org/#asciinema-demo-cover
* the exact code in question: https://github.com/NixOS/nixos-homepage/blob/master/demos/cover.scenario#L80-L94

**Additional context**

- [ ] I already created a Pull Request

**Comment by Welding-Torch** [comment]
Yep, doesn't work. Just tried this in Google IDX. Kindly request that the devs fix this example on the homepage of https://nixos.org

Here are the commands that I ran exactly while following along with the demo:
```bash
nix-build docker-redis.nix -o ./result
docker load -i ./result
docker images | grep redis #This showed me only nix-redis 164MB
# At this point, I wrote redis-minimal.nix followed by docker-redis-minimal.nix
nix-build docker-redis-minimal.nix -o ./result
docker load -i ./result
docker images | grep redis #This showed me only nix-redis 164MB
```
Note: The output `result` file is 54.08MB. I couldn't get this to change.

You may reproduce these steps, if needed.
