### ISSUE TITLE
mastodon social link image is black, but should be white

### ISSUE THREAD

**Issue by fidgetingbits** [NixOS/nixos-homepage#1227]
**Describe the glitch**
The mastodon social icon at the bottom right of the page is black, whereas all the others are white.

**Screenshots**
![Screenshot_20240225-131612_Firefox Beta~2](https://github.com/NixOS/nixos-homepage/assets/13679876/77c1a826-5d54-49f3-a98e-063020739b4d)

**Additional context**
Seems all svg social icons use .black(), so perhaps the meaning is inverse for that mastodon svg?

https://github.com/NixOS/nixos-homepage/blob/1dcbd0cdfe95e4b39a5fab48bfb13fc10403aed2/site-styles/pages/community.less#L71

**Comment by Isaiah-Hamilton** [comment]
@fidgetingbits This issue seems to have been fixed

**Comment by thilobillerbeck** [comment]
yup, this is resolved
