### ISSUE TITLE
[Techstack-Beta] Code Cinema frame has glitched size

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nixos-homepage#1230]
**Describe the glitch**
The frame around the code cinema on the homepage is too big in the redesigned page, making the main content misaligned and covering part of the "reproducible" section.

**Screenshots**
What it looks like on nixos.org:

![IMG_3775](https://github.com/NixOS/nixos-homepage/assets/9742635/c8490c10-3afd-4ac2-878f-c368d9f83ed1)

What it looks like on https://main--nixos-homepage.netlify.app/:

![IMG_3776](https://github.com/NixOS/nixos-homepage/assets/9742635/512ecd71-9ee9-4263-8a9a-cf06bc55cd15)

**Additional context**
I only tested this on iOS Firefox.

Sidenote: It also says "Reproducable" in the new version, which is wrong. "Reproducible" is the correct spelling.

**Comment by garbas** [comment]
This is already fixed, please reopen if not true.
