### ISSUE TITLE
[Techstack-Beta] Fix hero button text alignment on mobile devices

### ISSUE THREAD

**Issue by thilobillerbeck** [NixOS/nixos-homepage#1236]
**Describe the glitch**
The alignment of the hero button text looks a bit out of place on mobile devices.

**Screenshots**
![image](https://github.com/NixOS/nixos-homepage/assets/7442383/564b35c3-c569-4002-917a-2e88e8d25ca2)

**Comment by thilobillerbeck** [comment]
![Screenshot_20240229-192424.png](https://github.com/NixOS/nixos-homepage/assets/7442383/d32ddb3b-54be-4a6b-ba62-fe5cee505e81)

Original for reference

**Comment by garbas** [comment]
Closed in #1241
