### ISSUE TITLE
[Techstack-beta] RSS feed missing

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1245]
Previous URL

 - https://nixos.org/blog/announcements-rss.xml

Same URL on the new site

 - https://main--nixos-homepage.netlify.app/blog/announcements-rss.xml

I finally got this to build, and I see there are feeds

```
dist/blog/feed-newsletters.xml
dist/blog/feed-stories.xml
dist/blog/feed-announcements.xml
dist/blog/feed.xml
```

So, a couple issues

1. Not advertised in the `<head>` via a `<link>`
2. Changing the URL, which seems unneeded
3. No new redirects added

* * *

*Relatedly*, we were exposing the XML used for the announcements on the site:

-  https://nixos.org/blog/announcements.xml

I don't exactly know why, and what could be using this. Not knowing doesn't mean it should be thrown aside.

**Comment by thilobillerbeck** [comment]
Should be fixed with the linked PR

Since we changed over from DocBookXML to Markdown anyway I would discuss if we should still provide an XML file or maybe replace it with something lke a raw HTML file or something similar that is semi structured.
