### ISSUE TITLE
[Techstack-beta] Missing active state in top navigation

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1246]
Top, the old navigation. Bottom, the new navigation.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/1a56830a-41e9-4d06-9086-f117553c37f2)

There is no active state for the current page in the menu (where possible).

Since this is a new stack, the plan always was to have sub-pages show the section as active. So e.g. a team page would have the community link active. (The previous stack did not allow for that.)

Also an issue in narrow view

![image](https://github.com/NixOS/nixos-homepage/assets/132835/9aa2621a-29f3-4940-bacb-2efebee147ce)

**Comment by thilobillerbeck** [comment]
yeah I noticed this already, something with not seeing the wood for the trees :D

will be fixed shortly
