### ISSUE TITLE
[Techstack-beta] Blog: URLs/categorization

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1250]
Since this changes the presentation and contents of the section, I'll add notes about that.

URLs are meant to last. As such, deciding on their format is important.

Dated content *should* include the date in some form in the URL, it is useful UX-wise when faced with a bare URL, and also prevents duplicate generated URLs from being an issue.

The date should also be front-loaded in the URL, such that `sort`ing them naturally orders them chronologically.

I was about to say that it also has the benefit of making the source easier to deal with, but I see it's already dated in the source. So in reality, the data already is there.

**Comment by thilobillerbeck** [comment]
> URLs are meant to last. As such, deciding on their format is important.

While I don't think anyone probably would really rad the URLs (except for release announcements), I agree that it is maybe a good idea to add at least the year in front of every post
