### ISSUE TITLE
[Techstack-beta] Design: Narrow menu has white margins

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1254]
The narrow menu was design to fill the width, as its own "area", not as an extension of the top bar.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/5c0476f4-1416-4799-9c36-e81e4f2f7780)

**Comment by thilobillerbeck** [comment]
While a good intention another issue this opens is that now on the top and lower part of the mobile nav, the buttons meander into the rest of the background and it is not clear for the user where a click would actually trigger an action. Thus the decision was made to give every button the same style. I also think that the group of buttons as well as the clear border at the bottom provide a clear distinction for where the menu starts and where it ends.

**Comment by garbas** [comment]
I think actually current solution is better. But we'll still have to fix the colors sometime in the future.
