### ISSUE TITLE
Download hashes incorrectly labeled

### ISSUE THREAD

**Issue by saghm** [NixOS/nixos-homepage#126]
Hi! Sorry if this is the wrong place to open this issue, but I wasn't quite sure where the correct place is.

I noticed that the hashes on the [download page for unstable builds](https://nixos.org/channels/nixos-unstable) are labeled as "SHA-512 hash", but the hashes appear to actually be SHA-256. For example, the results of running `sha512sum` and `sha256sum` on the most recent (02/11/2017) graphic unstable image are:

```
# sha512sum
d74e3a304f5391874fa3db7eb8993d86a0634a7937face9f21b5b7050d06b68b015ae12eef667379700e8175ccb964358dd56c4b34623e60ba5fae4de2c8b25f  nixos-graphical-17.03pre100741.20eac78-x86_64-linux.iso
```

```
# sha256sum
b19086c9303b81333a87b8ba84f3cfa3e5db20c6cb7eac072c98110e4c207b1d  nixos-graphical-17.03pre100741.20eac78-x86_64-linux.iso
```

The latter of these is hash that's listed on the downloads website.

**Comment by domenkozar** [comment]
Cc @edolstra

**Comment by samueldr** [comment]
*Looking at the link, this issue seems to have been fixed*
