### ISSUE TITLE
[Techstack-beta] Learn: How Nix Works markup

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1264]
Markup in commands blocks is broken:

 - `$ nix-env --upgrade _some-packages_`
 - `/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-sshd\_config`
 - `$ ./result/bin/run-\*-vm`                                

![image](https://github.com/NixOS/nixos-homepage/assets/132835/6eba1789-0b6c-4a09-9603-3934dfab33e8)

![image](https://github.com/NixOS/nixos-homepage/assets/132835/fa3f3283-af2b-446d-abb3-0ddcc24e82c8)

![image](https://github.com/NixOS/nixos-homepage/assets/132835/a3d2299c-1832-45f0-a614-fc4ca94451bd)

Additionally, markup in text, starting at *Reproducible system configurations*, is lost.

Outline added to highlight the difference; Screenshot only shows first paragraph as an example.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/242c5eba-37cf-4828-a58f-f52ce01662d6)

**Comment by thilobillerbeck** [comment]
btw. leaving the nixos-config snippet with the default code block theme is intentional. While highlighting the store paths in a different way makes sense, highlighting code snippets does not so much imo.
