### ISSUE TITLE
[Techstack-beta] Community: Board details

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1269]
The content was "block-centered", both to make the titles centered all the time, and to make it so on narrow viewports they are centered with the NixOS Foundation logo.

In the new implementation, they are left-aligned, unhooking them from their context.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/f776f039-43b5-4147-9147-a53bd3b4fd7e)

Note that the board observers section *should* have had its list width equivalent to the previous list, but that was added after the initial implementation.

**Comment by thilobillerbeck** [comment]
The thing is that the current implementaiton just breaks this at another point. While the whole site has text starting left aligned this is the only point where this changes. I know this is neither a proper solution but I'm unsure if the old one really is. For me it looks off. I maybe have a solution for this, hold on.

**Comment by thilobillerbeck** [comment]
![localhost_4321_community](https://github.com/NixOS/nixos-homepage/assets/7442383/497c5a86-d84c-408e-a7e6-135ad820144b)

How about this?
