### ISSUE TITLE
[Techstack-beta] Homepage: example title diff.

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1273]
The title for *Declarative development environments* was changed to *Declarative dev-environments*.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/d41455ea-95d2-4c16-8c45-9ba3b2891ad3)

**Comment by thilobillerbeck** [comment]
Yes, I've done this because it broke into two lines on smaller grids or screens. I didn't want to hack something together with CSS so I decided on shortening development to dev with context kept, there are no line breaks now.

**Comment by samueldr** [comment]
Just a warning, but content will change and text will wrap. This is the trap with web development. One cannot avoid dealing with multi-line content.

And this is already an issue.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/bfa20426-f24d-4ab6-8a61-ba490aadd41a)

**Comment by thilobillerbeck** [comment]
To be absolutely fair, your example became an issue after the change has been made and tested and another change in layout was made.

While I agree with you on dynamic content this does not have to be true for static one.
