### ISSUE TITLE
[Techstack-beta] Homepage: Asciinema player content cropped on narrow

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1274]
The content doesn't scale down enough, nor is it scrollable, when view in narrow mode. (Paused at the same moment in both views.)

![image](https://github.com/NixOS/nixos-homepage/assets/132835/0e3f59eb-64e3-4623-a4bd-df209a7e3935)

**Comment by thilobillerbeck** [comment]
hmm, I think for now we wont finde a good common ground here. We can choose either between tiny text and cropped text. :/

**Comment by thilobillerbeck** [comment]
I already tried to make the asciinema scrollable. Maybe we can live with one of the problems for now since there will be some changes being done to the asciinema anyway in the near future.

**Comment by samueldr** [comment]
It is okay if the asciinema player font is small.

Either the window is in narrow view on a desktop, which can be resized to see better, or on a device where pinch-to-zoom will work out fine to read the text. Though I guess there might be outlier situations out there? I don't know what one would be where you can't zoom to view better, nor change the viewport size...
