### ISSUE TITLE
[Techstack-beta] Design: Wordmark on logo is incorrect

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1279]
It's the wrong font, and the wrong size and metrics.

The following visualization illustrates the problem by using the [NixOS logo](https://github.com/NixOS/nixos-artwork/blob/master/logo/nixos.svg), removing the `OS`, changing the colour to light red, and attempting to scale *as precisely as possible* according to the lambdaflake (left part) on top of a 2× magnified screenshot of the site.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/6f153463-7ef4-45ba-937d-6c82aa005caa)

The fringing is a non-issue, SVG being rendered by different engines, and working on a rasterized version of it.

Though, observe on the left that the `Nix` wordmark is positioned basically as close as possible under the conditions, while the `Nix` wordmark on the right is not.

Ignoring the lambdaflake, the text is not correct, since this is not the correct font. This was aligned on the vertical bar of the I, in height.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/08b7a0bd-4655-4fb5-a7bc-6c6e5b2f8711)

And note that the text was manually kerned by the logo author, so even attempting to get the webfont going is not going to get the correct result.

**Comment by samueldr** [comment]
Same comparison applied to the current fixed version

![image](https://github.com/NixOS/nixos-homepage/assets/132835/85ff6b7d-b0cf-4c30-9fe4-2e5171304863)

At 200%, aligned to the bar of the `i`, then to the pixel grid.

It could do with a "1px"-equivalent nudge closer, but otherwise is *good enough*.

**Comment by thilobillerbeck** [comment]
I can take a look at that, maybe this comes from the images being split to save on lading costs. This can definitely be improved.
