### ISSUE TITLE
[Techstack-beta] Homepage: Missing title tagline

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1280]
That might not be a bug, might be a different decision, but this is a notable difference.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/99074cc5-2f95-4916-8847-979f5ba916fd)

For the full text:

 - https://github.com/NixOS/nixos-homepage/blob/72fcddd779a48fd150428322f9276d18fbab34ea/layout.tt#L36-L40

**Comment by thilobillerbeck** [comment]
hm, I remebered this working, lets see why it broke
