### ISSUE TITLE
 [Techstack-beta] Site-wide: console and code blocks styles inconsistent

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1292]
Both inconsistent within the new site, and inconsistent with the previous implementation.

* * *

Here's a screenshot from the Download page, where the new implementation is proper for a commands block:

![image](https://github.com/NixOS/nixos-homepage/assets/132835/d0d7d4c0-0a8b-4d8b-874e-fde571fc6ffd)

* * *

Here's, comparatively, a screenshot from the *How Nix Works* page, showing an off-model commands block:

![image](https://github.com/NixOS/nixos-homepage/assets/132835/92f86ab7-867e-4195-a7e6-4e601e103707)

* * *

You may have noticed I'm using *commands block* here. This is because a stylistic decision was made to have code blocks on light, and terminal sessions on dark.

Source code blocks are always off-model in the new implementation.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/1bbca052-701c-4e9c-895f-26846d555a5d)

* * *

Side-note: the only *story* in the *stories* section is off-model in the old site.

**Comment by thilobillerbeck** [comment]
Will he part of a fix shortly
