### ISSUE TITLE
nixos-shell - possible merge?

### ISSUE THREAD

**Issue by rlupton20** [NixOS/nixos-homepage#130]
While trawling through general internet guff, I happened across this: https://github.com/chrisfarms/nixos-shell

While `nix-shell` is already incredibly powerful, I wondered if there may be some merit in merging this, or re-implementing it, or perhaps enhancing `nix-shell` to make this a normal feature (if it isn't already, and I just don't know about it).

I have in mind testing new system configurations, testing system descriptions for docker container provisioning, nixops etc.

It should be possible to provide such a thing without sudo privileges too (but perhaps group membership), which I think would be preferable.

Thoughts?

**Comment by garbas** [comment]
this would be better to be raised at https://nixos.org/nixos/nixpkgs repo.
