### ISSUE TITLE
 [Techstack-beta] Site-wide: Links aren't using border-bottom for their underline

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1304]
See https://github.com/NixOS/nixos-homepage/pull/538.

cc @garbas.

At the time it seemed important enough to require it is done (even through the problems it caused).

**Comment by thilobillerbeck** [comment]
I think we should tweak the underline offset instead https://tailwindcss.com/docs/text-underline-offset

**Comment by garbas** [comment]
[text-underline-offset](https://tailwindcss.com/docs/text-underline-offset) solved the problem. But I did made it a bit ticker to match our previous border bottom.
