### ISSUE TITLE
 [Techstack-beta] Site-wide: Search icon

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1306]
This is aimed at @garbas.

* * *

I'll note that the search icon used on the site is one the designer you'd hired made(?) for us.

It feels odd to throw that away.

(I personally don't mind, only bringing this up as a notable difference.)

**Comment by thilobillerbeck** [comment]
The decision came from my side and I thought it would be better to use only one Icon set (Material Icons) for the UI instead of different ones.

**Comment by garbas** [comment]
Thanks for noticing this. I think we'll just go with the Material fonts since than we don't have to go back to the designer for every icon.
