### ISSUE TITLE
[Techstack-beta] Site-wide: buttons on narrow

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1308]
- Text should be centered
 - Buttons should fill width

**Download**

![image](https://github.com/NixOS/nixos-homepage/assets/132835/2db6cee7-4892-4701-94d3-bb4881ced7d5)

(Note that on that page, in the old version, the wide button gained an incorrect margin... Not to be reproduced.)

**Donate**

![image](https://github.com/NixOS/nixos-homepage/assets/132835/7fbddbba-bfa2-41cb-8036-7ef8373e9b8e)

![image](https://github.com/NixOS/nixos-homepage/assets/132835/a8ac8154-ec34-48fe-b6d3-078a485b252f)

(Incorrect text alignment)

**Comment by garbas** [comment]
Already fixed
