### ISSUE TITLE
Homepage must be built on a linux box

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixos-homepage#131]
Seems kind of unfortunate that the webpage build cares about the system it's being built on.  This is what happens on macOS:

```
$ nix-shell --command make
rm -f nixos/manual-raw
nix-build -o nixos/manual-raw '<nixpkgs/nixos>' -I nixpkgs=https://nixos.org/channels/nixos-16.09/nixexprs.tar.xz \
  -A config.system.build.manual.manual --arg configuration '{ fileSystems."/".device = "/dummy"; }'
error: assertion failed at /nix/store/1c993kdy0vhfbs6ql0yx7rnifb2m5i8a-nixexprs.tar.xz/pkgs/os-specific/linux/kernel/generic.nix:32:1
(use ‘--show-trace’ to show detailed location information)
make: *** [Makefile:33: nixos/manual-raw] Error 1
```

**Comment by garbas** [comment]
@copumpkin I'm closing this for reason that I don't have an osx to test this and even if i would have this would be very low on my todo list. the current toolset to build nixos website is big. it is what it is and we can not change it, but going forward i will keep in mind that we also need to be able to build this on osx. if that day when we will rething how we build nixos.org ever comes :)
also please feel free to reopen if you want to work on this. I'm only trying to keep issues, which i think we will be able to address in reasonable amount of time, open.
