### ISSUE TITLE
[Techstack-beta] Homepage: Asciinema player content still cropped on narrow, and now small

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#1323]
#1274 was closed with #1316 though incomplete.

* * *

This is still being cropped on narrow (iPhone SE metrics, or larger still...)

![image](https://github.com/NixOS/nixos-homepage/assets/132835/b8603391-cf38-4169-a628-731598513096)

And now the wider versions look *off*

![image](https://github.com/NixOS/nixos-homepage/assets/132835/312978ef-0a88-4b30-bf1c-e3ad23a3dc27)

NOTE: the older website solves this by scaling the font responsively.

![image](https://github.com/NixOS/nixos-homepage/assets/132835/961bcb6c-5a95-44ca-bd7a-e41afdcec6e7)

(And also could be seen as cheating / wisely choosing its fights, by not embedding the player directly in the preview.)

**Comment by garbas** [comment]
For now this is good enough to do the switch. Maybe @ku1ik would like to help us do this properly.
