### ISSUE TITLE
No NixOS Manual Link on the Menu Bar & Lack of Consistent Parallelism in Menu Interface

### ISSUE THREAD

**Issue by ixxie** [NixOS/nixos-homepage#134]
I love the way the menu works on the nixos.org homepage - the idea of parallel menus for each element of the Nix ecosystem is brilliant.

However, the menus of these different elements are sometimes quite radically different. It is very understandable that some of them have less elements since they have less content; what is less understandable is when they have the same element reachable in different ways.

Case in point: in order to reach the NixOS manual, I must first click support and then press the manual; for Nix, NixOps, Nixpkgs, and Hydra I can reach the manual directly from the menu. Finding the Disnix manual is even more confusing than the NixOS one, although I understand if a pdf manual should not be a menu link.

If the maintainers of the site choose to take this under consideration and restructure the menu, a link to the github page of each project should also be considered, as it is becoming increasingly standard.

**Comment by BlessJah** [comment]
Disnix is also affected: https://github.com/NixOS/nixos-homepage/issues/140

**Comment by BlessJah** [comment]
![screenshot](http://i.imgur.com/gZCH9UU.png)

**Comment by garbas** [comment]
This issues has been now address and hopefully provides an easier way to navigate.
