### ISSUE TITLE
Use <kbd>/</kbd> to search

### ISSUE THREAD

**Issue by dev-ardi** [NixOS/nixos-homepage#1382]
**Describe the glitch**
I don't want to have to use my mouse to select the search box! 
This is mainly for https://search.nixos.org/ but it could also be applied to the wiki and other places.

In most places you can use <kbd>/</kbd> to search. Github, gitlab, google search, rustdoc (soon)... It's the default vi key for search so I suggest using that.

**Comment by sudanchapagain** [comment]
I think you have to post this on https://github.com/NixOS/nixos-search/issues

**Comment by crertel** [comment]
@dev-ardi I think this should be good now, is it?

**Comment by dev-ardi** [comment]
Yes, great!

**Comment by dev-ardi** [comment]
I'd like to see the text changed to hint that you can, a bit like docs.rs
![image](https://github.com/user-attachments/assets/3371b450-ba59-4df7-9b9c-887340e2ce19)
