### ISSUE TITLE
Everything is a link where it should not

### ISSUE THREAD

**Issue by Huy-Ngo** [NixOS/nixos-homepage#1412]
## Describe the glitch

Every text in [the manual](https://nixos.org/manual/nixos/stable/) from "Networking in the installer" section is inside an `<a>` tag. They should not be.

## Screenshots

![HTML source of the manual, showing texts that should be plain, but are marked up as links](https://github.com/NixOS/nixos-homepage/assets/19296926/7b2d5bd5-0868-4c4d-8cb8-4c6f2731ba7f)
![texts underlined when hovered like they're links](https://github.com/NixOS/nixos-homepage/assets/19296926/1714bc97-10b5-49f4-bd15-4cda98666c6c)

**Comment by infinisil** [comment]
Ping @DanielSidhion
