### ISSUE TITLE
service.fusuma.settings now use a yml instead of yaml

### ISSUE THREAD

**Issue by lVentus** [NixOS/nixos-homepage#1425]
**Introduce your stance**
fusuma now use yml file instead of yaml file as config file.
now when I use HM service.fusuma.settings, it will generate a yaml file in .config, please update it to change it to a yml file.
and when I use service.fusuma.enable = true; it wont be installed and won't exec when login.

**Describe the issue**
A clear and concise description of what the issue is about.

**Page links**
Please enumerate the page links where to observe the issue.

**Additional context**

- [ ] I already created a Pull Request

**Comment by thilobillerbeck** [comment]
Hi, this repo is for the NixOS Homepage. I guess your issue belongs here https://github.com/nix-community/home-manager. ;) Please reopen it there, thx. :)
