### ISSUE TITLE
Nixpkgs manual outdated and broken

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixos-homepage#1431]
**Introduce your stance**

According to https://github.com/NixOS/nixos-homepage/issues/1138#issuecomment-2094553898, the site is now only advanced weekly but it has now been [over two weeks](https://hydra.nixos.org/build/258517574) since https://github.com/NixOS/nixpkgs/pull/307077 hit nixos-unstable.

**Describe the issue**

https://nixos.org/manual/nixpkgs/unstable/#ssec-gnome-hooks is outdated and inline anchors appear to be turned into links eating the rest of the paragraph (updated CSS manually to make it visible since that is broken too):

![image](https://github.com/NixOS/nixos-homepage/assets/705123/afb9eb1d-4dd2-44c7-a430-a381aba66b28)

Compare with https://github.com/NixOS/nixpkgs/blob/nixos-unstable/doc/languages-frameworks/gnome.section.md#onto-wrapgapps-hooks-ssec-gnome-hooks

**Page links**

https://nixos.org/manual/nixpkgs/unstable/#ssec-gnome-hooks

**Additional context**

The anchor work fine in the local build in Nixpkgs so this must be something with the website (`nix-build pkgs/top-level/release.nix -A manual`).

**Comment by Aleksanaa** [comment]
The link issue is also reported here: https://github.com/NixOS/nixos-homepage/issues/1412
