### ISSUE TITLE
nix-manual redirect ist broken

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixos-homepage#1452]
**Introduce your stance**

When one visits old bookmarks to the nix manual, one gets redirected improperly to the new nix.dev one.

**Describe the issue**

Like I have these bookmarks:

* https://nixos.org/manual/nix/stable/
* https://nixos.org/manual/nix/unstable/

Which now link to the inexisting:

* https://nix.dev/manual/nix/2.18/stable/
* https://nix.dev/manual/nix/2.18/unstable/

deeplinks are similarily broken.

To access the wanted contend one has to manually remove the old stability qualifier and manually adjust the version

**Page links**

See above

**Additional context**

- [ ] I already created a Pull Request

**Comment by con-f-use** [comment]
Can confirm. This is a problem.

**Comment by infinisil** [comment]
See also https://github.com/NixOS/nixos-homepage/issues/1448 and https://github.com/NixOS/nixos-homepage/pull/1451 and https://matrix.to/#/!tPxtoBdChSsxHuBlNW:nixos.org/$TlTHLOrErEmxzWZvC_BcjfmtiPJLoLMSmMqUNnuec8c?via=nixos.org&via=matrix.org&via=nixos.dev

**Comment by thilobillerbeck** [comment]
A fix for this is already merged, unfortunately our deployment process broke for an unknown reason and I can't fix it on netlifys side since I don't have any permissions. 😅

**Comment by NobbZ** [comment]
> See also #1448 and #1451 and [matrix.to/#/!tPxtoBdChSsxHuBlNW:nixos.org/$TlTHLOrErEmxzWZvC_BcjfmtiPJLoLMSmMqUNnuec8c?via=nixos.org&via=matrix.org&via=nixos.dev](https://matrix.to/#/!tPxtoBdChSsxHuBlNW:nixos.org/$TlTHLOrErEmxzWZvC_BcjfmtiPJLoLMSmMqUNnuec8c?via=nixos.org&via=matrix.org&via=nixos.dev)

I had seen the title of #1448 but didn't connect "the redirects for the nix-manual" and "links on nixos.org/learn" in my head.

Thank you for the heads up and I hope you get the deployment issues fixed soon!

<details>
  <summary>How to open Matrix-links?</summary>

How am I supposed to open links to the matrix? When I clich them, I sometimes see "Do you want to open the preview" and after that I always see "which app do you want to use", and there I can select my prefered client, which gets me to an intermediate site, where I either can click "Download" or wait to an XDG-open popup to appear, though after that nothing happens.

I am stuck on this on my NixOS machines as well as my Ubuntu/plasma and on an equivalent workflow on my mobile.

Why is there no "open read only in web"?

I know, you can't really change that, but perhaps at least explain or document a workflow that actually works, ideally without requiring to install additional software or having a matrix account.
</details>

**Comment by garbas** [comment]
This should be now fixed. Please reopen if that is still the case.
