### ISSUE TITLE
broken link to mailing list

### ISSUE THREAD

**Issue by robx** [NixOS/nixos-homepage#147]
Not sure this is more a misconfiguration of mailman, or a missing page in this repo.

Both https://nixos.org/nixos/community.html and the nixpkgs README link to http://lists.science.uu.nl/mailman/listinfo/nix-dev, which in turn redirects to http://nixos.org/nix-dev-info/, which does not exist.

**Comment by vcunat** [comment]
We need to update the web page, as the old list just ended.  It continues on https://groups.google.com/forum/#!forum/nix-devel
