### ISSUE TITLE
Nominate myself as additional maintainer for the homepage.

### ISSUE THREAD

**Issue by hsjobeki** [NixOS/nixos-homepage#1491]
My motivation is to help fix and maintain the homepage of nixos.org. I recognize a growing need for opening PRs and fixing issues and would be happy if i can help out with my expertise and time.

About me: 
- engaged with nix community around 3 years.
- Lead frontend dev at secunet germany (part time) responsible for design system.
- Creator of Noogle.dev
- active Member of documentation team
- author of accepted rfc-145 (doc-comments)
- maintainer at clan.lol, mainly responsible for frontend related tasks.
- Experience with react solid, typescript, astro, python, rust and most other major programming languages.

As i am already a member of the documentation team i am not sure if i have merge rights here and if would be apropriate to use them without having this issue first.

**Comment by thilobillerbeck** [comment]
More helping hands on the homepage are always welcome. As a documentation team member you should have write access anyway. Would be great if you could make it to the marketing team meeting next tuesday at 9pm CET and join our matrix channel so we can onboard you. :)

**Comment by thilobillerbeck** [comment]
Since @hsjobeki is onboarded, I'm closing this
