### ISSUE TITLE
pass usb to docker with xfreerdp

### ISSUE THREAD

**Issue by Bitbitti** [NixOS/nixos-homepage#1498]
hello,
i have a problem. i need to pass some usb devices to a container, but when i launch xfreerdp with the /usb parameter, it gives me this error: libusb_open: error LIBUSB_ERROR_ACCESS[-3]
my config is attacched
thanks
[message.txt](https://github.com/user-attachments/files/16078107/message.txt)

**Comment by tomberek** [comment]
Please see our community resources to get some help with this: https://nixos.org/community/
