### ISSUE TITLE
https://nixos.org/download/ -- design glitch

### ISSUE THREAD

**Issue by sachinchaudhary1808** [NixOS/nixos-homepage#1499]
so on [nixos/download](https://nixos.org/download/) this thing

![image](https://github.com/NixOS/nixos-homepage/assets/138745629/a6f4ccf7-d111-4e00-866a-385f5061edef)

**Comment by thilobillerbeck** [comment]
Well, seems like the markdown rendere decided the button labels should be wrapped into paragraphs :shrug:. Fixed by 37c1938.
