### ISSUE TITLE
NixOs News RSS or Atom feed

### ISSUE THREAD

**Issue by bezirg** [NixOS/nixos-homepage#15]
I cannot find an RSS or Atom feed for the http://nixos.org/news.html

I found a /news.xml page, but this is apparently a custom format.

If you build such a feed, can you also add an RSS icon link somewhere on the homepage?

**Comment by davidak** [comment]
that would be helpful.

also add links to the html head section that browsers displays it:

`<link rel="alternate" type="application/rss+xml"
   title="RSS" href="http://www.example.net/feed.rss" />`

`<link href="atom.xml" type="application/atom+xml" rel="alternate" title="Sitewide ATOM Feed" />`

**Comment by charlieok** [comment]
:+1: Would like to get updates on NixOS in my feed reader. Also looked for a feed and didn't find one. Would subscribe if this were added.

**Comment by ajgrf** [comment]
I wrote a small program to generate an Atom feed from the news.xml page. I run it locally but it would probably be easy to adapt if you wanted to offer an official feed. I posted it as a gist [here](https://gist.github.com/ajgrf/ce07620b7ba5c80583a9).

**Comment by rexim** [comment]
:+1: Would like to stay updated on NixOS that way too. :)

**Comment by noffle** [comment]
I've been wanting an RSS feed for news as well, so I took a stab at this today! (https://github.com/NixOS/nixos-homepage/issues/90)

**Comment by domenkozar** [comment]
It's live: https://nixos.org/news-rss.xml
