### ISSUE TITLE
nix-dev doesn't link to new mailing list

### ISSUE THREAD

**Issue by eqyiel** [NixOS/nixos-homepage#151]
Currently the experience is like 

https://nixos.org/nix-dev/ -> "more information about this list" -> https://nixos.org/nix-dev-info/ (404)

**Comment by edolstra** [comment]
https://nixos.org/nix-dev/ is just an archival dump of the old mailing list. I don't think we link to it anywhere.

**Comment by eqyiel** [comment]
Thanks for the clarification @edolstra, I didn't realise it was just an archive.

Also it looks like the new mailing list is mentioned here: https://nixos.org/nixos/support.html

I guess it can't be helped that https://mailman.science.uu.nl/pipermail/nix-dev/ redirects to https://nixos.org/nix-dev, at least this way old links will continue to work.

Closing!
