### ISSUE TITLE
The NixOS logo on the "Reproducible" section is not centered

### ISSUE THREAD

**Issue by hawl1** [NixOS/nixos-homepage#1510]
**Describe the glitch**
The NixOS logo on the reproducible section is not centered.
It's a small design glitch, but when a person sees it, it's impossible for them to ignore or unsee it.

**Screenshots**
![image](https://github.com/user-attachments/assets/566ec06d-4a97-4223-863b-75f33c289d71)

**Comment by thilobillerbeck** [comment]
Thanks for reporting. Maybe there's something going on while optimizing the images.

> I hope that was intentional.
kind reminder to keep a respectful and kind tonality, we are a few people who do this in our spare time and such things can happen, please refrain from such comments in the future ;)

**Comment by hawl1** [comment]
> Thanks for reporting. Maybe there's something going on while optimizing the images.
> 
> > I hope that was intentional.
> 
> kind reminder to keep a respectful and kind tonality, we are a few people who do this in our spare time and such things can happen, please refrain from such comments in the future ;)

okay, i will be more careful.
