### ISSUE TITLE
Missing wallpaper config options

### ISSUE THREAD

**Issue by Enzime** [NixOS/nixos-homepage#154]
When searching the https://nixos.org/nixos/options.html, all the config options under `services.xserver.desktopManager.wallpaper.*` are missing

**Comment by samueldr** [comment]
I see:

```
services.xserver.desktopManager.wallpaper.combineScreens
services.xserver.desktopManager.wallpaper.mode
```

This must have been fixed meanwhile, I see only two options in the [linked `.nix` file](https://github.com/NixOS/nixpkgs/blob/release-17.09/nixos/modules/services/x11/desktop-managers/default.nix)
