### ISSUE TITLE
Can't download the OS because of low download speed

### ISSUE THREAD

**Issue by babakfp** [NixOS/nixos-homepage#1555]
![](https://github.com/user-attachments/assets/01dac6c3-cee2-436c-8f00-ccf74d9068a9)

This issue has nothing to do with my internet speed:

![](https://github.com/user-attachments/assets/5ffa682e-d51b-4531-b406-a46d8faf00f9)

I can't get NixOS downloaded with or without a VPN.

Are there any mirrors?

**Comment by babakfp** [comment]
😭

![](https://github.com/user-attachments/assets/e3bc7ac0-0550-4915-8ccf-5b34f121c522)

**Comment by thilobillerbeck** [comment]
Hey, we serve the ISOs using fastly. When it gets better using a VPN it is probably due to bad peering on your ISPs side. Unfortunately that is something we can't really fix.
