### ISSUE TITLE
Add the NixOS unofficial wiki to unofficial sources (https://nixos.wiki/wiki/)

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixos-homepage#1575]
**Introduce your stance**
The unofficial wiki is a great (if sometimes outdated) source for configuring NixOS. It often has helpful code blurbs.

**Describe the issue**
https://nixos.wiki/wiki is currently not in the unofficial sources.

**Page links**
https://nixos.org/community/

- [ ] I already created a Pull Request

**Comment by mschwaig** [comment]
The unofficial wiki has been superseded by the official one.

As far as I am aware all of the content has been migrated, but the person running the unofficial wiki is not responsive to cooperating with that effort that effort. So it would be kind of counter-productive to link the unofficial wiki anywhere.

You can read more about that at https://github.com/NixOS/foundation/issues/113 and https://wiki.nixos.org/wiki/NixOS_Wiki:History.

**Comment by drupol** [comment]
If it was only me, I would not mention any single unofficial sources. So here, I agree with @mschwaig here.

**Comment by flyfloh** [comment]
> The unofficial wiki has been superseded by the official one.

And the official wiki is linked to on https://nixos.org/learn/ which is the better place. I'd say this is done.
