### ISSUE TITLE
Installation instructions describes incorrect result on Mac OS X

### ISSUE THREAD

**Issue by daniels** [NixOS/nixos-homepage#158]
*Chapter 4. Installing a Binary Distribution* contains the following information:

> If you are using Linux or Mac OS X, the easiest way to install Nix is to run the following command:
> ```sh    
> bash <(curl https://nixos.org/nix/install)
> ```
> This will perform a single-user installation of Nix, meaning that /nix is owned by the invoking user. [...]

This is no longer true, as the installation script performs a multi-user installation on Darwin-systems.

Also the uninstall instructions should really mention not only the `/nix` directory, the profile directories and any changes made to the bash profile (#99), but also the build users.

**Comment by domenkozar** [comment]
cc @grahamc

**Comment by garbas** [comment]
this was already reported in nix repository.
