### ISSUE TITLE
GPG Verification instructions on Getting Nix page not helpful on stock MacOS

### ISSUE THREAD

**Issue by daniels** [NixOS/nixos-homepage#159]
There is kind of a chicken and egg problem if you want to verify the integrity of the install script on MacOS/OSX as gpg isn't available on the system, and the thing you need to verify is the package manager that you probably would want to use to install it.

Possibly a sha256 checksum could be presented as an alternative?

**Comment by grahamc** [comment]
That is a challenge, for sure!

A few weeks ago, I submitted a PR to add sha256 checksum verification to the instructions. After doing some threat modeling we found it to not be useful and removed it from my PR. Maybe you can help me think through how it helps?

### A malicious actor:
1. The Nix installation script, tarball, and instructions are served from https://nixos.org and the same server.
2. Any malicious actor intent on damaging the contents of the install script or tarball are also equally capable of changing the sha256 on the instructions page to match.

### a partially downloaded tarball
The install script performs a sha256 verification after downloading the tarball, to ensure it has the correct contents.

https://github.com/NixOS/nixos-homepage/blob/master/nix/install.in#L43-L51

### a partially downloaded installer
The install script prevents a partially-downloaded file from executing: https://github.com/NixOS/nixos-homepage/blob/master/nix/install.in#L7

**Comment by daniels** [comment]
Thanks Graham, your explanation helped me realize that what I asked for would not be useful.

I've already been a bit unsure of the usefulness of this kind of checksum to prevent the malicious actor, but eventually accepted it as it is ever present ... Though most often the checksum and the actual download is served from different servers. But then again, compromising the site with the links to each would probably be enough to be able to serve a malicious package to many users.

I'm not sure if or how a signing key from a key server linked from the instructions would help protect your first download if you don't have the key in advance, but I see how it would be much better than a new checksum for each release once you have a trusted key.

I guess the proper way to handle this for a fresh MacOS install then is to make the download on a different machine with gpg and the signing key installed.
