### ISSUE TITLE
How to change application configuration file???

### ISSUE THREAD

**Issue by unixbhaskar** [NixOS/nixos-homepage#173]
Say I have installed screen( a GNU tool) and I have my own screenrc , how to make changes globally in the system with that particular file??

Where to put the file? If I mount /nix/store as read0-write and put the file ..stil it is not reflecting the change..heck.

Why you people make it unnecessary so complicated??? Shed some light.

**Comment by davidak** [comment]
This is not the right place for questions related to Nix packages. Better is IRC or the Mailinglist, or https://github.com/NixOS/nixpkgs to report bugs.

The answer to your question is probably the `programs.screen.screenrc` option of NixOS you find on https://nixos.org/nixos/options.html#screen.

**Comment by unixbhaskar** [comment]
But you haven't told me, where to put that thing in the system....in configuration file?? somewhere else?? where???

**Comment by davidak** [comment]
I don't know what system you are running. I assume NixOS 17.09 as it is the current stable.

There add it to your `/etc/nixos/configuration.nix` like this

```
  programs.screen.screenrc = ''
    ...
  '';
```

**Comment by unixbhaskar** [comment]
Thanks, that's more close answer. Should be in configuration, while building the os it brings it in.

**Comment by davidak** [comment]
Can you close this issue then?

**Comment by unixbhaskar** [comment]
Yup.
