### ISSUE TITLE
Revoked key for Rob Vermaas on NixOS security page.

### ISSUE THREAD

**Issue by thblt** [NixOS/nixos-homepage#174]
@rbvermaa's PGP key [0xE114A5F264A8AE8E](https://pgp.mit.edu/pks/lookup?op=get&search=0xE114A5F264A8AE8E) as listed on the [NixOS security](https://nixos.org/nixos/security.html) page is revoked.

**Comment by Ekleog** [comment]
@rbvermaa Can you update your PGP key on the NixOS security page?

**Comment by JohnAZoidberg** [comment]
This can be closed. The key is no longer listed on the security page.
