### ISSUE TITLE
nixos.com is a porn site

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixos-homepage#179]
I typed nixos.com/nix into my browser and was presented with porn. You should consider trying to buy the nixos.com domain because this is a pretty easy mistake to make.

**Comment by samueldr** [comment]
It might be hard, archive.org has captures going as far back as 2000, yes that website can visit itself!

**Comment by vcunat** [comment]
Doesn't nixos.org have _sysadmin_ porn?

Now, seriously, I wouldn't be inclined to encourage domain name speculation, especially _if_ it were my money...

**Comment by leifmetcalf** [comment]
A WHOIS returns these status codes for nixos.com:

    Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
    Domain Status: clientHold https://icann.org/epp#clientHold
    Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
    Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited

This problem may resolve (ha) itself soon!

**Comment by vcunat** [comment]
For practical purposes it's probably solved (for now?), as the domain isn't delegated anymore.
```
$ kdig nixos.com @k.gtld-servers.net.
;; ->>HEADER<<- opcode: QUERY; status: NXDOMAIN; id: 37585
...
```

**Comment by davidak** [comment]
Is here anything to do?

**Comment by edolstra** [comment]
No, let's close it.
