### ISSUE TITLE
Caching the release tarball

### ISSUE THREAD

**Issue by chrismwendt** [NixOS/nixos-homepage#184]
It's annoying to have to wait ~30s to re-download the release tarball after it throws an error (e.g. because of relics from previous installations). Could the release tarball be downloaded to a deterministic path in `/tmp`?

**Comment by vcunat** [comment]
I'm not sure it's worth the work, but I don't even understand what kind of release tarball you mean (and what process downloads it).

**Comment by chrismwendt** [comment]
@vcunat I'm referring to the tarball from https://nixos.org/nix/install. Check out the PR for this: #185

**Comment by garbas** [comment]
This is now part of the nix repository.
