### ISSUE TITLE
The nix/docs.html file is a ghost!!

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#187]
As [reported on IRC](https://logs.nix.samueldr.com/nixos/2018-02-26#1519619504-1519619591;).

 * https://nixos.org/nix/docs.html

The PDF being unavailable seems to be a result of [some spring cleaning](https://github.com/NixOS/nix/commit/58e423ce323b85d1e440320e2a39947c89c7441b)

Though, the scary part, is that this page isn't in the repository since *30 December 2014*!

 * https://github.com/NixOS/nixos-homepage/commit/d4dc01819993c1db992b1733b1c15602ff8e5de2#diff-393b7e38038f12c5fb4c92e81a1b5a01

![20180226001814](https://user-images.githubusercontent.com/132835/36654426-97dd4250-1a8a-11e8-8ae0-5723e507ac0e.png)

> An example of a ghost of ~~a fish~~ an older webpage.

**Comment by vcunat** [comment]
I suppose we just remove the link, right?  I doubt anyone would print the manual.
