### ISSUE TITLE
Provide archived "packages.json"

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixos-homepage#194]
Right now we provide JSON files of all Nixpkgs under "packages.json" and "packages-unstable.json". It would be nice to archive the older versions of this as "packages-$VERSION.json".

This would be useful in providing visualization of how Nixpkgs has changed over time. For instance in this graph from Repology (which uses the .json files):

![](https://repology.org/graph/map_repo_size_fresh.svg)

**Comment by garbas** [comment]
package.json and options.json are now being generated as part of release artifacts (eg. http://releases.nixos.org/?prefix=nixos/19.09/nixos-19.09.2332.598a9cbed63/). if there is interest and a goo enough use case we can "backfill" for previous releases.

**Comment by davidak** [comment]
@garbas the use case is explained above. visualize how NixOS became the distro with the most up-to-date packages :)

I see Ubuntu 12.04 there. So it would be nice to have as many releases as possible back to 2012.
