### ISSUE TITLE
Combine Nix and Nixpkgs pages?

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#199]
From the maintainer perspective that are two different projects, but from a user perspective it is confusing to separate.

We could unclutter the website more by removing the Nixpkgs page and move the relevant informations to the Nix site.

We can have a "Nix Package Manager User Guide" and "Nix Packages Contributors Guide" linked on the "Manual" page, each in different versions like (unstable, stable, stable-1).

What do you think?

**Comment by jonathn** [comment]
+1
In addition, the total number of packages listed on the 'nixpkgs' page gets outdated:

> "The Nix Packages collection (Nixpkgs) is a set of nearly 6,500 packages"
https://github.com/NixOS/nixos-homepage/blob/master/nixpkgs/index.tt#L4

**Comment by davidak** [comment]
Nixpkgs is the official package collection for Nix. It is not useful alone. So it's part of Nix.

I would like to have it as just one section on the Nix page.

@grahamc what do you think?

**Comment by garbas** [comment]
This has been now addressed
