### ISSUE TITLE
Why the system is complaining for missing autoconf??

### ISSUE THREAD

**Issue by unixbhaskar** [NixOS/nixos-homepage#203]
I have autoconf installed and still, the system spits out this: 

`You must have "autoconf" installed on your system.
             Download the appropriate package for your distribution,`

Builds are failing ...not sure ...mind shedding some light. Well, something` for your eyes

`
[root@NixOS:~]# nix-env -u
upgrading 'docker-18.02.0-ce' to 'docker-18.03.0-ce'
upgrading 'konsole-17.12.2' to 'konsole-17.12.3'
upgrading 'gnome-terminal-3.26.2' to 'gnome-terminal-3.28.0'
upgrading 'xfce4-terminal-0.6.3' to 'xfce4-terminal-0.8.6'
upgrading 'linux-4.16-rc5' to 'linux-4.16-rc7'
these derivations will be built:
  /nix/store/n8j7i2lm2mmfp3zvbcxi829kl6qp9mz4-libxfce4util-4.13.1.drv
  /nix/store/4pa2pkb9l9na1r8fv5rdzbhb7bvqg0kr-xfconf-4.13.4.drv
  /nix/store/i9b034vpb5fkd7ncsippwdw7hm1xi9za-linux-4.16-rc7.tar.gz.drv
  /nix/store/bbhkzyhppflsg3ay95yx83kg11swwxfs-linux-config-4.16-rc7.drv
  /nix/store/gw7s0r2dhbfgpggiy3681j4famns0l5p-linux-4.16-rc7.drv
  /nix/store/igj47g6pvydlyp6vmrc20vxm6nz33a0d-libxfce4ui-4.13.4.drv
  /nix/store/m9xh14d21wv22gz357wgkqf7xaf2zwjb-xfce4-terminal-0.8.6.drv
these paths will be fetched (3.75 MiB download, 25.00 MiB unpacked):
  /nix/store/3wkm9bvpczwlh8myvypw75rkwj3yzw6n-tracker-miners-2.0.4
  /nix/store/lr2cs2gk0f5lap7vs87xi7bww146wjps-nautilus-3.28.0.1
  /nix/store/n37rch5z89aqnamyplhwpjsb8qvvd38g-gnome-terminal-3.28.0
copying path '/nix/store/3wkm9bvpczwlh8myvypw75rkwj3yzw6n-tracker-miners-2.0.4' from 'https://cache.nixos.org'...
building '/nix/store/i9b034vpb5fkd7ncsippwdw7hm1xi9za-linux-4.16-rc7.tar.gz.drv'...
building '/nix/store/n8j7i2lm2mmfp3zvbcxi829kl6qp9mz4-libxfce4util-4.13.1.drv'...
unpacking sources
unpacking source archive /nix/store/n6d5wziwsxl6lkgdqilfx0z0zdgj86s6-libxfce4util
source root is libxfce4util
patching sources

trying https://git.kernel.org/torvalds/t/linux-4.16-rc7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
xdtAutogenPhase
xdt-autogen: You must have "autoconf" installed on your system.
             Download the appropriate package for your distribution,
             or get the source tarball at ftp://ftp.gnu.org/pub/gnu/.
builder for '/nix/store/n8j7i2lm2mmfp3zvbcxi829kl6qp9mz4-libxfce4util-4.13.1.drv' failed with exit code 1
cannot build derivation '/nix/store/igj47g6pvydlyp6vmrc20vxm6nz33a0d-libxfce4ui-4.13.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m9xh14d21wv22gz357wgkqf7xaf2zwjb-xfce4-terminal-0.8.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gw7s0r2dhbfgpggiy3681j4famns0l5p-linux-4.16-rc7.drv', '/nix/store/m9xh14d21wv22gz357wgkqf7xaf2zwjb-xfce4-terminal-0.8.6.drv', '/nix/store/wmmhd8pky79fsl8hblcdaz7jr4n0hwh0-gnome-terminal-3.28.0.drv' failed

`

More for your eyes 

`
[root@NixOS:~]# whereis autoconf
autoconf: /nix/store/13f9xvhkycs2flmq0bnd9hwicygvyw82-user-environment/bin/autoconf

`

**Comment by edolstra** [comment]
This repository is for the NixOS homepage. Issues with Nix or Nixpkgs should be created in the corresponding repositories, please.
