### ISSUE TITLE
packages.html doesn't support "maintainers" object

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixos-homepage#208]
Newest Nixpkgs uses an object for "maintainers" so that needs to be handled.

See https://nixos.org/nixos/packages.html and this line:

```
Maintainers: [object Object]
```

**Comment by ariutta** [comment]
Is [this the line](https://github.com/NixOS/nixos-homepage/blob/master/nixos/packages.tt#L255) that needs to be changed?

**Comment by matthewbauer** [comment]
Also looks like platforms has the same problem now.

**Comment by samueldr** [comment]
@ariutta yes it is.

As for platforms, unless I'm mistaken, it's not yet an issue (with 18.03). It will also be much more complicated to render palatable platforms. That one can now be tracked in #213
