### ISSUE TITLE
Presentations/slides available to show of nixos

### ISSUE THREAD

**Issue by teto** [NixOS/nixos-homepage#217]
I would like to present nixos in a short high level overview (5mn). I am not willing to create one from scratch for various reasons (mostly time). I've seen several times talks about presentations on IRC and I wonder if some were freely available and of the opportunity to showcase/link some on the website ?

**Comment by teto** [comment]
https://arianvp.github.io/nixtalk/slides/slides.html
https://www.slideshare.net/sandervanderburg
There is also a list of presentations at https://discourse.nixos.org/t/intro-talks-slides-on-nix/353/8

**Comment by flyfloh** [comment]
Looks like these are all quite old by now. I don't think we have the resources to look for any current presentations and keep the list up to date.
