### ISSUE TITLE
cache.nixos.org should have an index.html

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-homepage#223]
When people unfamiliar with the specifics of the NixOS cache perceive the cache to be broken, they visit https://cache.nixos.org and see a browser error page, forget to notice that it is a 404 and conclude, indeed, the cache is broken!

I propose we create an index.html on the cache that says "Yep, we're up!"

**Comment by LnL7** [comment]
That looks great.

**Comment by grahamc** [comment]
We should have it tracked in _A_ repository. Perhaps https://github.com/nixos/nixos-org-configurations with a task on the nixos.org box like https://github.com/NixOS/nixos-org-configurations/blob/master/nixos-org/hydra-mirror.nix#L17 to upload it?

I made a minor set of changes to it here: https://gist.github.com/grahamc/fde7340096c3aac050d7a5a097ef4248/revisions what do you think?

**Comment by samueldr** [comment]
Definitely better if it's tracked, and changes look good.

Oh, right nixos-org-configurations looks like the right place to track that!

**Comment by samueldr** [comment]
I looked a bit at all that, I have no experience with S3. Here's where I'm at:

##### Wrong bucket

Looks like the channel releases are in another bucket than the cache:

 * cache.nixos.org → d3m36hgdyp4koz[.cloudfront.net]
 * [nix-releases.s3-eu-west-1.amazonaws.com] → d3g5gsiof5omrk[.cloudfront.net]

Which make me think that (ab)using the existing configuration will not work for putting the index page there.

##### Wrong [thing]?

I don't know what cache.nixos.org is. It responds with a 404, which is different from the nix-releases bucket, which responds with a listing.

Still, I'm assuming it's a bucket, only that it's configured to reply differently at the root.

##### Index configuration

As per [pretty-s3-index-html](https://github.com/nolanlawson/pretty-s3-index-html) project makes me think, the index.html file wouldn't be used by default. If it was the same *thing* as nix-releases is, it would reply with a list. Unless it was configured differently (RoutingRules?).

That is, unless something like [Specifying a Default Root Object](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DefaultRootObject.html) can be used.

* * *

With this said, I'll defer to the knowledge of those knowing where I should contribute my change. But yes, I think it would be better to have it tracked, and even better if at all possible to have it managed in a more automated way.

**Comment by samueldr** [comment]
Other than putting the file in source control *somewhere*, was there something left to do here? I think not. This probably can be closed.

**Comment by davidak** [comment]
The page is visible. So initial issue is fixed.

https://cache.nixos.org/

Anything left to do?
