### ISSUE TITLE
Remove confusing directory listing

### ISSUE THREAD

**Issue by roberth** [NixOS/nixos-homepage#227]
https://nixos.org/releases/nixpkgs/ lists a bunch of old releases. I'd assume the directory listing can be disabled. The page should redirect or link to https://nixos.org/nixpkgs/download.html

**Comment by davidak** [comment]
@edolstra can you do that or is there someone else who also has acess to the system?

**Comment by edolstra** [comment]
Thanks, I've removed read permission on the directory.
