### ISSUE TITLE
feature request: pass search terms trough url

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixos-homepage#23]
For the search packages, and search options pages, it would be great if search terms could be passed trough the url, like most search engines.
That way they could be used in scripts and as a FF search engine.
I use a bunch of scripts trough dmenu, that let me search the web and do other nifty things with the primary selection, for example:
https://github.com/StudioDotfiles/DotRepo/blob/master/i3/scripts/actions/google

**Comment by davidak** [comment]
that would also be helpful to send links to a package description.

**Comment by magnetophon** [comment]
Great!

Thanks for the heads up @davidak !
