### ISSUE TITLE
nixos.org out of sync

### ISSUE THREAD

**Issue by govertb** [NixOS/nixos-homepage#236]
Hi, I discovered that the information on nixos.org (e.g. https://nixos.org/nix/manual/#sec-prerequisites-source) is not in sync with the GitHub repository (e.g. https://github.com/NixOS/nix/blob/master/doc/manual/installation/prerequisites-source.xml). For the  documentation I referred to, the GitHub sources mention `xz` as a dependency, whilst the website does not. Hope this is useful information! Best.

**Comment by vcunat** [comment]
That commit a405d25fa isn't reachable from any tag yet.  Off the top of my head, I don't know what version the online manual updates to...

**Comment by govertb** [comment]
Ah, ok. If the manual updates to the latest release tag, it makes sense. The 2.0.4 source-release (which I downloaded from from nixos.org) has `xz` as a prerequisite. Yet, the docs on GH didn't reflect this yet in [the corresponding tag](https://github.com/NixOS/nix/releases/tag/2.0.4).  Thanks!

**Comment by samueldr** [comment]
Hi!

The nixos.org manuals are all for the current-stable version of Nix, Nixpkgs and NixOS, respectively.

Once 2.1 releases (hopefully soon™) this section should show up; [it's part of the 2.1-maintenance branch](https://github.com/NixOS/nix/blob/2.1-maintenance/doc/manual/installation/prerequisites-source.xml).

I opened #237 to be a bit more on-topic.

* * *

Oops, too slow to reply!
