### ISSUE TITLE
Keep versioned manuals

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#237]
This is a multi-fold issue, I'm opening this quickly, this isn't as detailed as I'd like.

 * There are no `unstable` manuals available online.
 * Once a stable release updates, the manual links *may* end up being dead-ends.
 * There is no way to reference an older manual online.

I know hydra builds the manual, and I think they're available somehow online, but I don't really know how to access them.

I'd like opinions and suggestions about whether we should and how we should approach this.

(I'll write my owns later.)

**Comment by vcunat** [comment]
Yes, at least for the currently maintained branches.

**Comment by edolstra** [comment]
The latest manual for Nix master is at https://hydra.nixos.org/job/nix/master/tarball/latest/download-by-type/doc/manual.
