### ISSUE TITLE
Review the performance of the packages page.

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#245]
* https://nixos.org/nixos/packages.html

The updated 18.09 page of packages takes 1.9 second to do the JS massaging, that's **not** considering the download!

![image](https://user-images.githubusercontent.com/132835/46769396-a5f34600-ccb9-11e8-89d2-7707c5f81c85.png)

Add an additional 2.1s for the network (30mbps internet) for me.

This is pretty bad for the UX considering the current implementation's search box will be:

 * Focused on load
 * Emptied when the network event finished and scripting happened (4s later)

And for the record, this is not on a budget CPU:

 * Intel(R) Xeon(R) CPU E5-1660 0 @ 3.30GHz

If people want I can try on a haswell-era celeron and on a cherry trail atom.

**Comment by garbas** [comment]
with move to netlify this has become even bigger problem.
