### ISSUE TITLE
Better landing page (nixcon followup)

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#248]
Writing up some of the points we brought up in an informal group talk this morning at nixcon.

The couple needs I remember from this:

 * Landing page for `nixos.org/` should advertise Nix as well as NixOS
 * Landing page would need good "stories" to hook in users
 * Landing page would need an easy and well marked road to the nix installer (so users can try easily)
 * The manual**s** should be easier to find

* * *

Additional note for the manuals: when on a non-specific subsection of the website, it would be helpful to link to a Manual**s** page, which has the multiple (three) manuals linked, with an introductory paragraph explaining why one would read that manual.

* * *

So this probably means we would have four menu structures, one for non-specific pages (e.g. community, support, manuals), and then specific menus when on pages about one of the sub-projects. This is something that needs exploring: would the non-specific menu be shown anyways on the specific sub-websites? Not showing it might become confusing.

* * *

> *This is only a rough reminder of what we talked about rapidly with @garbas earlier today. I'm probably missing a bunch.*

**Comment by davidak** [comment]
>Landing page would need good "stories" to hook in users

I also thought about this. NixOS and Nix are great for different groups of people, so we should address them directly.

A good discussion with ideas is here: https://discourse.nixos.org/t/how-would-you-pitch-nix-os-if-you-had-5-minutes/3270/2?u=davidak

I would like to have very little, but precise text on the landing page together with symbols or images to visualize it. A new user should not be overwhelmed by the complexity of the ecosystem, but lead to master it step by step.

That starts with the claim "The Purely Functional Linux Distribution" and ends with multiple huge manuals that are not really accessible.

Maybe even a 5 minute video that explains why one should use NixOS / Nix.

**Comment by garbas** [comment]
This was now partially done with #425 and more updates are coming.
