### ISSUE TITLE
Versioned documentation for NixOS releases

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-homepage#25]
Since we're having half-year releases, we should start having an option to select what version should the docs be.

Currently: unstable, 14.12, 14.04, 13.10

**Comment by teto** [comment]
I miss a simple link towards master/unstable documentation too. I always am on unstable and sometimes want to contribute to the manual or check a feature. I look at the manual but forget it's not the updated version. I know it's accessible through hydra
https://hydra.nixos.org/build/79406630/download/1/nixpkgs/manual.html
 but a per-channel link would be much a better .

**Comment by garbas** [comment]
This is a duplicate #237 ... I chose to close this issue since the other issue has more information how to move ahead with it.
