### ISSUE TITLE
Security page is outdated

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixos-homepage#251]
This has been pointed out [here](https://discourse.nixos.org/t/security-page-on-nixos-org-is-outdated/1430).

The page should no longer link to the dead Google Group, but instead link to `#nixos-security` and [github security tag](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%221.severity%3A+security%22).

See also #174.

**Comment by ekalosak** [comment]
Created a PR fixing the dead links: https://github.com/NixOS/nixos-homepage/pull/252
