### ISSUE TITLE
Can reach https://nixos.org/ but not https://www.nixos.org/

### ISSUE THREAD

**Issue by rycee** [NixOS/nixos-homepage#264]
I'm pretty certain that https://www.nixos.org/ has worked before.

**Comment by vcunat** [comment]
:+1: this is on DNS level &ndash; the name doesn't exist.  When I spoof that name to have the same contents as nixos.org, the web seems to work OK again.

**Comment by edolstra** [comment]
Yeah, we got rid of it. It used to exist more or less by accident (because our registrar had a wildcard DNS entry for `*.nixos.org`).

**Comment by vcunat** [comment]
I wonder, is it worth not having it at all?  I still feel it's pretty common to use it &ndash; sometimes even have sites redirect to `www`-prefixed name as the canonical one.  I personally prefer to use unprefixed names, but I fear removal will kill many links and I can't see any significant benefit.

**Comment by rycee** [comment]
FWIW removing it broke a link on my heavily accessed site – it probably gets dozens of visitors per annum! In any case I changed the link over to use https://nixos.org so you can rest easily again.

As far as I'm concerned the issue can be closed but I agree with @vcunat that dropping www.nixos.org may break existing links which seems unfortunate.
