### ISSUE TITLE
Search NixOS Packages doesn't show all packages. 

### ISSUE THREAD

**Issue by Prithvirajbilla** [NixOS/nixos-homepage#268]
Searching for scalafix (https://nixos.org/nixos/packages.html#scalafix) results in no results.

But I could find scalafix inside nixpkgs repository (https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/scalafix/default.nix) 

This is little misleading.

**Comment by samueldr** [comment]
The package was added after the last (18.09) release:

 * https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/tools/scalafix/default.nix

The package listing currently only lists the (Free) software for the current stable release of NixOS.

#209 will address that (once updated and merged).
