### ISSUE TITLE
Package search loads slowly for users with bad internet.

### ISSUE THREAD

**Issue by TZubiri** [NixOS/nixos-homepage#279]
https://nixos.org/nixos/packages.html

The page initially prompts 'loading...' and never changes. You can write text in the search bar, but there is no button to send the form, hitting enter does nothing.

**Comment by TZubiri** [comment]
Dramatized the title for greater impact

**Comment by TZubiri** [comment]
Oops, it finished loading. That query took something like 4 minutes. 

- [ ] Reduce initial loading time. Perhaps there's a query that's lacking a LIMIT?

**Comment by samueldr** [comment]
The whole package set is being loaded from a statically compiled json (gzipped) blob. Though, it has been gaining weight over time. (2.81MB, unzipped to 36.99MB)

The current infra for the website has no server-side code; under those limitations this is the best that can be done.

Though, thanks for the reporting, this is something that might need to be re-thought considering the ever increasing amount of data. This will hit computers with less RAM or slower CPUs even worse, and will be compounded by slower internet. Not exactly the best for global accessibility of the contents.

**Comment by TZubiri** [comment]
https://nixos.org/nixpkgs/packages.json.gz

>   Perhaps there's a query that's lacking a LIMIT?

Oops, looks like there's a whole query missing!! The website currently serves a whole json with 45thousand packages to the user. That's a 37MB download. I can see how this might have slipped through testing if the developers and dev machines have good internet connections this might have been completed in a couple of seconds.

**Comment by samueldr** [comment]
The column to look for, and will only show when the request isn't cached, is "Transferred".

> ![image](https://user-images.githubusercontent.com/132835/57730288-23bf6b80-7666-11e9-9b8d-38e91c657f72.png)

**Comment by TZubiri** [comment]
Ah I see, that's some very effective gzipping, at 3MB this will only affect users with a slow throughput like me then.

It looks like the fix might be quite easy. I'll just link to the relevant code in case anyone wants to develop a lighter package explorer (including myself if I find the time for it.)
https://github.com/NixOS/nixos-homepage/blob/master/nixos/packages.tt

**Comment by TZubiri** [comment]
Here is a small temporary fix that will mostly placate the issue by better communicating the status of the loading to the user.

- Initially load the top 25 packages (by popularity preferably, but alphabetically is ok)
- Start downloading the zipped json immediately.
- Prompt the loading screen only when the user enters a search query or expands one of the packages.

**Comment by edolstra** [comment]
May be worth reconsidering https://github.com/NixOS/nixos-homepage/pull/201 (which substantially increased the size of `packages.json`). Having said that, the current size (2.8 MiB compressed) doesn't seem excessive given the average size of web pages in 2019 (which is apparently ~3 MiB).

**Comment by samueldr** [comment]
There are things that would improve the situation somewhat:

 * A "loading" state, so users know something is going on
 * Disabling the inputs during the "loading" state.
 * Showing the "downloading" differently than the "working" state. In a situation where both the internet is slower, and the computer is slower, it would at least show some progress.

That is, as long as the goal is to keep this entirely client-side, with static generation.

**Comment by Abdillah** [comment]
Can we store the JSON file on the browser's cache? Then we just query whether the JSON has changed or not (through commit hash).
