### ISSUE TITLE
Package search by "starts with"

### ISSUE THREAD

**Issue by smithtim** [NixOS/nixos-homepage#280]
It would be nice to have a "starts with" option for the package search.  Currently, if I search for "nim", I have to page through 150 results to get to the one I want, `nim-0.19.4`.

**Comment by edolstra** [comment]
Use a regular expression:
```
# nix search '^nim'
```

**Comment by smithtim** [comment]
Thank you for the suggestion, but this issue is about the package search at:

https://nixos.org/nixos/packages.html

Typing `^nim` there gives no results.

**Comment by vcunat** [comment]
One can currently at least approximate "ends with" by using "nim-" in this particular case, though it's still not ideal.

**Comment by garbas** [comment]
regex is supported by package explorer ... eg. https://nixos.org/nixos/packages.html?channel=nixos-19.09&query=%5Enim
