### ISSUE TITLE
Update State of NixOS

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#285]
The [About](https://nixos.org/nixos/about.html) page is pretty good. Only the Status section is heavily outdated!

We should update it.

So let's collect facts about the current status and write them up.

This is part of https://github.com/NixOS/nixos-homepage/issues/230, but very important. So we should work on this smaller task individually to get it done ASAP.

**Comment by JohnAZoidberg** [comment]
>  Since NixOS is a relatively young Linux distribution, you may find that certain things that you need are missing
Absolutely not true :D NixOS isn't young and I'm always surprised how many packages there are.
We can instead say that if a package isn't there it's very easy to add them and get them added to the package manager. With Debian, Arch etc. it seems to me that only a few elite people can contribute - I love how open we are.

**Comment by davidak** [comment]
>NixOS isn't young

compared to debian or RHEL it is young. but the project exists for more than 10 years and is used by many people, even professionally. i would like to have an estimate of the number of users. a survey could provide that https://discourse.nixos.org/t/idea-yearly-nixos-community-survey/2814

a list of companies that use NixOS would fit here also and might state that this is not just for fun, but a serious project that solves real problems.

>I'm always surprised how many packages there are.

Only AUR has more packages. And by the number of up to date packages, we are the best distribution! That's very amazing when you think about it since we have not so many contributors as the big distros (citation needed). It underpins the fact that packaging for Nix is simple and reliable. And we have a lot of automation (Hydra: build and test, OfBorg).

https://repology.org/repositories/statistics/newest

I think the "Repository size/freshness map" would fit perfectly here and shows very impressively that we are very good with packaging.

https://repology.org/repositories/graphs

But at the same time, many common packages are missing that are part of most popular distros. That fact is also important in a status report.

https://github.com/NixOS/nixpkgs/issues/60005

>With Debian, Arch etc. it seems to me that only a few elite people can contribute - I love how open we are.

From my experience as a sysadmin, packaging software for Nix is easier than creating deb packages. And it's very streight forward to get them included in nixpkgs. This is a great point!

**Comment by davidak** [comment]
>So, for stateful services, NixOS isn’t fully declarative, but nevertheless, it is highly reproducible.

https://discourse.nixos.org/t/general-questions-for-a-popularization-article-in-france/3358/25?u=davidak

**Comment by worldofpeace** [comment]
How about removing the status section completely?
I don't really think it's needed, it will eventually get out of date and the information there could be split up into better sections. Like software selection, services, DE's, corporations that support it, supported platforms etc. Not once is it mentioned what format NixOS is released in, which is a common linux user curiosity.

Pretty much don't need to go out of our way to assert our "status", that's only needed for projects on the downturn. You only have need to open your eyes to realize where NixOS is headed (in my opinion).

**Comment by worldofpeace** [comment]
Addendum: Instead of communicating the "status" with a bunch of brief anecdotes, just directing people to where they can discover relevant info about NixOS is important. Things like software selection and services is easily searchable with the package and option search. DE's and WM have predictably name-spaced options we could link too. Exposing content in the NixOS manual is important as well.

**Comment by flyfloh** [comment]
The About page has been replaced by the Explore page at some point and there is no more Status section. I guess we can close this for now.
