### ISSUE TITLE
NixOS package search page shows misleading date

### ISSUE THREAD

**Issue by nikuda** [NixOS/nixos-homepage#290]
When you navigate to https://nixos.org/nixos/packages.html directly the text on the bottom of the page, "Last changed on 2018-11-04", could be seen as referring to the package index but it's just a general html doc edit time stamp. 

You might want to update that page every time the package index is updated. Or alternatively have a more visible package index change date somewhere else on the page.

**Comment by davidak** [comment]
This would be fixed by https://github.com/NixOS/nixos-homepage/pull/209 since it shows the channel and git commit.

![Screenshot from 2019-08-03 21-24-08](https://user-images.githubusercontent.com/91113/62416109-434aac80-b635-11e9-82c6-7d9c8220aa67.png)

**Comment by davidak** [comment]
It shows now the exact commit.

![Screenshot from 2019-09-02 17-33-04](https://user-images.githubusercontent.com/91113/64124631-cd5a7200-cda7-11e9-83fb-75ba8af1d275.png)

@nikuda do you think it's clear now or is the "Last changed on 2018-04-08" in the footer still confusing? It's probably not trivial to update the ""Last changed" date every time the package index is updated.
