### ISSUE TITLE
nixos-generate-config generates duplicate fileSystems entries and swapDevices

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixos-homepage#292]
I've set up the following in my configuration.nix:

```
  fileSystems = {
    "/".device = "/dev/mapper/vg-root";
    "/home".device = "/dev/mapper/vg-home";
  };
  swapDevices = [ { device = "/dev/mapper/vg-swap"; } ];
```

`sudo nixos-generate-config` creates duplicate entries for these in /etc/nixos/hardware-configuration.nix:

```
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f7ecf35-bebe-4655-8de0-4f0648b8bb35";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a2a744ac-923e-4217-b77e-e6c8e39e0f28";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/50a66e47-cde9-4aa5-a3f9-9500b5aa1d8f"; }
    ];
```

This means I have to go against the advice in /etc/nixos/hardware-configuration.nix to make my modifications in /etc/nixos/configuration.nix.

**Comment by edolstra** [comment]
You should probably open an issue in the `nixpkgs` repo rather than in `nixos-homepage`.
