### ISSUE TITLE
Maintenance site

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#294]
Today https://hydra.nixos.org/ was DOWN. ERR_CONNECTION_TIMED_OUT

That is not very user friendly.

It would be better to have a simple maintenance page. Technically it would probably be simple since a webserver is used as reverse-proxy in front of hydra (or could be used this way). Then the webserver should just show this simple page instead of proxy for hydra.

Is nixos.org website on a different server than hydra? Then we can use the webserver and proxy hydra and show the maintenance page when it is down.

So

1. do we want this?
1. is it technically possible how i described it?
1. do someone want to design a simple HTML page? maybe with NixOS logo and one sentence...

Here are some information on the topic and examples: https://www.atlassian.com/blog/statuspage/maintenance-page-examples

Here is a simple template: https://gist.github.com/pitch-gist/2999707

It's probably also good to send 503 HTTP Code.

Like in this example:
```
<?php
header("HTTP/1.1 503 Service Temporarily Unavailable");
header("Status: 503 Service Temporarily Unavailable");
header("Retry-After: 3600");
?>
```

**Comment by grahamc** [comment]
Today's maintenance took the entire machine offline. This machine is in Hetzner, which doesn't have handy load balancing / fronting services. The IP of hydra is the IP in DNS, so there was no good place to put a "down" message.

It could be possible to use nixos.org's webserver as a reverse proxy, however it is also in the plans to move nixos.org to being a statically generated and uploaded-to-s3 website. I think we would not be inclined to front hydra with this webserver for that reason.

**Comment by edolstra** [comment]
Note that we already have a 503 page (https://hydra.nixos.org/apache-errors/503.html). But as Graham said, it doesn't help if the entire machine is down. Having a separate proxy machine is probably overkill for an internal service of the NixOS project (i.e. it doesn't affect Nix/NixOS users directly if it's down).

**Comment by davidak** [comment]
>Having a separate proxy machine is probably overkill for an internal service of the NixOS project (i.e. it doesn't affect Nix/NixOS users directly if it's down).

That's a point.
