### ISSUE TITLE
Options on the website are out of date

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixos-homepage#296]
I hope this is the right repo to open the issue :-)

In 19.03 the option `hardware.acpilight` was introduced (among others): I can find it through `nixos-option hardware.acpilight.enable` on the command line but is seem to not be available through `https://nixos.org/nixos/options.html`.

**Comment by samueldr** [comment]
Oooh, you found something particular.

I can vouch that the options list is not out of date. I can also say that there is an acpilight module for NixOS. So what gives?

The acpilight module [was not added to `<nixos/modules/module-list.nix>`](https://github.com/NixOS/nixpkgs/commit/4cae259fceeb2728925ed01eab76302d1f68a0e2#diff-57d6021a3228873abfb61148d181984d) when it was introduced. 

What surprises me is that you seem to imply that `nixos-option hardware.acpilight.enable` works, but it shouldn't, at least not without importing the acpilight.nix module in your configuration.

```
 $ nixos-option hardware.acpilight.enable
error: while evaluating 'walkOptions' at (string):11:29, called from (string):30:16:
error: undefined variable 'config' at (string):10:11
An error occurred while looking for attribute names. Are you sure that 'hardware.acpilight.enable' exists?
```

The options [was later added](https://github.com/NixOS/nixpkgs/commit/89845931e4caa74f0906bb45b06624983e77e485) to the list, but [is not part of the release-19.03 branch](https://github.com/NixOS/nixpkgs/blob/release-19.03/nixos/modules/module-list.nix) as of today.

**Comment by samueldr** [comment]
[Just backported the fix](https://github.com/NixOS/nixpkgs/compare/81375643d1c1...878531fbdbbe).

**Comment by samueldr** [comment]
This issue can be closed, I think.

 * https://nixos.org/nixos/options.html#acpilight

**Comment by zarelit** [comment]
Yes it was a nixpkgs issue, not a website one. What is weird to me is that the option was discoverable by `nixos-option`, that means that the website and the application use two different options discovery methods... but it's absolutely OT for this issue.
Thank you for the fix @samueldr
