### ISSUE TITLE
Site navigation doesn't work on phone 

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-homepage#3]
On my phone I get the mobile view, and for nixos and nix that is simply two times the logo, no text. 

Furthermore, the projects drop-down shows but doesn't allow clicking on a project.

**Comment by samueldr** [comment]
*This can be closed, the navigation has changed. The issue can be reproduced [on a 2014 snapshot](https://web.archive.org/web/20140610021828/http://nixos.org/) with a recent desktop chrome browser, and no equivalent issue could be found with either a mobile or desktop chrome browser.*

**Comment by garbas** [comment]
It looks this was already fixed.
