### ISSUE TITLE
schwag link

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixos-homepage#309]
I run merchandise for nixos and was thinking it might make sense to link to it from the community section. https://www.redbubble.com/people/mogorman/shop

**Comment by samueldr** [comment]
This came up during the meeting, so here's the link to the semi-regular report.

 * https://discourse.nixos.org/t/nixos-merchandise-report/303

**Comment by davidak** [comment]
@mogorman to what countries do they ship? maybe someone has to create a shop in regions not reached with it. also, can you create a "NixOS" collection to show just NixOS related motives? (Trimps has cost me a couple of hours)

when we link to it, i would like to have it a little more professional. like having t-shirts with all motives. i wouldn't buy the other stuff. The logo on the travel mug looks very distorted and who needs a NixOS Shower Curtain, even for a specific release? i don't think that makes sense

I wear my nixos shirt i got from NixCon very proudly. We might want to offer also the normal NixOS logo but that make the limited NixCon shirt less special. Any opinions on that?

**Comment by mogorman** [comment]
so you are correct no one has bought the shower curtain.... yet!

I don't know how far around the world rebubble ships but I get orders from all over europe and usa currently without a problem.

I don't mind removing the non-nixos items from the shop they are just tiny things for myself mostly, but I do agree better to have it united to be just nixos related.

Im curious what other people think, id hate to limit the selection of items to deprive someone of something. Like I can't imagine wanting a throw pillow, iphone case, and even that tall mug has been bought before.

At end of day happy to do whatever the project wants.

**Comment by samueldr** [comment]
We may want to make appropriate variants for the different products.

**Comment by garbas** [comment]
This was now done as part of Donate page PR #399
