### ISSUE TITLE
NixOS manual should have a single page variant.

### ISSUE THREAD

**Issue by nbp** [NixOS/nixos-homepage#31]
Splitting the documentation is nice, because we have all these source links, but this breaks the browser search.  We should enable both a single HTML page and the multi-page documentation as well.

Having a website search box is not an option, as this implies spending extra time loading even more pages which might not have the result/context that might interest me.

**Comment by manpages** [comment]
:+1:

**Comment by jbirch** [comment]
https://nixos.org/releases/nix/nix-1.9/manual.pdf does exist, but this isn't HTML as you request.

**Comment by catern** [comment]
This should be closed, a single-page variant exists now: https://nixos.org/nixos/manual/index.html
