### ISSUE TITLE
Offline-Capable versions of packages, options and manual

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixos-homepage#315]
This is a wishlist/idea of how the NixOS website could be improved by making it more like a PWA. 
Currently it is necessary to be online to view the package list, options and manual from nixos.org. 
Also, the usability of the package list and manual could be improved by changing them to load only the parts that are viewed (either from the server or from offline storage) and using an index to make them searchable. 

For the implementation of this I would use service workers and IndexedDB for offline storage and indexing. I have made a tech-demo of the packages page, which I am constantly improving, next up are full-text search and faster initial loading times: https://nixos.pbb.lc/packages/ (source here: https://git.pbb.lc/petabyteboy/nixos-package-list)

On caveat of all possibilities to make this possible I have thought about until now is that it will take up a bit of storage on the user's computer when made available offline, so this should probably only happen after the user has clicked a button. Fetching only the needed parts from the server would still improve performance for users who haven't made the content available offline.

While I'm working on my implementation of this, I'm open for suggestions and I will update this issue when I have made significant changes.

Related: #110 #245

**Comment by samueldr** [comment]
Note that there is currently no interest for a server-side component for the site. Though, I'm not saying it's never going to happen, but it's something required to know. This is why though I reworked the package search, it was left to be handled entirely client-side.

**Comment by petabyteboy** [comment]
> Note that there is currently no interest for a server-side component for the site. Though, I'm not saying it's never going to happen, but it's something required to know. This is why though I reworked the package search, it was left to be handled entirely client-side.

Thanks for noting, most of what I thought of can be done offline, but takes up a bit of space on the user's computer, and an online implementation could be useful to serve answers before everything is loaded.

**Comment by samueldr** [comment]
There might exist, also, a clever scheme that could be used to make an index part faster (and smaller) to load, then load the rest of the data asynchronously as needed (or always, but after loading the index). Though, I don't know of an existing solution for that.

**Comment by petabyteboy** [comment]
There are solutions for indexing a data set in such a way, for example elasticlunr, but when I tried it the search index was bigger than the actual data set. Saving the search index to several files and only loading the parts of the index required for searching might also be possible, but I think that would kind of be overengineering.

**Comment by garbas** [comment]
I think this idea is too much of a stretch, especially with all the other things that we should fix first. but please if somebody wants to work on this, please reopen this ticket and lets discuss how we can get this working.
