### ISSUE TITLE
The wiki logo is squashed.

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixos-homepage#32]
The NixOS logo on the wiki is not in scale (is vertically squashed). Its resolution is 135x135, but a regular hexagon would have ratio of about 0.87:1. The picture in question is in this repository (logo/nix-wiki.png).

**Comment by samueldr** [comment]
*This issue can be closed; the logo on the current wiki is fine, and the wiki isn't managed here anymore.*

**Comment by davidak** [comment]
@edolstra the wiki don't exists anymore, this issue can be closed.
