### ISSUE TITLE
describe how to know that reboot is necessary after rebuild-switch-upgrade

### ISSUE THREAD

**Issue by agreif** [NixOS/nixos-homepage#320]
I regularily do a 'nixos-rebuild switch --upgrade' but never know when to reboot.
It would help a lot if the docs would describe how a user can see if a reboot is necessary.
A good place would be 'Chapter 4. Upgrading NixOS'

**Comment by edolstra** [comment]
Currently it tells you to reboot if there is an incompatible change to the init system. It would be nice if it could detect other incompatible changes (e.g. needing kernel modules that are not loadable in the current kernel).

NixOps has an `--allow-reboot` flag to automatically reboot the remote system when needed.

**Comment by edolstra** [comment]
BTW, this issue should be in the nixpkgs repo, can you reopen it there?

**Comment by sigmonsays** [comment]
Why is this just closed without any comment?

what's the solution here?
