### ISSUE TITLE
GPG key on GitHub

### ISSUE THREAD

**Issue by ppadamcz** [NixOS/nixos-homepage#321]
In order to verify the script I wanted to download the GPG key from GitHub: https://github.com/edolstra.gpg. The result I get is:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded 8170B4726D7198DE


=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by grahamc** [comment]
Did you mean to fetch it from https://github.com/NixOS/nixos-homepage/blob/master/edolstra.gpg or https://nixos.org/edolstra.gpg?

**Comment by ppadamcz** [comment]
Yes, that works for me, just wanted to point maybe it is something worth fixing. I was writing to @edolstra an e-mail.

**Comment by grahamc** [comment]
Is there somewhere on the homepage or manuals that refers to https://github.com/edolstra.gpg? I don't see one. If there is, we should definitely fix that -- separately I'll ping Eelco about possibly uploading his GPG key to github :)

**Comment by ppadamcz** [comment]
No, there isn't any reference on the homepage/manuals.

**Comment by garbas** [comment]
I believe this was fixed. please reopen if i'm wrong.
