### ISSUE TITLE
planet.nixos.org

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-homepage#336]
After moving to Netlify, we will shut down the EC2 instance that currently serves nixos.org but also planet.nixos.org. So we need to figure out what to do with it (assuming we want to keep it). Maybe the contents can be generated/committed as part of the update.sh script in nixos-homepage and served by Netlify?

**Comment by garbas** [comment]
:+1: we might even consider splitting this away from the website.

**Comment by craigem** [comment]
I'm one vote for keeping it as I find it quite useful.

I note it's down now and am assuming this is why :-)

**Comment by garbas** [comment]
Planet.nixos.org is back
