### ISSUE TITLE
Make Netlify actions less spammy

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-homepage#337]
Currently we get a lot of comments from Netlify build/deploy actions, e.g. https://github.com/NixOS/nixos-homepage/commit/576a38d01758a47885d553328e401414c9b4d5bf#commitcomment-37784357

Maybe this could just update the PR status or something, rather than create a separate comment.

**Comment by garbas** [comment]
this was fixed by splitting github actions in two (#335)
