### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-homepage#341]
Copied from #326:

One remaining issue: currently nixos.org points to Netlify using an A record because you can't have CNAMEs on apex records. So IPv6 doesn't work and load balancing is probably also affected. Solutions: 1) Switch from nixos.org to www.nixos.org (https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/); or 2) Use an ALIAS record on the apex, however united-domains doesn't support this so we'll have to switch to another DNS. We already have a terraform config for route53 but switching to route53 breaks the email forwarding provided by united-domains. So probably we should find some email forwarding service.

**Comment by vcunat** [comment]
1\) sounds good to me, as I'm not overly attached to what appears in the address bar.  I assume they normally do provide a simple IPv6-capable http redirector from nixos.org to www.nixos.org &ndash; I don't expect that part would need to be very performant (load-balanced etc.).

_Better HTTPS+DNS standards for this [are being worked on](https://mikebishop.github.io/dns-alt-svc/draft-ietf-dnsop-svcb-httpssvc.html), but that will surely take years to deploy._

**Comment by edolstra** [comment]
Regarding 2) - switching to route53 will not help since route53 doesn't support ALIAS records except to point to other AWS resources. (From their FAQ: "Amazon Route 53 also offers alias records, which are an Amazon Route 53-specific extension to DNS. You can create alias records to route traffic to selected AWS resources, including Amazon Elastic Load Balancing load balancers, Amazon CloudFront distributions, AWS Elastic Beanstalk environments, API Gateways, VPC interface endpoints, and Amazon S3 buckets that are configured as websites.")

**Comment by edolstra** [comment]
We could also switch to Netlify's DNS service...

**Comment by zimbatm** [comment]
We could also use DNSMadeEasy which [costs $59.-/year](https://dnsmadeeasy.com/pricing/#business) which is a super reasonable pricing. They support ALIAS records (they call it ANAME). One advantage is that they have [terraform support](https://www.terraform.io/docs/providers/dme/index.html) for declaring the DNS entries. I have used them in the past and was super happy.

**Comment by edolstra** [comment]
We're now using Netlify's DNS server so IPv6 now works fine.
