### ISSUE TITLE
"200" redirects are handled as 302

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#346]
From #344.

> 200: "OK". Redirects with this status code will change the server response without changing the URL in the browser address bar. This is used for rewrites and proxying.

 * https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes

The docs [*are*](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file) linking to that list of statuses for `[[redirects]]`.

~~I wonder if there is an issue with Netlify and 200s that I don't know about.~~

Thinking about it now, I believe it's simply Hydra's 302 being proxied, and followed. A solution for this issue, if it is an issue, would be to provide "permalink" URLs out of Hydra for such resources. Those URLs would not use HTTP redirection, but instead serve the content directly.

Keeping this open for discussion about the issue.

**Comment by garbas** [comment]
related PR https://github.com/NixOS/nixos-homepage/pull/345

**Comment by samueldr** [comment]
No, #345 is not really related.

This is about serving the document proxied under `https://nixos.org/.../manual` URL, but the contents coming from Hydra. Rather than actual redirection.
