### ISSUE TITLE
Package listing is extremely slow to load initially

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#353]
Some users reported the package listing being slower. It felt slower to me at the initial load. This is why I started investigating.

Not the only report, but the one I started actually looking into it:

 * https://logs.nix.samueldr.com/nixos-dev/2020-03-16#1584392813-1584393611;

* * *

## Facts

Netlify *does* compress the data when the client requests for it.

![image](https://user-images.githubusercontent.com/132835/76800747-af37ea80-67aa-11ea-9d2d-b86255af6136.png)

## Observations

Sometimes, responses will keep being quick for an undetermined amount of time, with cache disabled.

Responses may take multiple seconds (untimed) to actually be received, but Firefox says it loaded under 200ms. (EDIT: this may be caused by the data being sent without a size header, "streamed"... curl reports it being at 100% all the duration of the download.)

**Comment by samueldr** [comment]
~ $ curl -vv -o /dev/null 'https://nixos.org/nixpkgs/packages-nixos-19.09.json' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: Trailers'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.248.50.87:443...
* TCP_NODELAY set
* Connected to nixos.org (104.248.50.87) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2564 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nixos.org
*  start date: Mar 11 09:38:22 2020 GMT
*  expire date: Jun  9 09:38:22 2020 GMT
*  subjectAltName: host "nixos.org" matched cert's "nixos.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x1448070)
} [5 bytes data]
> GET /nixpkgs/packages-nixos-19.09.json HTTP/2
> Host: nixos.org
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache
> TE: Trailers
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [281 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 150)!
} [5 bytes data]
< HTTP/2 200 
< accept-ranges: bytes
< cache-control: public, max-age=0, must-revalidate
< content-type: application/json
< date: Mon, 16 Mar 2020 21:33:31 GMT
< etag: "e8a03eb3b38e4387381756541fc7a6db-ssl-df"
< strict-transport-security: max-age=31536000
< content-encoding: gzip
< age: 0
< server: Netlify
< vary: Accept-Encoding
< x-nf-request-id: 3389443b-0914-42b7-b4b2-9086781ddcd2-9231629
< 
{ [5 bytes data]
100 3904k    0 3904k    0     0   139k      0 --:--:--  0:00:27 --:--:--  188k
* Connection #0 to host nixos.org left intact

**Comment by tilpner** [comment]
```
curl 'https://nixos.org/nixpkgs/packages-nixpkgs-unstable.json' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: Trailers' -i > foo.http
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4473k    0 4473k    0     0  38152      0 --:--:--  0:02:00 --:--:-- 66341
```
It's unreliable, I got 10 fast curls, and then a slow one. Perhaps Netlify is load-balancing, and this only happens with a subset of servers?

**Comment by samueldr** [comment]
This one was quick:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.81.212.192:443...
* TCP_NODELAY set
* Connected to nixos.org (192.81.212.192) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2564 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nixos.org
*  start date: Mar 11 09:38:22 2020 GMT
*  expire date: Jun  9 09:38:22 2020 GMT
*  subjectAltName: host "nixos.org" matched cert's "nixos.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0xbd5070)
} [5 bytes data]
> GET /nixpkgs/packages-nixos-19.09.json HTTP/2
> Host: nixos.org
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache
> TE: Trailers
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [281 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [281 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 150)!
} [5 bytes data]
< HTTP/2 200 
< accept-ranges: bytes
< cache-control: public, max-age=0, must-revalidate
< content-type: application/json
< date: Mon, 16 Mar 2020 21:28:00 GMT
< etag: "e8a03eb3b38e4387381756541fc7a6db-ssl-df"
< strict-transport-security: max-age=31536000
< content-encoding: gzip
< age: 674
< content-length: 3997884
< server: Netlify
< vary: Accept-Encoding
< x-nf-request-id: b6e1e424-0d64-4ac0-b4b7-e704ef3ff5c0-16121689
< 
{ [5 bytes data]
100 3904k  100 3904k    0     0  1776k      0  0:00:02  0:00:02 --:--:-- 1776k
* Connection #0 to host nixos.org left intact

```

**Comment by samueldr** [comment]
I had a slow request, made a concurrent one, both were slow and resolved at the same time. The second one started at the amount of bytes the first one was now at.

**Comment by samueldr** [comment]
This also happens on HTTP/1.1 forced with curl.

**Comment by chrissound** [comment]
Same here... 1.4minutes just to load the first css files.
![2020-03-22-12:39:22](https://user-images.githubusercontent.com/1499652/77249625-77adc000-6c3a-11ea-8e64-3231018b0a95.png)

**Comment by chrissound** [comment]
The issue does not seem to be present when opening it in a new incognito window (at least for chrome)... 

I wonder if it's due to an browser extension? Though the same occurs on firefox.

**Comment by samueldr** [comment]
With https://github.com/NixOS/nixos-channel-scripts/pull/35 merged, we'll soon be able to fix the issue where, though unverified, Netlify seems to sometimes slowly stream the packages and options json uncompressed to their edge, then compress it, which is slow.

The next step is to use the channels url/redirection as the data source.

**Comment by samueldr** [comment]
Fixed by:

 * https://github.com/NixOS/nixos-homepage/commit/c7f9f123276f111444b532a7c2fe3fc7411d29ff
 * https://github.com/NixOS/nixos-homepage/commit/ca7664c8ef2625d8e4bd95b2c3a616a4d1147876

The channel data is not served by Netlify anymore.

If people experience slowness still, it is likely another issue, and I ask they open a new issue with as much helpful data they can. It may be that an issue someone is having is specific to their regionality or setup.
