### ISSUE TITLE
Add status.nixos.org to the website

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#358]
From the forum:

>I think status.nixos.org 1 should get somewhere mentioned on nixos.org…

https://discourse.nixos.org/t/announcement-moving-nixos-org-to-netlify/6212/22?u=davidak

When something is broken in Nix/NixOS, users probably go to the website to see if they can get answers what's going on. We should add a link to status.nixos.org to answer that question. A "Status" link in a footer would be enough.

I think GitHub has great UX and design and they do it like this:

![Screenshot from 2020-03-19 15-43-26](https://user-images.githubusercontent.com/91113/77079473-66757100-69f8-11ea-92c4-8aba162a456a.png)

**Comment by vcunat** [comment]
I don't see us using any footer right now.  What about adding it into the (existing) "Continuous builds" section of https://nixos.org/nixos/community.html ?  _Perhaps replacing the direct links to jobsets._

**Comment by edolstra** [comment]
We do have a footer, but it's currently empty. It used to contain the revision and a link to the GitHub source of the homepage (removed in 00ab08e30f5ecb1e0ee7089f6440bf9aeec13a40). So we can easily bring it back.

**Comment by vcunat** [comment]
I mainly meant that a footer with a _single_ entry wouldn't make much sense to me, and I prefer to structure all those links better anyway.

**Comment by davidak** [comment]
>I don't see us using any footer right now.

correct. so we need a different but prominent place until we might have one

Maybe replace "Security" from the menu and put that on some page. I don't think it's a commonly visited page

>What about adding the link into the (existing) "Continuous builds" section of https://nixos.org/nixos/community.html ?

that page is full of information. no one will find it there

>I mainly meant that a footer with a single entry wouldn't make much sense

sure. we might add a footer in the future. discussing that here would be off-topic, so here is a new issue https://github.com/NixOS/nixos-homepage/issues/361

>I prefer to structure all those links better anyway.

@vcunat would you like to discuss that? the marketing team will have the next meeting on 1st april (video conference). we are 5 people right now who has no expertise in marketing :smile: 

https://discourse.nixos.org/t/marketing-team-can-we-present-nix-nixos-better/6249
