### ISSUE TITLE
Nix install command snippet text overflow

### ISSUE THREAD

**Issue by pacien** [NixOS/nixos-homepage#369]
![15853524648031](https://user-images.githubusercontent.com/1449319/77808757-084a2d00-708d-11ea-8ef7-4ed62fbe9c0a.png)

Since https://github.com/NixOS/nixos-homepage/commit/673e131a51fdb7a72a7a89a5f759f4c7c2b9dbcd

**Comment by garbas** [comment]
@pacien thank you for raising this. I'll fix it asap, since I was the one breaking it :)

**Comment by edolstra** [comment]
I would suggest removing `--proto` and `--tlsv1.2`. They provide very little extra security (I mean, if you were really paranoid about security, you wouldn't be doing `curl | sh` to begin with...).
