### ISSUE TITLE
EC2 Page is Out of Date

### ISSUE THREAD

**Issue by Julian** [NixOS/nixos-homepage#37]
Not sure if this is the right place, but https://nixos.org/wiki/NixOS_on_Amazon_EC2 is out of date seemingly, specifically `nixos-rebuild pull` results in:

```
/run/current-system/sw/bin/nixos-rebuild: unknown option `pull'
```

I know it's a Wiki, I'd fix it if I knew enough yet to know what the right thing is now :) (looks like `nixos-rebuild --upgrade switch` might be it?)

(In an unrelated note which probably deserves to be elsewhere, all the tools [well the two there] seem to have `--help` but no `-h`. Is this intentional?)

**Comment by samueldr** [comment]
*This issue can be closed; the wiki isn't managed here anymore.*
