### ISSUE TITLE
Do an inventory of all URLs we had pre-netlify move

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#375]
Verify that all URLs still point to somewhere.

For URLs that do not, decide what should be done.

The issue right now is that we do not **know** what is missing.

**Comment by garbas** [comment]
Since we enabled analytics on netlify we can see "Top resources not found".

I already fixed quite few of the red issues. I'm closing this issue and we can open tickets for each missing url if they still exists.
