### ISSUE TITLE
[Wiki] Port "NixOS Manual" styles to wiki.

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixos-homepage#38]
Currently the wiki seems to be using base styles, and it has a different feel to it than the manual. Making the wiki have the same look as the manual (at least in terms of typography) would make the wiki more readable.

**Comment by edolstra** [comment]
@qknight made a skin, it's at https://github.com/NixOS/nixos-org-configurations/tree/master/delft/wiki-skins. But IIRC, it's not up to date with the current Mediawiki version or the current nixos.org style.

**Comment by qknight** [comment]
@edolstra  would you like me to update it? IIRC: last time you were opposed to its usage.

@Havvy http://blog.lastlog.de/posts/new_nixos_org_mediawiki_theme/

**Comment by Havvy** [comment]
Ah, cool to see some work has already been done for this in the past. I actually filed this bug so that if I'm bored in the future, I have something I can direct my attention towards. But if somebody else wants to do it sooner, so much the better.

This report is almost purely an enhancement. If it's not fixed, nobody is going to really notice, but if it is fixed, it would help tremendously.

**Comment by qknight** [comment]
@Havvy: eelco mentioned a [mediawiki extension for bootstrap](https://www.mediawiki.org/wiki/Extension:Bootstrap) which makes a unified design easy. we should go this direction then i guess.

**Comment by samueldr** [comment]
This can be doubly-closed:

 * The wiki isn't part of nixos anymore.
 * I did use the manual/site styles for the [community wiki](https://nixos.wiki/)

**Comment by davidak** [comment]
@domenkozar can you close this issue?
