### ISSUE TITLE
[Wiki] Cannot confirm e-mail address, error with PHP mail()

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#39]
The only thing the wiki spits out is this:

```
Mailer returned: Unknown error in PHP's mail() function.
```

Someone that can look at the logs will be better suited to see what's the issue.

**Comment by davidak** [comment]
I have the same issue:

```
Nix Wiki could not send your confirmation mail. Please check your email address for invalid characters.

Mailer returned: Unknown error in PHP's mail() function.
```

My E-Mail-Address has no special Characters.

**Comment by qrilka** [comment]
Any chance to get it resolved? Google shows a lot of links to NixOS wiki but some of materials there are outdated and without confirmation it looks there is no way to edit it

**Comment by olejorgenb** [comment]
Any news on this?

**Comment by samueldr** [comment]
*Closing since the wiki officially closed a while ago, and there's now the new [https://nixos.wiki/](https://nixos.wiki/).*
