### ISSUE TITLE
Convert news to single file per entry

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#390]
I think it would be easier to maintain if `news` would be a folder in the git repo with a file for every entry, so you just have to add a new file instead of editing the huge very complex XML file

like in https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual/release-notes

the files can be later converted to Markdown or whatever

what do you think?

**Comment by edolstra** [comment]
What do you consider "very complex" about it? It's a flat list of entries.

**Comment by davidak** [comment]
It just overwhelms me having a 1708 line XML file, even when the actual structure is not that complex. It would be easier for me to edit a file with just one entry.

That would also make it easier if we might add longer entries later.

But it might be ok for now.

**Comment by garbas** [comment]
This can be now closed since news will be aggregated from discourse.nixos.org
