### ISSUE TITLE
Add some more content to release announcements

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#391]
The news entries are identical except the version and codename. Can we add at least one sentence what big highlights it includes?

We might also want to have medium size articles for release announcements like other operating systems, with all highlights, some screenshots etc. That's probably a decision for the marketing team and the release managers.

![Screenshot from 2020-04-11 19-05-08](https://user-images.githubusercontent.com/91113/79050003-651a1b80-7c27-11ea-9ff4-5f0540cda1da.png)

**Comment by garbas** [comment]
This can be now closed since news will be aggregated from discourse.nixos.org
