### ISSUE TITLE
Improve nix package explorer performance (NOTE: not just complaining, solution offered)

### ISSUE THREAD

**Issue by pmwhite** [NixOS/nixos-homepage#395]
Whenever I need to install a package on NixOS, I use the "Search NixOS packages page". Sometimes when I don't even know what package I want, I go to that page and search some keywords to see if there is anything that satisfies my needs. My point is that I find this page is extremely useful. However, it is incredibly slow. Often I will have typed the entire word I want and then have to wait 5 seconds for the page to catch up. While this is not catastrophic, it is not good.

Looking at the source code, I see that it is written using fancy new javascript stuff, including React and JSX. I'd like to submit that this way is not only less maintainable, but also the cause for the poor performance. I'm not indicting the React itself, since it may have some good use-cases, but for this particular page it is certainly overkill.

Since I use this page so much, I figured it would be worth attempting to write a better version. My results of my effort can be found hosted here - https://trailingwhite.space/nix-package-search/. Source code can be found here - https://git.sr.ht/~philipwhite/nix-package-search. At the time of writing this issue, I haven't added a license to the repo yet, but that's coming. I'm thinking I'll just use the same license that NixOS does.

Two suggestions:
1. I'd be quite happy if this version of the page ends up replacing what is currently on the site. I'd be glad to modify it or add anything that is currently missing so that it fits with the rest of the site.
2. It would be nice if the website enabled CORS for the `packages.json` file that the package explorer downloads on each page load. Currently, I just loaded a copy of that file onto my own server, but it would be nice to have it pull directly from the NixOS server (selfishly to reduce load on my own server, and also to keep it always up-to-date).

Currently my version does not have the ability to switch between channels, but this is an easy change.

**Comment by samueldr** [comment]
Hi! :wave: 

Thanks for the interest in improving our website. It's always nice to see interest in the "less glamorous" or even almost hidden bits of this organization.

With that said, this response is split in sections, and the tone will be different in each. I will preface with the tone I want to project, hoping not to cause sparks to fly. Text is such a lossy encoding of thoughts!

* * *

<sup>(neutral, stating facts)</sup>

I am involved in the development of the website, and heavily involved in the development and maintainership of the JavaScript parts.

Most, if not all, of the issues with the performance are coming from the backend-free implementation. It is front-loading all the data in one go. You must also have seen this as you are currently serving an incomplete index split in (for now) 5 files.

I do not like how it takes an inordinate amount of time to load, but this is a limitation we had to work with on the current website and infrastructure.

* * *

<sup>(responding the perceived slight in the second paragraph, so the tone is probably best described as "annoyed". Not at all responding as a NixOS contributor, but on a personal level)</sup>

I'll be blunt, but claiming the performance issues are coming from the "fancy new javascript stuff" seems myopic in my opinion. The re-implementation was compared with the previous "non fancy new javascript stuff" implementation and was found to work just as fast. I wouldn't have felt it would be right if it was slower than what was present.

I will then add that the rewrite in React was made to *improve* the maintainability. The state is controlled in a manner that allows one to reason about the state of the application at any point in its lifecycle. This state is synchronized to the URL of the browser, allowing users to share links, including permalinks, to the search results. That last part was a marked improvement allowing users to share searches.

The intent was (and still is) to implement the options search in a common codebase, sharing all features. Building it using a more involved system like React is not overkill given that intent.

About that topic, I will last say that a bespoke DOM-manipulation maze of functions to build the UI is probably not more maintainable, and I'm not sure I would call that more approachable. Maintainability can be horrible in both approaches, it can also end up being good with both approaches. Though I know which one has the advantage going for figuring out the flow of the application.

* * *

<sup>(hopeful and positive, mind clear from the previous section)</sup>

With that said, there is currently work by @garbas to fix the main issue by instead relying on a backend that does the search. It should additionally allow more in-depth search, which is simply not possible with the current implementation without bloating the index even more.

See https://github.com/NixOS/nixos-search for the WIP repository. (I see there is no issue for tracking the work in this repo.) Maybe @garbas can describe the current plan somewhere and link to it, if there is a more in-depth plan than what was discussed :).

* * *

And finally, on a more personal note, don't let my partially sour response to your contribution ruin your day. Even with what I said, **I am glad people care to take a look and try to fix things**. I think this is why it makes this response hard to write. I don't want to nip innovation in the bud, and **I certainly do not want to stop any enthusiasm you have**.

**Comment by pmwhite** [comment]
Thanks for the response! My day is not ruined at all (that would be bad if it were because when I'm typing this, there are still 23 hours left in my day :)

I have a couple responses to both your factual and "sour" portion (which I don't find all that sour - criticism is helpful for discussion, since this was indeed constructive). First, the improvements that I think I've made are mostly client-side. I realize that a there is a problem loading a large file initially; I tried to mitigate that a little bit by splitting up the files, as you know. That seemed to help things a little bit, but it's still not a completely happy situation.

Aside: When you say "incomplete index split into 5 files", I assume you just mean each of the 5 files is incomplete, but put together they are whole. I downloaded the packages.json file from what I thought was the same place that the current search page does. Of course, it might get out of date, but I believe my page is working with the same size dataset.

> Most, if not all, of the issues with the performance are coming from the backend-free implementation.

My main source of pain when using the page is actually after the package index has loaded. I often make several searches on the page, if the first one doesn't pan out. I've found the speed at which I can type into the box to come to a crawl, especially on the first few characters of the search. Thus, my opinion is in disagreement with your statement.

**Comment by pmwhite** [comment]
Sorry if you just got spammed with email, I was typing and accidentally hit close and comment before I was finished.

**Comment by pmwhite** [comment]
Thanks for the response! My day is not ruined at all (that would be bad if it were because when I'm typing this, there are still 23 hours left in my day :)

I have a couple responses to both your factual and "sour" portion (which I don't find all that sour - criticism is helpful for discussion, since this was indeed constructive). First, the improvements that I think I've made are mostly client-side. I realize that a there is a problem loading a large file initially; I tried to mitigate that a little bit by splitting up the files, as you know. That seemed to help things a little bit, but it's still not a completely happy situation.

Aside: When you say "incomplete index split into 5 files", I assume you just mean each of the 5 files is incomplete, but put together they are whole. I downloaded the packages.json file from what I thought was the same place that the current search page does. Of course, it might get out of date, but I believe my page is working with the same size dataset.

> Most, if not all, of the issues with the performance are coming from the backend-free implementation.

My main source of pain when using the page is actually after the package index has loaded. I often make several searches on the page, if the first one doesn't pan out. I've found the speed at which I can type into the box to come to a crawl, especially on the first few characters of the search. Thus, my opinion is in disagreement with your statement.

> I'll be blunt, but claiming the performance issues are coming from the "fancy new javascript stuff" seems myopic in my opinion. The re-implementation was compared with the previous "non fancy new javascript stuff" implementation and was found to work just as fast. I wouldn't have felt it would be right if it was slower than what was present.

My apologies for being condescending. Let me amend: I did not investigate whether React was itself to blame for the perceived slowness, so I shouldn't attribute it to "fancy" javascript. I am wondering whether we are in agreement on the slowness of the client-side portion; what is your opinion on the comparison of the two pages. I think mine is noticeably faster, but I guess I should not presume that you also think so. If the previous implementation was about the same performance, than it likely is not React itself that is slow.

Now about the matter of maintainability. Here are reasons I argue for a more basic approach here. 

* Using the browser's DOM-manipulation functions and ordinary javascript, I achieved a page with similar functionality a 4th of the code (according to my line counter, the current page uses about 900 lines of js, and mine uses about 180, but you can add 14 lines for the polyfill that I should probably use); of course, I do not have a couple features, so perhaps the better ratio is a third. This first reason boils down to smaller code being easier to fit entirely into one's head. 
* The source code in the repository I linked to contains the entire code for the page - there are no dependencies at all. This also means that there is no setup or environment required to work on the project, and there is no knowledge of any libraries required. It is thus easier find someone who is able and willing to maintain the code. It also means that the payload downloaded is smaller; the network tab of my devtools says that the javascript payload is 78 kb, which is not terrible, but it is a lot larger than the 6 kb that my javascript came to.
* The DOM manipulation required by this application is minimal, which means that understanding the reasons for everything is not too hard. My approach was actually simpler than what I could have done. Every time a character is typed, I remove every child element of the results table and rebuild it from scratch. While I could probably have been more clever to achieve marginal performance improvement, it was much clearer to do it the way I did, and I found that the performance was not too bad, especially if you make the max number of results shown at once be under 100.
* Googling for issues is easier because there are fewer abstractions where the issues might hide. The main things one would have to google with the basic approach are browser APIs.

Don't misunderstand me, I like functional programming about as much as anyone. However, I was head-over-heals in love with it at one point. Right now, I'm at a point where I want to think about decisions within their own context and not dogmatically choose the functional way because it is "right". I don't mean this in a mean way, but it feels like the npm/webpack/react/redux setup comes from an overly dogmatic approach. I don't think manual DOM manipulation should be automatically characterized as a "maze" unless you looked at my code and thought it was a maze; the manual approach is about the same as the non-manual approach in this case, except it is perhaps longer.

I'll stop here. I hope what I'm saying is taken constructively, since that's how it is meant.

**Comment by samueldr** [comment]
Hi,

Thanks for the well-thought-out reply. I can see now that, as I suspected, you weren't being antagonistic.

* * *

> [...] First, the improvements that I think I've made are mostly client-side. I realize that a there is a problem loading a large file initially; I tried to mitigate that a little bit by splitting up the files, as you know. That seemed to help things a little bit, but it's still not a completely happy situation.
> 
> Aside: When you say "incomplete index split into 5 files", I assume you just mean each of the 5 files is incomplete, but put together they are whole. I downloaded the packages.json file from what I thought was the same place that the current search page does. Of course, it might get out of date, but I believe my page is working with the same size dataset.

I tried searching for *zziplib* yesterday and it wouldn't show up, but I didn't do due diligence in opening up the data to inspect. Maybe something went wrong, maybe I made a typo. Sorry about that.

Though yeah, with the upcoming changes this is a moot point, there will be no data to preload. Also a reason why it's been hard to respond, all that work for what may be no good reason soon.

If we were to keep the backend-free approach, I think that chunking the data in multiple files and load them in parts that way would be a good way to make it appear that the application loads faster, though it shouldn't do so without having a global load state implying the data is incomplete until it is complete.

* * *

> My main source of pain when using the page is actually after the package index has loaded. I often make several searches on the page, if the first one doesn't pan out. I've found the speed at which I can type into the box to come to a crawl, especially on the first few characters of the search. Thus, my opinion is in disagreement with your statement.

Thinking a bit more, I think I may be less right than I initially thought. The speed was verified before that was plugged into the History API for URL bar changes. Looking at it right now I assume it is what is causing the main hitches while typing.

If it wasn't for that upcoming change, I would look into fixing it by synchronizing at blur time (when you leave the field) or at a longer debounced interval (so it happens during typing pauses). The biggest issue being that it requires two states to be kept, the internal state of the app and the state in the URL, and no desyncs should happen.

This all comes from the main design goal of keeping the one true state using the History API, but that history, as I've learned in other unrelated projects, causes slowness, and it is heavily browser-dependent. The goal being to always be able to (1) navigate to a stable URL for e.g. channel name/package search and (2) keep appropriate history navigation for back/forward (though I've learned that the way web pages have evolved nobody agrees on that expected behaviour *sigh*).

* * *

Now, in principle I would normally agree that doing simple DOM manipulation is intuitively more manageable for small applets. Though it scales less when you want to compose more complex applications. I am guilty of thinking multiple steps ahead in this case.

And this is where it comes back to future improvements to the current codebase, that are now canceled. I'm waiting to see how it goes for the complete revamp with a backend.

All this is part of why I'm not looking into improving or fixing the current bits, and wouldn't feel right recommending continuing to work on that with the goal of getting this in. Though, if you do it for fun and self-fulfillment, great :).

**Comment by pmwhite** [comment]
I tried *zziplib* myself, and was able to find it on my site; not too important of a matter though. I appreciate your own thoughtful response.

Something which may cause a bit of a disconnect with how different people perceive this page is the level of their hardware and their internet connection. My connection is not too bad, but my laptop is not too fast. It has 8GB of RAM, but the performance bottleneck of the page is a good part CPU, and I have an oldish AMD processor.

I am not understanding why having backend code would end up improving the performance of the page. One good thing about the page is the instant feedback that you get with every keystroke. It would be difficult to maintain this instant feedback if every keystroke sends a search query to the server. I think that the page solves a problem best done on the client-side; why ask a centralized server to take on the computational burden of user searches when we can offload that to the client? The main benefit is that we don't have to download the entire package index. Thus, the hope with a backend solution is that the amount of time saved by avoiding the initial package download is not outweighed by the extra time spent sending requests and responses across the network.

The backend would be quite useful for improving the load time of links that have a builtin query. However, for a query that is not carried with the link, the time it takes to type the search is probably only a bit shorter than the time it takes for the index to download. After the initial search, the package index will be downloaded, which means that additional keystrokes can get instantaneous responses.

A problem that both the current page and my page had was that although the download was happening asynchronously, the page froze while parsing the JSON string. My solution to this was to download and parse the package.json in a web worker and using the web worker as a sort of server that the main thread sends queries to (of course, there is no network boundary to cross there). After making this change, all of the remaining lagginess when typing went away (the results didn't show up any faster, but typing felt more responsive).

There are two more improvements that can be made to what I've done so far.
* Enable browser local storage, which would mean that each user would only need to download the package index once, and subsequent visits would inspect the locally stored data.
* Preprocess the json file to decrease both downloading and parsing times. For example, why serve packages with a field name "description" when "a" will do just as well. As long as the client knows that "a" means "description", there is no difference. Although a change like this would not decrease the gzipped size, since the repetition would get optimized away either way, but it would definitely help the browser parse the faster, since there is less memory to traverse. Another possibility is to trim the platform support list in the package.json file before sending it, since that the client seems to just filter out all but four platforms. This would trim the file size by about a third, from what I've been seeing in my tests.

Anyway, the point of what I'm saying is not to toot my own horn, but because there is a lot that can be done to improve the site, so that any gains made by having a backend would already be acheived by an entirely client-side solution.

A big benefit of the static-only approach is that it can be served entirely on a github pages site, or anything else, which increases the portability of and agility of the site. This worries me less though, since I would not be the one to maintain it.

One last thing I'll mention is that I plan to add support for the options page as well. In fact, I was making the package search page with the goal of also supporting the options page.

**Comment by garbas** [comment]
I would just add a bit to the discussion that packages/options search is being reworked in https://github.com/nixos/nixos-search. My plan is to finish it this week. When I say finish it I mean to have it as feature complete as current implementation, then discuss in which direction we want to expand it.
