### ISSUE TITLE
Decouple the nixos/nixpkgs manuals from the nixpkgs flake input

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#400]
```
 19:03 <worldofpeace> umm, why is the 20.03 manual on the website https://nixos.org/nixos/manual/ 
```

— https://logs.nix.samueldr.com/nixos-dev/2020-04-18#1587236607-1587236688;

The manuals being built are the ones from the input nixpkgs:

```
# flake.nix
  inputs.nixpkgs.url = "nixpkgs/nixos-20.03";
[...]
          export NIXOS_MANUAL_IN="${nixpkgs.htmlDocs.nixosManual}"
          export NIXPKGS_MANUAL_IN="${nixpkgs.htmlDocs.nixpkgsManual}"
```

This prevents us from moving forward either the manual forwards, or the nixpkgs input forwards without affecting the other.

This also makes it look like the current release is 20.03, while it's not been released yet.

* * *

cc @worldofpeace

**Comment by worldofpeace** [comment]
@garbas @edolstra

**Comment by worldofpeace** [comment]
The release docs say https://nixos.org/nixos/manual/index.html#at-final-release-time
> Update the NIXOS_SERIES in the nixos-homepage repository. 

I'm guessing when you bump that it changes the input the website uses https://github.com/NixOS/nixos-homepage/blob/master/Makefile#L1 (before flake)

**Comment by samueldr** [comment]
> I'm guessing when you bump that it changes the input the website uses https://github.com/NixOS/nixos-homepage/blob/master/Makefile#L1 (before flake)

Exactly, the way this has been reworked with flakes the manuals are "forcibly shoved" in the Makefile instead of letting the Makefile handle building it. So that instruction will need a touch-up too.
