### ISSUE TITLE
https://nixos.org/nixos/support.html is missing yet still referenced in nixpkgs

### ISSUE THREAD

**Issue by operator-name** [NixOS/nixos-homepage#406]
I'm unsure if this should be a bug here or in nixpkgs, the offending nixpkgs source is [nixos/modules/misc/version.nix#L113](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/version.nix#L113) which at least appears in Pantheon's about settings page.

![Screenshot from 2020-04-21 18 15 41](https://user-images.githubusercontent.com/53277700/79894394-4a049400-83fd-11ea-82f3-8acb9c9bf6f3.png)

[The last archive of the content](https://web.archive.org/web/20191027102323/https://nixos.org/nixos/support.html) seems similar to #402 so I assume things were moved around.

**Comment by davidak** [comment]
The right URL is probably https://nixos.org/learn.html now, but we will discuss it.

Since it's related to the website, the issue is fine here.

Thank you for the report.

**Comment by garbas** [comment]
I would say to change the following:
```
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
```

**Comment by samueldr** [comment]
We should still provide a redirect to a page that makes sense.

**Comment by davidak** [comment]
I created PRs for the suggestions.
