### ISSUE TITLE
entr make does not work

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#410]
I followed the instructions in the readme, but it does not rebuild after changes, only the first time when the command is started.

## Steps to reproduce

1. clone nixos-homepage
2. add new page
3. `[nix-shell:~/code/nixos-homepage]$ git ls-files | entr make`
4. edit that page and save

It might just work with changes to files tracked by git. @egasimus 

This is a useful feature, please make it work with any file change (except in .git i guess).

**Comment by aepsil0n** [comment]
You at least have to exclude the files created by make. Otherwise, you will get into an infinite rebuild loop (make → change to file → entr detects the change → make → …). Which files that are not in Git are you editing though, that this is a problem?

**Comment by davidak** [comment]
>Which files that are not in Git are you editing though, that this is a problem?

Files that are **not yet** in git, like a new page.

**Comment by aepsil0n** [comment]
Ah, that makes a lot of sense. What I do on my own projects quite often, is to use [fd](https://github.com/sharkdp/fd) instead of `git ls-files`. It looks for all the files, but still respects `.gitignore`. Let me test that out and write a PR…
