### ISSUE TITLE
Nixpkgs manual says version is pre-git

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixos-homepage#417]
![Screenshot from 2020-04-28 17 56 38](https://user-images.githubusercontent.com/28888242/80541705-a75a9100-8979-11ea-80d2-bf1282c58086.png)

Expected version would be just `20.03`.

**Comment by bjornfor** [comment]
FYI, after https://github.com/NixOS/nixpkgs/commit/d2a2ec2ebe49c42127cbf316d215a64c60d68fde it will say "post-git". But surely neither is good for the manual.
