### ISSUE TITLE
Install image filenames and checksum filenames do not match

### ISSUE THREAD

**Issue by MawKKe** [NixOS/nixos-homepage#420]
I am unsure whether this repo is the right place to raise this issue:

On the download page (https://nixos.org/download.html) the filenames of the server-suggested .iso images  do not match the names in the respective checksum files. This makes the verification a cumbersome and error-prone process, since I cannot do a simple `sha256sum -c <checksum-file>`.

Example: 

The server-suggested name:
*  `latest-nixos-minimal-x86_64-linux.iso`

The name provided in latest-nixos-minimal-x86_64-linux.iso.sha256:
*  `nixos-minimal-20.03.1782.210d8624ac4-x86_64-linux.iso`

**Comment by garbas** [comment]
This should be now resolved, please reopen if it is not
