### ISSUE TITLE
The "Cross-Origin Request Blocked" error on the Search NixOS packages page

### ISSUE THREAD

**Issue by Ovsyanka** [NixOS/nixos-homepage#428]
I faced with the error
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://releases.nixos.org/nixos/20.03/nixos-20.03.1917.82b5f87fcc7/packages.json.br. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

on the Search NixOS packages [page](https://nixos.org/nixos/packages.html?channel=nixos-20.03).

Note that the error only appears if I choose `nixos-20.03` and not when I choose `nixpkgs-unstable`.

I use `Mozilla Firefox 76.0.1`

**Comment by garbas** [comment]
I will close this issue with wontfix flag since we are very close from switching to https://nixos-search.netlify.app. This should not be a problem there. Please give it a try and report issues to https://github.com/nixos/nixos-search.

**Comment by garbas** [comment]
@Ovsyanka I forgot to thank you for the time you took to report the issue. Thank you!
