### ISSUE TITLE
VirtualBox appliances latest download link is broken on homepage

### ISSUE THREAD

**Issue by dqdinh** [NixOS/nixos-homepage#43]
Both of the urls below return 404s:

http://releases.nixos.org/nixos/14.12/nixos-14.12.496.5f7d374/nixos-14.12.496.5f7d374-x86_64-linux.ova
http://releases.nixos.org/nixos/14.12/nixos-14.12.496.5f7d374/nixos-14.12.496.5f7d374-i686-linux.ova

**Comment by domenkozar** [comment]
It works at the moment: http://nixos.org/nixos/download.html
