### ISSUE TITLE
follow nix repo directly for nix releases

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixos-homepage#432]
Right now we follow which Nix is released in nixpkgs. This means we need to wait for channel update. We know this is not ideal, but was good enough to start.

Going forward this will be improved by following the nix repository directly. As we currently use flakes to follow other repositories we need to wait for Nix to also have `flake.nix`. https://github.com/NixOS/nix/pull/3573

<details>
   <summary>This ticket was changed from originally reported issue...</summary>

#  nix manual wasn't updated with the latest release

Nix v2.3.5 was released yesterday, but the documentation changes are not visible on the website yet. As far as I know this used to update automatically when a new release happens, either this doesn't work anymore or the page is cached too agressively.
</details>

**Comment by garbas** [comment]
I'm hijacking this ticket to convert it into actionable issue.

**Comment by LnL7** [comment]
Is there anything manual that could be done in the meantime? Sounds like the way to go, but would be great if the installer wouldn't point people at seemingly non-existent documentation.
