### ISSUE TITLE
https://nixos.org/nix/ broken

### ISSUE THREAD

**Issue by danieljharvey** [NixOS/nixos-homepage#439]
It looks like https://nixos.org/nix/ is missing? 

Getting `The requested content at /nix/ could not be found.`

**Comment by davidak** [comment]
Yes, that is expected. We reorganized the website.

How did you get there?

We should setup a redirect to `https://nixos.org/`.

**Comment by danieljharvey** [comment]
Ahh fair enough. It was the top result from googling `nix package manager`.

**Comment by grahamc** [comment]
We should set up redirects.
