### ISSUE TITLE
Change how we talk about Nix/NixOS on the landing page

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-homepage#444]
We need to find a nicer way how we describe Nix and NixOS on the landing page.

**Comment by davidak** [comment]
We can just ask people in the survey

- How would you describe Nix in one sentence?
- How would you describe NixOS in one sentence?

we might get some good inspiration.

https://pad.nixnet.services/5gt7n9h8S5yDyA0xk72uOg?view
