### ISSUE TITLE
Blog / News section

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-homepage#446]
- aggregate categories of teams on discourse
- integrate planet.nixos.org

**Comment by Profpatsch** [comment]
I’m quoting your thoughts from https://github.com/NixOS/nixos-homepage/pull/552#issuecomment-697167063 @garbas:

> Here is a mix of my thoughts on the news section in general:
> 
>     * I personally find it completely OK if news from 10 years ago has broken links. I use [Wayback Machine](https://addons.mozilla.org/en-US/firefox/addon/wayback-machine_new/) add-on which fixed this for me most of the time.
> 
>     * News section was taken from the landing page because existing users are not primary audience of the landing page. But there is a section on the landing page were we can show one important announcement, like we already have for NixCon or like we will have when new Nix/NixOS version is released. So in reality is not really gone from the landing page just reduced to one item.
> 
>     * There is a plan that each release version would get a dedicated page, linking to only, well mostly, to release.nixos.org, which is our immutable storage - out archive.org.
> 
>     * It is important to define the purpose of the news section of the site. I would refer here to the audience and fuel the purpose from there. Main audience of the website are new nix users and they "story" could be something like this:
>       
>       1. Just heard of Nix, went to nixos.org and got excited because of the examples and benefits it brings - Landing and Features page
>       2. Downloaded it for my system / cloud (Download page)
>       3. Need to learn more about Nix, I hope there are some tutorials about Nix for X language - Learn page
>       4. Everything is working except one little thing is missing how do I contribute back, oh is just a PR? nice and simple - Community page -> pointing to How to contribute tutorial
>       5. I'm sold on Nix I want to get involved into the community and help as much as I can (News/Blog)
>       
>       As you can see each of above points happen in some sort of order and each of above points correlates to some page. You can also see that we try this order of pages in the navigation bar (Community, Governance, Donate pages are going to be merged soon, once we have other pages to take their place).
> 
> 
> The purpose of the news/blog section is then to show the "internals" of the community, trying to answer things such are "What are others working on?", "What is happening in marketing team?", "What is coming next in Nix?", "Which RFCs are being reviewed/discussed?", ...
> 
> This works is being tracked under #446
> 
> Regardless of my comments I think this PR improves on the current state, until we actually implement #446 (expecting this to happen this year).

**Comment by Profpatsch** [comment]
Personally I liked the news page going back all the way to 2004, since it is an important historical document (plus it’s super nostalgic). We should take care to not destroy historical insight if it can be avoided. The linked papers are still as valid as ever, for example.

**Comment by samueldr** [comment]
An implementation detail note proposal:

Do not *directly* integrate planet.nixos.org into the *actual* NixOS.org news. Rather, implement the NixOS.org news as a data source into planet.nixos.org, which can be consumed independently as needed.
