### ISSUE TITLE
Search "actions" in header can't be used on narrow viewports

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#457]
The `... for packages` and `... for options` "drop down" items can't be activated using a mouse (unverified for keyboard) when the viewport is narrow. 

![image](https://user-images.githubusercontent.com/132835/83926524-09b46780-a758-11ea-9b03-bb2055227562.png)

**Comment by garbas** [comment]
Yeah, I dislike this UI as well, but couldn't come up with something better. We could have 2 buttons, but that looked really weird when I tried it.

I wonder if we should just search for packages on the landing page (with a link to options) and remove this search from the navigation bar. Also if there is a search input box in the navigation one might think it will search this website, which is kinda confusing.

@samueldr What do you think? I'm more and more inclined to remove the search from the navigation bar and only leave it on the landing page.

**Comment by samueldr** [comment]
I agree that the search bar in the header is a bit clumsy because of the unspoken contract that a search bar in the header searches for the whole site.

I'd say, in addition to the main page search bar, add a (less big) copy of it to the top of the Learn page maybe? This might help lost souls that wander off the main page and never go back to the main page find it better?

**Comment by asbachb** [comment]
I see two problems:

1) As @garbas already mentioned my expectation about the search box on front page would be that the box searches the entire site.
2) A user would need to use the mouse, then use the keyboard and then use the mouse again since the "sub buttons" are not selectable by arrow key which feels quite weired.

**Comment by garbas** [comment]
I'll remove the search from the header and try to add it somewhere to learn page.
