### ISSUE TITLE
Migrating to bootstrap 4.5

### ISSUE THREAD

**Issue by Xel** [NixOS/nixos-homepage#462]
Is there any interest in migrating from bootstrap v2.3.2 to a more recent stable version? I know there are a few breaking changes here and there, but from a quick look at the code base and the bootstrap docs, it's nowhere near a rewrite. 

If someone was willing to put in the work, is there any other reason why we're not willing to bump up ?

**Comment by samueldr** [comment]
@garbas probably can word it better, but we're working (on a short-to-mid term) on getting an actual design firm working with us for the visuals.

What this means, firstly, is that any effort for big changes like those are not worth it right now.

(Additionally, I'll say that bootstrap 2 to any future version is majorly breaking, the whole way it's structured changed drastically from semantics classes, to less semantics and more utilities classes. I'm pretty sure updating to another version of bootstrap would be enough work to be comparable to a small re-designing.)

**Comment by garbas** [comment]
@Xel thank you for noticing the old bootstrap version we are using.

As @samueldr mentioned we hope tackle the design in next 3 months (target date is next nixos release) with a help of some profesionals. 

If you find some css quirks that will not take you a rewrite to fix please send the PR.
