### ISSUE TITLE
Rendering of longDescription on packages page is not nice

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixos-homepage#473]
The `meta.longDescription` appears to be meant to be prose, but it is rendered using a fixed-width font on the [packages page](https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=frescobaldi).

Also, in many cases the content has hard line breaks, but is also soft-word-wrapped, meaning that for some font and window sizes there are lots of mostly-blank lines where a couple of words have been soft-wrapped.

The [nixpkgs manual](https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes) does not give any guidance on how `longDescription` should be formatted, or how and where it will be displayed.

I personally would suggest:
1. Render `longDescription` in a proportional-width font.
2. Discourage hard-wrapping the source text: It makes it impossible to adapt to different screen widths further down the line.

**Comment by samueldr** [comment]
See if it is fixed in https://search.nixos.org/; if it is, then this issue can be closed as search.nixos.org will replace the current implementation in the coming near future.

**Comment by Thra11** [comment]
Certainly an improvement. Looks like it's stripping the newlines from the `longDescription`, which deals with the broken up sentences. I assume if anyone tries to write more than one paragraph it'll squash them into one, but I doubt anyone cares enough to do anything about that (As a very rough estimate, only 1986/32381 even have a longDescription).
