### ISSUE TITLE
No obvious way to switch between package and option search

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixos-homepage#475]
Since the redesign the options and packages link vanished from the top menu. I can easily get to the packages search by using the input form on the main page, but then there is no way to navigate to options search without going back.

**Comment by davidak** [comment]
will be solved soon

>I'm going to leave a "search icon" link on the right side (pointing to packages search) just to keep it easier to find. Eventually (any day now) this will point to http://search.nixos.org where visitor will see that you can search also for nixos options.

https://github.com/NixOS/nixos-homepage/pull/472#issuecomment-644555422

**Comment by garbas** [comment]
@mweinelt Last 2 issues are being worked before we make [search.nixos.org](https://search.nixos.org) official search for packages and options. Last 2 issues are regarding search filters and relevance, so please don't report (yet) the issues if you can not find things, but the structure of the website is there and I think that makes this issue "fixed", in a very near future (I'm talking this week).

I'll go ahead and close this issue, but please reopen it if you think that switching between packages/options search is not clear on the new search page.
