### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#477]
I had the idea to do a yearly community survey to know our community better and get feedback.

I will create a concept for it.

**Comment by davidak** [comment]
Here is my concept: https://pad.nixnet.services/wpvO_S3RTDyLIBqiSPd55Q?view

Please provide feedback.

**Comment by gilligan** [comment]
Hi @davidak - i wasn’t aware of your effort and i have already put together a survey based on input on different surveys from different communities which i have also already tested on several individuals. I also had a video chat with Taylor Fausak who has for over 3 years run the Haskell community survey to benefit from his experience of doing so.

I have been working on this together with @andir. The survey is basically in place and theoretically ready to go minus making potential refinements to questions.

I guess it would make sense for the 3 of us to have a chat?

**Comment by davidak** [comment]
Inkscape web site survey is one page with 7 questions, all simple text boxes.

https://twitter.com/inkscape/status/1286081829985046528

![Screenshot from 2020-08-26 19-35-56](https://user-images.githubusercontent.com/91113/91337263-6792a180-e7d3-11ea-83a1-d445fc317e4b.png)

---

## Help make Inkscape's website better!

We are revamping some pages and need your help to shape the future site. Thank you for contributing to the project!

What does Inkscape mean to you?

What problem(s) does Inkscape solve for you?

How does Inkscape compare to other similar apps?

What words do you associate with Inkscape?

What do you look for the most on the Inkscape website?

What would you most like to see on the Inkscape website?

What country do you live in?

**Comment by davidak** [comment]
I hacked in the nixos logo in the limesurvey package. So https://github.com/NixOS/nixpkgs/issues/86087 is not needed this time.

https://github.com/NixOS/nixos-artwork/blob/master/logo/nixos.svg
https://github.com/davidak/nixpkgs/tree/survey-2020

![Screenshot from 2020-09-07 02-21-13](https://user-images.githubusercontent.com/91113/92338648-f21bb080-f0b1-11ea-8abf-aab08a47e797.png)

**Comment by davidak** [comment]
Ticket for infrastructure: https://codeberg.org/davidak/nixos-config/issues/23

**Comment by davidak** [comment]
We focus this year on the website redesign. The concept is here: https://pad.nixnet.services/5gt7n9h8S5yDyA0xk72uOg?view

Feedback welcome!

**Comment by davidak** [comment]
We decided to not do a survey on the redesign, since it's very subjective.

We will plan a community survey for next year.

**Comment by bpiv400** [comment]
The marketing committee agreed on a set of questions: https://pad.nixnet.services/wpvO_S3RTDyLIBqiSPd55Q?view

I'm transferring the questions and Logic into LimeSurvey. I'm targeting next week to have most of an MVP finished. 

We're also hoping to transfer the Hetzner instance where the survey is hosted to NixOS Foundation. Currently trying to figure out who to contact about that.

**Comment by garbas** [comment]
https://survey.nixos.org is up and running.

**Comment by davidak** [comment]
@garbas does that mean you don't need my VM anymore and i can delete it?

**Comment by garbas** [comment]
> @garbas does that mean you don't need my VM anymore and i can delete it?

yes

**Comment by davidak** [comment]
The survey is online, so we can close this. Thanks to everyone involved to make this happen! :sparkles: 

https://survey.nixos.org/2022
