### ISSUE TITLE
"Search NixOS packages" broken Nix expression links

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#48]
https://nixos.org/nixos/packages.html

is: https://github.com/NixOS/nixpkgs/blob/release-14.12//nix/store/ia013c0gf5p4srg2h6c87az0a4j4m15g-nixos-15.09.338.b02bbbc/nixos/pkgs/games/0ad/default.nix#L116
should be: https://github.com/NixOS/nixpkgs/blob/release-15.09/pkgs/games/0ad/default.nix#L116

https://github.com/NixOS/nixos-homepage/blob/master/nixos/packages.tt#L172
@edolstra do you mean this issue with your FIXME comment? then i would delete it in my fix.

**Comment by davidak** [comment]
source: `"position":"/nix/store/ia013c0gf5p4srg2h6c87az0a4j4m15g-nixos-15.09.338.b02bbbc/nixos/pkgs/games/0ad/default.nix:116"`

maybe slice after the 5. `/`

**Comment by davidak** [comment]
@edolstra i think you mean with your comment the problem, that `latestNixOSBranch` is 14.12 but the `Makefile` that builds `packages.json.gz` is executed on a 15.09 system and has the path of that like `/nix/store/qczmxcd81p4r4vrxgaczidw92jhdyyim-nixos-15.09.343.1b83abb/nixos/pkgs/games/0ad/default.nix` and some packages are in 15.09 but not in 14.12.

the solution is to build the website on a system with the `latestNixOSBranch`. maybe inside a container...

**Comment by vcunat** [comment]
It seems like there still are some bugs in the links: https://github.com/NixOS/nixpkgs/issues/12729

**Comment by vcunat** [comment]
Note: I'd reopen but I don't have permissions for that.
