### ISSUE TITLE
adding-new-plugins-to-nixpkgs  all the links in this section are broken.

### ISSUE THREAD

**Issue by nixinator** [NixOS/nixos-homepage#482]
Seems link checker works :-).

https://nixos.org/nixpkgs/manual/#adding-new-plugins-to-nixpkgs

all  the links in this section are broken.

example

https://nixos.org/pkgs/misc/vim-plugins/generated.nix

Seems to directly link in to nixpkgs somehow.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/update.py

https://github.com/NixOS/nixpkgs/tree/master/pkgs/misc/vim-plugins/update.py

not sure how to fix this, without some clever rewrite foo on the web server.

i guess it's a fight between the automated doc building, how git up generates it direct linking into repo's.

perhaps someone can explain the relationships.

**Comment by edibopp** [comment]
You ran `linkchecker https://nixos.org` to find this? I feel like we should add this as a GitHub action to be run after deployment.

**Comment by nixinator** [comment]
Yeah, link checker seems to work well on find those broken links..

I see you made a PR for this. Nice!  

However, perhaps one should not do a direct link into 

https://github.com/NixOS/nixpkgs/tree/master/pkgs 

from the documentation as those links are unstable.

**Comment by garbas** [comment]
fixed in #487
