### ISSUE TITLE
Different logos for each project 

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-homepage#5]
It would be awesome if there were a distinct logo for Nix, NixOS etc. 

Perhaps the mirrored lambda signs that make up the current logo could be used:
- nix is a single sign 
- nixpkgs is three signs, like a forest 
- nixos is the circle 
- nixops is intertwined circles like the Olympic rings 
- hydra is a circular tree of signs, like a plasma lightning disk

**Comment by Mathnerd314** [comment]
https://github.com/qknight/Multi-PlatformSoftwarePackageManagement/blob/master/images/nix-collection.svg looks reasonable, it uses the old logo though.

**Comment by garbas** [comment]
I'm closing this as a duplicate of #2. This issue talks about specific idea how to address general goal in #2.
