### ISSUE TITLE
"Failed to get package data" (packages.json.gz) in dev environment

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#50]
why do i get this error message but the browser has loaded the file like the live site?

![bildschirmfoto 2015-09-15 um 20 59 42](https://cloud.githubusercontent.com/assets/91113/9886987/8407d8b6-5bed-11e5-8ab9-e8727234d31a.png)

**Comment by edolstra** [comment]
The nixos.org Apache configuration has:
```
        # Serve the package/option databases as automatically
        # decompressed JSON.
        AddEncoding x-gzip gz
```
You probably need something similar.

**Comment by davidak** [comment]
Thanks, i will test it this evening.

http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
