### ISSUE TITLE
Font and typography: give it another look once redesign and content is in place

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#508]
This is a meta ticket to collect all the fixes needed regarding fonts and typography.

We need to give another look at the fonts and typography once redesign is done. The proposed design did not force us to use certain font (this was requested) but left it to us to decide. Few proposals were given:

- **Zilla Slab**
- **Krub**
- **Sora**
- **Open Sans**

### Collected feedback that we should consider:

- The typography on mobile is too splashy: too big and lack of security margins. Consequentially, it is harder to sync and parse the content (#600)
- Self host the font (#601, #551)

<details><summary>Original message of the issue</summary>
I'm not happy with the font choices for the redesign. They feel arbitrary and not specifically a good fit for our project.

- **Zilla Slab** looks like a typewriter, so not modern.
- **Krub** has many curves which don't fit the rest of the design with a lot of sharp edges
- **Sora** feels messy and unfocused with all the small details
- **Open Sans** is actually not bad. it's perfectly readable and for good reason the second most popular font on google fonts

Once we select fonts we should serve them from the nixos.org.

The demo uses **Sora** for the headings and **Krub** for the paragraphs in the current state.

![Screenshot from 2020-08-28 21-46-00](https://user-images.githubusercontent.com/91113/91609614-08ba5d00-e978-11ea-8d45-2a5e2f187412.png)

I find the fonts too fancy and detailed. The round w and x distract me from the content. I have autism and dyslexia, so i'm very easy distracted and it's hard for me to read. So it is an accessibility issue.

Here are my alternative suggestions:

![Screenshot from 2020-08-28 17-57-55](https://user-images.githubusercontent.com/91113/91610064-d5c49900-e978-11ea-897e-7e3b59f6226e.png)

**Source Sans Pro + Open Sans**

Perfectly readable, heavy heading.

![Screenshot from 2020-08-28 18-01-57](https://user-images.githubusercontent.com/91113/91610234-220fd900-e979-11ea-8f16-d5f8a9d3aa1d.png)

**Overpass + Open Sans**

(https://reproducible-builds.org/ uses Overpass for all text 😬)

i find the first suggestion more readable, the second looks sharper and might fit the nix snowflake and lambda better

We can ask the designer if these fonts fit together and to the rest of the new design. Source Sans Pro + Open Sans is a popular pairing according to google fonts.
</details>

**Comment by blaggacao** [comment]
You might want to have a look at typography.js or design token font declarations in the process.

**Comment by garbas** [comment]
I'm going to hijack this issue and turn it into an action item.
