### ISSUE TITLE
Minimal Docker image example doesn't work on macOS

### ISSUE THREAD

**Issue by bxrt** [NixOS/nixos-homepage#514]
The expression for the "Minimal Docker image" example on https://nixos.org/ produces a Docker image based which is compiled for macOS, whereas Docker needs the image to be compiled for Linux:
```
$ nix-build default.nix -o ./result
/nix/store/iqfh088nkrqmdvd05rjn3g7nkiiv6lzb-only-hello.tar.gz
$ docker load -i ./result
Loaded image: only-hello:amj73ijs77wmxdp11zglwp3i2shxv9xy
$ docker run only-hello:amj73ijs77wmxdp11zglwp3i2shxv9xy hello
standard_init_linux.go:211: exec user process caused "exec format error"
```
I believe this is a bug in the content.
The changed expression:
```
{ pkgs ? import <nixpkgs> { system = "x86_64-linux"; }
}:
pkgs.dockerTools.buildLayeredImage {
  name = "only-hello";
  contents = [ pkgs.hello ];
}
```
returns the expected/desired result on macOS (not tested on Linux).
This requires a remote builder for Linux like https://github.com/LnL7/nix-docker or https://github.com/nix-community/linuxkit-nix. I used the former, then discovered the latter, which seems easier to set up and use.

I suggest adding a couple of lines for macOS users to say that:
macOS users should note that a Linux environment is needed to build Docker images. Nix can use remote builders in containers or virtual machines to build for other architectures. See for example: https://github.com/LnL7/nix-docker or https://github.com/nix-community/linuxkit-nix. Learn more about remote builds: https://nixos.org/manual/nix/stable/#chap-distributed-builds.

**Comment by garbas** [comment]
Thank you! I definitely looks like system needs to be set to "x86_64-linux".
