### ISSUE TITLE
Main page demo content for redesign

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#519]
From #510 

 * [x] Automatically build svgs for demos
 * [x] A sixth demo for the examples

We have five demos, but three columns! Let's push for an additional demo!

**Comment by garbas** [comment]
svg is now built with `asciinema-scenario` tool

https://github.com/NixOS/nixos-homepage/pull/526

**Comment by garbas** [comment]
sixth demo done with #535
