### ISSUE TITLE
cover demo won't load after last update

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#530]
Verified on nixos.org

```
Uncaught only asciicast v1 and v2 formats can be opened
```

Pretty sure this must come from #526

To reproduce:

 * Try playing the demo on the front page
 * Observe the message in the developer console

**Comment by garbas** [comment]
@samueldr and big thank you for reporting this!

**Comment by davidak** [comment]
Is it really fixed? I still get the error and i'm sure i cleared the cache :smile: 

![Screenshot from 2020-09-15 13-03-47](https://user-images.githubusercontent.com/91113/93203127-21868900-f754-11ea-854e-e5db456e93b4.png)
