### ISSUE TITLE
ascii cinema nix-shell too short 

### ISSUE THREAD

**Issue by teh** [NixOS/nixos-homepage#541]
This demo: https://nixos.org/#asciinema-demo-cover

At 23-24s it shows "node" running so briefly I missed it the first time round.

Unrelated but to play devil's :avocado:  - `docker run node -e "console.log(1 + 1)" ` does exactly the same so it's a cool but not necessarily distinguishing feature :)

**Comment by utdemir** [comment]
It also happens around 48-50s too. I think there seems to be not enough delay before clearing the screen.

**Comment by garbas** [comment]
@teh oh I understand the issue now. doesn't look good now. I plan to work on few issues with asciinema-scenario this week and this will be the first in line.
