### ISSUE TITLE
ascii cinema spacing on mobile

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#544]
![signal-2020-09-21-002201](https://user-images.githubusercontent.com/91113/93724013-da5d2580-fba3-11ea-8273-fe92aefc823f.png)

wrapped items have different space. is that good for orientation or should the same elements also have the same spacing?

On Xiaomi Redmi Note 4 with Firefox Klar.

Reproducible on desktop Chromium.

![Screenshot from 2020-09-21 00-48-44](https://user-images.githubusercontent.com/91113/93724100-7e46d100-fba4-11ea-88a2-d28de2ca34b3.png)

also, is there too much space at the start and end of the section?

**Comment by Javiertiolico** [comment]
> ![signal-2020-09-21-002201](https://user-images.githubusercontent.com/91113/93724013-da5d2580-fba3-11ea-8273-fe92aefc823f.png)
> 
> wrapped items have different space. is that good for orientation or should the same elements also have the same spacing?
> 
> On Xiaomi Redmi Note 4 with Firefox Klar.
> 
> Reproducible on desktop Chromium.
> 
> ![Screenshot from 2020-09-21 00-48-44](https://user-images.githubusercontent.com/91113/93724100-7e46d100-fba4-11ea-88a2-d28de2ca34b3.png)
> 
> also, is there too much space at the start and end of the section?
