### ISSUE TITLE
Cannot save the new manual in the wayback machine (web.archive.org)

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixos-homepage#550]
https://web.archive.org/save/https://nixos.org/manual/nix/stable/

returns an error. We should investigate, because we really want the manual to be archived in reasonable time-steps.

**Comment by makefu** [comment]
according to https://web.archive.org/web/20200916201737/https://nixos.org/manual/nix/stable/ it was working at least once (2020-09-16 20:17:37)

**Comment by garbas** [comment]
I think this has been now resolved, please reopen the issue if I misinterpreted the waybackmachine interface.

https://web.archive.org/web/20200921134446/https://nixos.org/manual/nix/stable/

**Comment by Profpatsch** [comment]
Looks great!
