### ISSUE TITLE
Font is not being served from a nixos.org property

### ISSUE THREAD

**Issue by andir** [NixOS/nixos-homepage#551]
Ideally all resources required for the website should be served by the website. Currently the font(s) is being loaded from Google Fonts which is not really ideal.

**Comment by garbas** [comment]
@andir We haven't a final call for the font which we will look at one point. This work is being tracked under https://github.com/NixOS/nixos-homepage/issues/508

**Comment by raboof** [comment]
Regardless of what font we'll choose, we can independently start work on self-hosting the fonts (and document how to update this when we select different ones). https://webdesign.tutsplus.com/tutorials/how-to-self-host-google-fonts--cms-34775 looks like it has some helpful pointers.
