### ISSUE TITLE
NixOS Options search is not easily discoverable from the home page.

### ISSUE THREAD

**Issue by nbp** [NixOS/nixos-homepage#553]
Previous options and packages used to be listed as top-level entries in the website. (in the previous previous version of the website). This section then moved to the Learn section, and now it moved to the footer of the pages.

The footer is hardly discoverable, as mostly unread by most users.

**Comment by garbas** [comment]
Oh I didn't know we skipped the search section from the learn page, thank you for reminding me. I'll add it back.

Search input is going to be unified. One search input for packages, options, documentation, website, ... this is tracked under https://github.com/NixOS/nixos-search/issues/95.
