### ISSUE TITLE
A few minor issues with the ascii cinema examples

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixos-homepage#558]
#..w..a..t..c..h..i..n..g.., watching, t..h..e.., the, c..o..m..m..e..n..t..s.., comments slowly appear in the ascii cinema bits is really tedious, especially when most of the examples in question are short enough that they could be presented as static text.

Using commands like `bat` (which I assume is a `cat` alternative/replacement?) is distracting: If you're not familiar with `bat`, it's not immediately obvious whether calling `bat` is doing something special/relevant to nix (it's not, it's just showing the contents of the file).

Instructing the viewer to pause the video to read the text, when there's no real reason for it to have been a video in the first place seems a bit ... weird?

If you hover over it, the playback controls appear, which covers up the line that's currently being entered, i.e. the most interesting line (I assume this is an upstream bug in ascii cinema). It also makes it difficult to navigate back to a specific part of the video, since  you can't see what's going on while you're dragging the position.

There are a few typos:
> And POOF, just like that *your are* back to your normal

I thought I'd seen another typo, but I can't find it now.

I assume the ascii cinema bits are supposed to draw your attention where static code snippets might not, but I'm not convinced that they'll keep peoples attention long enough to get to the interesting bits.

**Comment by garbas** [comment]
> #..w..a..t..c..h..i..n..g.., watching, t..h..e.., the, c..o..m..m..e..n..t..s.., comments slowly appear in the ascii cinema bits is really tedious, especially when most of the examples in question are short enough that they could be presented as static text.

#560 

> Using commands like bat (which I assume is a cat alternative/replacement?) is distracting: If you're not familiar with bat, it's not immediately obvious whether calling bat is doing something special/relevant to nix (it's not, it's just showing the contents of the file).

#561 

> Instructing the viewer to pause the video to read the text, when there's no real reason for it to have been a video in the first place seems a bit ... weird?

This examples are not really meant to educate much but more to excite newcomers to give nix a try. what is still missing are the tutorials that they can follow after watching this short examples.

> If you hover over it, the playback controls appear, which covers up the line that's currently being entered, i.e. the most interesting line (I assume this is an upstream bug in ascii cinema). It also makes it difficult to navigate back to a specific part of the video, since you can't see what's going on while you're dragging the position.

#562 
> There are a few typos:
>
>    And POOF, just like that your are back to your normal
>
> I thought I'd seen another typo, but I can't find it now.

I'll fix this right away.

> I assume the ascii cinema bits are supposed to draw your attention where static code snippets might not, but I'm not convinced that they'll keep peoples attention long enough to get to the interesting bits.

We received fairly positive reaction on this videos. I'm not saying this video will stay but we are searching for ways how to "excite" newcomers about certain use cases. At the same time we are also aware that we don't have the capacity - at least not yet - to record this videos and keep them updated (multiple re-recordings). Asciinema videos is a nice compromise, since the "video" is generated from a text file (eg. [demos/cover.scenario](https://github.com/NixOS/nixos-homepage/blob/master/demos/cover.scenario))

**Comment by Thra11** [comment]
I may have come across as a little bit too negative: I do like the videos as an engaging way to show off commands: enter this simple command... get this really useful result.

I wonder if we could try putting the commentary as "printed immediately" (though that wouldn't work if there's a clear screen (`--`) immediately after it. Not sure if there's a way to 'escape' a leading `#`, so that they're still obviously comments to the viewer, but don't get ignored as comments when building the video.

**Comment by garbas** [comment]
@Thra11 No worries. Your concerns are valid, thank you for opening the issue and taking the time to explain it. I'm not sure when, but soon (I hope this week) I'll try to look at the issues I have opened based on your feedback.

**Comment by deviant** [comment]
I'd much prefer static code snippets, for one - they don't require JavaScript, and aren't slow or annoying (why do I have to sit through something which could be expressed much more efficiently as a block of text?).
