### ISSUE TITLE
Add Package search to Nix homepage

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#56]
Select channel: Linux or Mac, stable or unstable

<table class="source-tableeditor">
<tbody>
<tr>
<td></td>
<td>stable</td>
<td>unstable</td>
</tr>
<tr>
<td>Linux</td>
<td>nixos-17.09</td>
<td>nixos-unstable</td>
</tr>
<tr>
<td>Mac</td>
<td>nixpkgs-17.09-darwin</td>
<td>nixpkgs-unstable</td>
</tr>
</tbody>
</table>

since unstable channels are very active, the packages.json.gz should get generated at least once a day from github source, better every hour.

**Comment by garbas** [comment]
this is being fixed now

**Comment by davidak** [comment]
no, the request was to add a "packages" page with search to Nix page similar to NixOS, but directed to people who use Nix on macOS or linux distro other than NixOS. it don't make sense that this users go to NixOS page...

![Screenshot from 2020-03-16 23-49-39](https://user-images.githubusercontent.com/91113/76806177-048eee80-67e1-11ea-86d9-63c5243f87a4.png)

(thanks for cleaning up the issues btw :+1:)
