### ISSUE TITLE
redirect /nixpkgs to github

### ISSUE THREAD

**Issue by raboof** [NixOS/nixos-homepage#567]
I see https://nixos.org/nixpkgs no longer exists, and https://nixos.org links to github for the nixpkgs.

That seems reasonable, but for old links we should perhaps redirect users from https://nixos.org/nixpkgs to github as well.

**Comment by garbas** [comment]
@raboof I not sure I understand this issue, please help me. Where did you see https://nixos.org/nixpkgs link being used?

Currently https://nixos.org/nixpkgs redirects to https://nixos.org since we decided to talk about all three projects (Nix/Nixpkgs/NixOS) as one story.

**Comment by raboof** [comment]
I don't remember :/ .

I like the new landing page, but I'd say people who link specifically to https://nixos.org/nixpkgs want to point people specifically to nixpkgs, so in that case the generic homepage is not great.

Anyway, I'll close this until I find a compelling example I guess.
