### ISSUE TITLE
build instructions outdated?

### ISSUE THREAD

**Issue by raboof** [NixOS/nixos-homepage#569]
When I follow the build instructions from the README, 'make' indeed appears to build things, but running 'caddy' just shows the caddy help. 'caddy run' starts on port 2019 rather than 8000, and produces a 404 there.

Just looking at the generated 'plain' html pages is good enough for simple changes, but for more complicated contributions I'd like to be able to see it with all CSS applied correctly :)

(this is on nixos-unstable)

**Comment by garbas** [comment]
@raboof Good catch. let me fix the README asap.
