### ISSUE TITLE
Add possibility to link to packages

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixos-homepage#57]
More and more projects link to their packages on `github/nixos/nixpkgs` - it would be nice (in manner of user experience) to link to the package on `nixos.org/nixos/packages`. Currently this is not possible.

A simple solution would be to pass the search term via HTTP GET, I think. I would file the PR for this myself, though I'm by no means a JS guy, so I guess I'll struggle hard to accomplish this.

**Comment by bjornfor** [comment]
+1. Achlinux already has this, ex. this random package: https://aur.archlinux.org/packages/microscheme/. With NixOS I have to manually enter a search term into http://nixos.org/nixos/packages.html. But I want a _link_, so that I can pass it around :-)

**Comment by davidak** [comment]
duplicate of https://github.com/NixOS/nixos-homepage/issues/23

**Comment by davidak** [comment]
You can now get a Permalink: https://nixos.org/nixos/packages.html?attr=pipenv&channel=nixos-19.03&query=pipenv

**Comment by samueldr** [comment]
You can drop the channel name and/or the query from the package name to get a more permanent permalink that links to whatever the default channel is. The important bit is the `attr` argument.

 * https://nixos.org/nixos/packages.html?attr=pipenv
