### ISSUE TITLE
Get a link to a manual section

### ISSUE THREAD

**Issue by sindikat** [NixOS/nixos-homepage#58]
In [Python docs] if you see a section heading, you move your mouse pointer to it and link “¶” appears. If you press on it, your browser's address bar now contains full link to that section. Compare:

- https://docs.python.org/2/library/stdtypes.html
- https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex

Is it possible to create such convenience links in Nix and NixOS manuals? This would improve manual UX and make easier to link to specific portions of the manual.

**Comment by domenkozar** [comment]
This is now implemented in https://github.com/NixOS/nixos-homepage/commit/e0a1c8b548611fc67412b9fa7c719949753b35ef
