### ISSUE TITLE
Nixpkgs manual has too much padding

### ISSUE THREAD

**Issue by berbiche** [NixOS/nixos-homepage#580]
The new website looks really great but the documentation now suffers from having too much whitespace/padding.

#### Screenshot taken on a 32:10 1200p monitor
![image](https://user-images.githubusercontent.com/20448408/94209624-bb5bdd80-fe9a-11ea-9836-c5bdfb0001a5.png)

I don't always remember the definition of functions available in `lib` so I sometimes need to refresh my brain.
1. With the new website, I can see at most two functions in my viewport.
2. The space between each section is too wide (there is a trailing `<br>` with a line-height of ~30 pixels + margin-top of the next section)

**Comment by piegamesde** [comment]
That's funny, because on my system there's absolutely no padding:

![image](https://user-images.githubusercontent.com/14054505/96308119-1056c380-1003-11eb-905e-8d392504b709.png)

(Chromium only, Firefox is fine though)

**Comment by piegamesde** [comment]
Ah, I see. You mean that the line spacing is way too large for you? Okay, I'll open a separate issue then.

**Comment by berbiche** [comment]
Doesn't bother me anymore.

Feel free to reopen.
