### ISSUE TITLE
Link to https://broken.sh/

### ISSUE THREAD

**Issue by nixinator** [NixOS/nixos-homepage#604]
Should there be a link to ultra useful https://broken.sh/

on the security resources section of 

https://nixos.org/teams/security.html

?

**Comment by davidak** [comment]
It don't look very good, so maybe not?

It seems more like an internal tool. But we should make it more accessible for the maintainers.

Maybe post the link on the discourse https://discourse.nixos.org/c/dev/security/21

**Comment by garbas** [comment]
@nixinator The content of the team page is up to the team (except of the standard elements: members, etc..). Please reach out to the security team as @davidak suggested and then open a PR with a change and a link pointing to the discussion.
