### ISSUE TITLE
asciinema syntax highlighting (bat -n)

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixos-homepage#611]
> I think that the asciinema videos are fantastic. [...]
> They might benefit from some shell syntax highlighting & the use of bat -n in place of cat -n as I think the highlighting will make the nix a lot more approachable (can always have it aliased to avoid confusing people who haven’t heard of bat)

Courtesy of @06kellyjac from [discourse](https://discourse.nixos.org/t/new-nixos-org-design/9080/30?u=blaggacao).

**Comment by garbas** [comment]
We were actually using `bat` initially can we switched to `cat` since people are not familiar with `bat` and were confused.

**Comment by 06kellyjac** [comment]
> (can always have it aliased to avoid confusing people who haven’t heard of bat)

The point is colour from shell syntax highlighting and bat would make the asciinema easier to read and understand
