### ISSUE TITLE
EC2 Launch Buttons are Broken

### ISSUE THREAD

**Issue by endgame** [NixOS/nixos-homepage#623]
**Introduce your stance**
I often use the NixOS download page https://nixos.org/download.html#nixos-amazon to launch EC2 image.

**Describe the issue**
The launch button generates a launch link to (e.g.)
```
https://console.aws.amazon.com/ec2/home?region=download-amazon-ap-southeast-2#launchAmi=ami-04c0f3a75f63daddd
```
It should be (no `download-amazon-`):
```
https://console.aws.amazon.com/ec2/home?region=ap-southeast-2#launchAmi=ami-04c0f3a75f63daddd
```

**Page links**
https://nixos.org/download.html#nixos-amazon

**Comment by samueldr** [comment]
Can you confirm that #624 indeed fixes this issue?

Link here:

 * https://5f8e67529807aa933fcc4279--nixos-homepage.netlify.app/download.html#nixos-amazon

**Comment by endgame** [comment]
I believe this fixes it - I get taken to the EC2 launch wizard where before I got an AWS error page.
