### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by zaari** [NixOS/nixos-homepage#638]
**Introduce your stance**
The news page doesn't have [RSS](https://en.wikipedia.org/wiki/RSS) or [Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) feed.

**Describe the issue**
It would make it easier to follow NixOS related news if there was a feed available on the news page.

**Page links**
https://nixos.org/news.html

**Comment by skmd0** [comment]
Seems like there is a RSS feed, but there is no link available from the website. [https://nixos.org/news-rss.xml](https://nixos.org/news-rss.xml)
It would be great if this was easily accessible from the page UI.

**Comment by zaari** [comment]
That's a good find. It would be also nice if there was an HTML tag for news aggregators.

`<link rel="alternate" type="application/rss+xml" title="(TITLE)" href="(FEED-URL)" />`

**Comment by garbas** [comment]
Thank you for reporting the bug.

The updated news/blog will soon change quite a lot and the RSS will be part of it (#446).

I'm going to close this issue to not have duplicate issues, but consider that this is going to happen until next NixOS release. If you wish to help with getting this done sooner I would really appreciate it. But lets discuss this under #446 .
