### ISSUE TITLE
Dead Link for Boehm Garbage Collector

### ISSUE THREAD

**Issue by NomAnor** [NixOS/nixos-homepage#66]
In section 5.1 Prerequisites the link for the Boehm Garbage Collector
> http://www.hpl.hp.com/personal/Hans_Boehm/gc/

is not working. Looking at Wikipedia the official site seems to be
> http://www.hboehm.info/gc/

**Comment by davidak** [comment]
the source for that is in the nix repo where i created an issue already. https://github.com/NixOS/nix/issues/727

will fix it now.

**Comment by domenkozar** [comment]
It's fixed now: http://nixos.org/nix/manual/#sec-prerequisites-source
