### ISSUE TITLE
Double clicking in the copyright text causes some sort of outline overylay to pop up

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixos-homepage#661]
**Describe the glitch**
A clear and concise description of what the design glitch is.

**Screenshots**
Please provide screenshots that show your observation. Annotating them is a plus.

![image](https://user-images.githubusercontent.com/18599032/102963336-18dae700-44e9-11eb-9515-a27c3f9cf6a6.png)

The `lg` is in the top left of the current screen

**Additional context**

**Comment by garbas** [comment]
@Atemu you just discovered our debug tool :) double click on it again to hide it.

**Comment by roberth** [comment]
I've been annoyed by these ugly lines for like a month now. I don't remember doing anything to cause this.

**Comment by roberth** [comment]
Perhaps it could set a date until which debug mode is activated?

**Comment by garbas** [comment]
Yes this is done when you double click on the Nix logo in the footer. Double click again to disable it.

**Comment by roberth** [comment]
How is an average visitor going to find out though? I'm crazy enough to dig into it and find this issue, but we shouldn't expect visitors to do so.
