### ISSUE TITLE
Unclear nix channel instructions

### ISSUE THREAD

**Issue by spease** [NixOS/nixos-homepage#664]
**Introduce your stance**
Out of date information on website

**Describe the issue**
https://nixos.wiki/wiki/Nix_channels directs you to https://nixos.org/channels/nixpkgs-unstable

https://nixos.org/channels/nixpkgs-unstable seems to go to a pre-21.03 release, which is sorely out of date

According to that URL's header:
"nixos-unstable release nixos-21.03pre260232.733e537a8ad"

The clue was that postgrest was marked broken, and when I reported it I was told this was fixed some time ago. Ticket where this came up:
https://github.com/PostgREST/postgrest/issues/1718

**Page links**
https://nixos.wiki/wiki/Nix_channels

**Additional context**
What URL do I need to use for rolling updates to nixpkgs?

- [ ] I already created a Pull Request

**Comment by grahamc** [comment]
21.03 is 3 months from now, though?

**Comment by spease** [comment]
Damn, you're right. I glossed over the year. Guess I'm just too eager to get to 2021. OK, if this is still correct advice, this may still be an issue with postgrest. It looks like the version that installed (7.0.0) is slightly older than the one marked as broken (7.0.1) so this checks out. Sorry for wasting your time.
