### ISSUE TITLE
Commercial support page: logos are "squished"

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixos-homepage#681]
**Describe the glitch**
The square logo images on the [commercial support page](https://nixos.org/community/commercial-support.html) are squashed into a slightly-wider-than-square rectangular box, distorting them.

**Screenshots**

GitHub isn't letting me upload them…

**Additional context**

none

**Comment by garbas** [comment]
@lheckemann Can you provide also the browser you are using (and possibly the version of that browser)? Screenshot would help a lot as well if you can upload it somewhere else then github.

**Comment by samueldr** [comment]
![Uploading image.png…]()

**Comment by lheckemann** [comment]
This happens in larger sizes as well, though less extremely:
Firefox:
![2021-04-06-130159_screenshot](https://user-images.githubusercontent.com/341954/113701456-77af1f80-96d8-11eb-9cf0-c63dd966fd0c.png)
Chromium:
![2021-04-06-130234_screenshot](https://user-images.githubusercontent.com/341954/113701449-767df280-96d8-11eb-871e-9ba41abaff28.png)

**Comment by kacperwyczawski** [comment]
I think that this has already been fixed, because I can't reproduce the bug on firefox
