### ISSUE TITLE
Dead link in documantation at "54.1. Writing Tests"

### ISSUE THREAD

**Issue by nichmoe** [NixOS/nixos-homepage#689]
**Introduce your stance**
I'm trying to understand nixos tests to be able to write my own.

**Describe the issue**
In the linked part of the documentation, after the example code, the documentation references and links two tests as examples. These test show how to specify the use of one VM and of multiple VMs. 
The linked example for a test using multiple VMs is nfs.nix . But nfs.nix does not exist anymore, so the link is dead. 
Its now split into multiple files and is located in the nfs subfolder. 

**Page links**
https://nixos.org/manual/nixos/stable/index.html#sec-writing-nixos-tests

**Additional context**
Currently I'm not familiar enought with nixos tests to make the edit myself, as it would require some understanding to choose a good new example.

**Comment by fricklerhandwerk** [comment]
@nichmoe this issue should be directed towards https://github.com/NixOS/nix where the manual is maintained.

**Comment by timfenney** [comment]
The manual links look fine to me now.
@nichmoe @fricklerhandwerk can this be closed?

**Comment by fricklerhandwerk** [comment]
@timfenney thanks for checking issue validity!
