### ISSUE TITLE
[DOCUMENTATION] Add paged support for project documentation

### ISSUE THREAD

**Issue by enderger** [NixOS/nixos-homepage#691]
**Describe the glitch**
The Nix documentation pages are near-enough impossible to navigate properly for 2 reasons:
1. The site loads as slow as molasses, owing to it's massive size
2. The only available versions of the Nix manuals are single page, and in places don't provide enough access to nested subsections (especially the Nix Language reference).

**Screenshots**
See any of the documentation pages, it should be immediately obvious

**Additional context**
I have found this particularly annoying when trying to build a project on top of the Nix expression language, as the reference has no table of contents that goes deep enough to find anything quickly.

**Comment by samueldr** [comment]
Good news: it's already part of the consideration for the updated documentation.

It's mainly blocking on a proper tooling for the Nixpkgs and especially NixOS documentation upstream at Nixpkgs, which hopefully https://github.com/NixOS/nixpkgs/pull/108063 is the solution for.
