### ISSUE TITLE
One-way bridging IRC > Matrix

### ISSUE THREAD

**Issue by nesnera** [NixOS/nixos-homepage#696]
**Introduce your stance**
Matrix user

**Describe the issue**
Content created in Matrix does not appear in IRC. Very confusing and frustrating :woozy_face: 
- open a Matrix room e.g. [#nixos-aarch64](https://matrix.to/#/!ACOPNtJclKAfOLQCKK:matrix.org?via=matrix.org&via=kernelpanic.cafe&via=ruhr-uni-bochum.de)
- write and send a message
- check if it appears in the [IRC log](https://logs.nix.samueldr.com/nixos-aarch64) 

**Additional context**
I have verified in another room that the bridging works in both directions (IRC <> Matrix).

**Comment by mweinelt** [comment]
I cannot confirm this issue. I just joined `#nixos-aarch64:matrix.org` and the bridge goes both-ways.

### Matrix
![image](https://user-images.githubusercontent.com/131599/114110473-da223e80-98d7-11eb-92c0-751248670e82.png)

### IRC
![20210409_02h05m20s_grim](https://user-images.githubusercontent.com/131599/114110551-1190eb00-98d8-11eb-88de-b82b815f2608.png)

**Comment by garbas** [comment]
I'm not sure how is this related to nixos.org website.

**Comment by nesnera** [comment]
I stopped using IRC, so I don't know if the issue persists.

However, I find it frustrating to close the issue because of "not related" without a suggestion where to transparently address it.

**Comment by garbas** [comment]
@nesnera I also have no idea, but I would start with the infra team channel on matrix
