### ISSUE TITLE
Nix Channel Status outdated?

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#699]
https://status.nixos.org/ says _nixos-unstable_ was last updated 2 days ago, but hydra says 1 hour ago. Which is correct and why is it different?

https://hydra.nixos.org/job/nixos/trunk-combined/tested

![Screenshot from 2021-04-21 23-11-41](https://user-images.githubusercontent.com/91113/115621866-629cd800-a2f7-11eb-8e62-697ad23bc75f.png)

**Comment by grahamc** [comment]
Did you check out the link at the top:

> See the NixOS Wiki for information on how channel updates progress. 

for information about how that works?

**Comment by lukegb** [comment]
Yeah, this has been broken for a few days now. Basically, there's an ongoing problem following an update to the server which takes the completed Hydra evaluation and updates the nixos-unstable channel.

I filed https://github.com/NixOS/nixpkgs/issues/120120 to track this.

**Comment by vcunat** [comment]
Why is it different?  First, the channel needs to wait for all builds/binaries and not just the tested job.  Second, the time-stamp definition on status.nixos.org perhaps could be improved: https://github.com/NixOS/nixos-status/issues/7#issuecomment-756146485

**Comment by wamserma** [comment]
Picking up on this, 21.05 seems to be stuck at https://github.com/NixOS/nixpkgs/commit/63ee5cd99a2e193d5e4c879feb9683ddec23fa03 while e.g. small has properly advanced. Looking at the tested and channel jobs (https://hydra.nixos.org/job/nixos/release-21.05/nixos.channel) I expected the channel to advance, so the block might be in some of the preparatory steps listed in the Wiki. Maybe we could enrich the status page and use the Channel Status column to show some information on how the channel update is proceeding (e.g. "populating cache" or "xx builds left" or sth. like that.

**Comment by vcunat** [comment]
That build hasn't finished yet.  I just cancelled it for a while to unblock the channel, as it was building for more than a day and the log hasn't advanced by a single line in at least an hour.  (Hydra apparently kept it going and later just "resumed" the status without really cancelling the build.)

**Comment by vcunat** [comment]
Anyway, this particular thread would better get closed.  (but I don't have permissions for that)
