### ISSUE TITLE
wrong link for nix expression

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#70]
search for `git-crypt` on http://nixos.org/nixos/packages.html

`Nix expression:	pkgs/applications/version-management/git-and-tools/git-crypt/default.nix`

but the link is https://github.com/NixOS/nixpkgs/blob/release-15.09/default.nix#L23

the file is actually at the path from nix expression.

**Comment by copumpkin** [comment]
:+1:  lots of packages have that bad link

**Comment by edolstra** [comment]
Wasn't this fixed by c8b83b07c9cccc890cfeb769e6ecc273bdad59a4?

**Comment by copumpkin** [comment]
Oh yes, so it was. You're on top of it!

**Comment by domenkozar** [comment]
Works now.
