### ISSUE TITLE
Show enum values on Options page

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixos-homepage#71]
Some options, like `permitRootLogin`, [specify a number of valid options](https://github.com/NixOS/nixpkgs/blob/release-15.09/nixos/modules/services/networking/ssh/sshd.nix#L104).

It'd probably be nice to show those valid options on the [Options page](https://nixos.org/nixos/options.html) as well, when expanding an entry. Including descriptions of each option would be even nicer, but as those are not currently defined in the `.nix` files, that might be out of scope for this issue.

**Comment by naomik** [comment]
:+1: my feelings exactly

**Comment by d3xter** [comment]
Bump

Ran into this when trying to set permitRootLogin. Had to check the source to find the possible values.

**Comment by garbas** [comment]
this is now fixed
