### ISSUE TITLE
Link to Matrix rooms

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-homepage#710]
https://nixos.org/community/index.html still refers to #nixos on freenode, which [we're moving away from](https://discourse.nixos.org/t/join-us-on-matrix-at-nix-nixos-org-migrating-from-freenode/13166/20). We should update it to point to our Matrix rooms / space.

**Comment by samueldr** [comment]
Done #714 and #715 (thanks!)

**Comment by felschr** [comment]
https://nixos.org/guides/contributing.html still references the freenode channel.

But it seems that `guides/contributing.tt` doesn't exist anymore, so I'm not sure where that's defined.
