### ISSUE TITLE
RSS Feed gone

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixos-homepage#725]
**Introduce your stance**

I had the release announcements in my RSS reader and since the site got redesigned, the URL 404s.

**Describe the issue**

There does not seem to be any RSS feed anymore.

**Page links**

https://nixos.org/blog/announcements.html I guess

**Additional context**

- [ ] I already created a Pull Request

**Comment by jtojnar** [comment]
The page has https://nixos.org/blog/announcements-rss.xml as `link[rel=alternate]` which seems to work.

**Comment by garbas** [comment]
yes @jtojnar provided the correct url.
