### ISSUE TITLE
Blog post names should be in the titles

### ISSUE THREAD

**Issue by busti** [NixOS/nixos-homepage#727]
**Introduce your stance**
Searching for pills on search engines like DuckDuckGo is rather hard since they are all titled the same, but searches often contain multiple pills in their results.

**Describe the issue**
The names in the search engine are all the same since the blog article names are not in the title of the corresponding webpage. It just says "NixOS - Nix Pills"

**Page links**
https://nixos.org/guides/nix-pills/why-you-should-give-it-a-try.html  
https://nixos.org/guides/nix-pills/install-on-your-running-system.html
and so on...

**Comment by timfenney** [comment]
That's interesting.
There is also the Document "description" meta tag required by Google for good SEO.
In the end you could have something like:
title: Nix Pill # 29: The Home Directory
description: Nix makes managing Dotfiles a breeze

**Comment by timfenney** [comment]
@fricklerhandwerk

**Comment by fricklerhandwerk** [comment]
SEO is not great currently, yes. Feel free to propose changes in pull requests. Just make sure to coordinate with @lucperkins who is working on a rewrite.
