### ISSUE TITLE
discourse.nixos.org now pointing at ClearLinuxOS forum

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixos-homepage#730]
Earlier this morning, [discourse.nixos.org](https://discourse.nixos.org/) was down when I tried to load it.  Now it loads the [ClearLinuxOS](https://github.com/ClearLinuxOS) forum.  

Also when I try to log in to [discourse.nixos.org](https://discourse.nixos.org/) using my Github account, Github tries to authorize me for the ClearLinuxOS discourse forum too.

Seems discourse may be having some technical issues.

I assume the NixOS team is already aware, but reporting it anyway just in case.

**Page links**
https://discourse.nixos.org/

**Comment by edolstra** [comment]
I don't know what happened, but it seems to be fine now.
