### ISSUE TITLE
DOCS: Incomplete set of S3 actions in policy example for successful READs

### ISSUE THREAD

**Issue by avanov** [NixOS/nixos-homepage#731]
**Introduce your stance**
Nix user

**Describe the issue**
[The current example of a S3 access policy](https://nixos.org/manual/nix/unstable/package-management/s3-substituter.html#anonymous-reads-to-your-s3-compatible-binary-cache) for a S3 binary cache READ operations is incomplete - it is missing `"s3:ListBucket"` action. Whilst the current config is enough for basic nix-shell substitutions, without `"s3:ListBucket"` action a user would see this kind of error when running `nix-build`:
```
error: AWS error fetching '7fk9b9w8bpkkm36glg378l4arczk85sw.narinfo': Access Denied
```

So the complete list of actions for reads shlould be this:
```
"s3:GetObject",
"s3:GetBucketLocation",
"s3:ListBucket"
```

**Page links**
* https://nixos.org/manual/nix/unstable/package-management/s3-substituter.html#anonymous-reads-to-your-s3-compatible-binary-cache

**Additional context**
none

- [ ] I already created a Pull Request

**Comment by fricklerhandwerk** [comment]
@avanov This issue should be directed at https://github.com/NixOS/nix, where the manual is maintained.

**Comment by avanov** [comment]
@timfenney I'm fine with closing it here, thanks!
