### ISSUE TITLE
broken link "Follow the contribution guidelines."

### ISSUE THREAD

**Issue by jkarlson** [NixOS/nixos-homepage#736]
**Introduce your stance**
Make it clear under what perspective are you reporting and what is your motivation.

user reading website

**Describe the issue**
A clear and concise description of what the issue is about.

link broken

**Page links**
Please enumerate the page links where to observe the issue.

https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes

"Follow the contribution guidelines." link
https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes
needs to have substring ".github" removed
 https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

**Additional context**

- [ ] I already created a Pull Request

**Comment by rski** [comment]
one sec, i'll prep a pr for this

**Comment by jkarlson** [comment]
The issue has been fixed, I see.
