### ISSUE TITLE
Installing Nix 1.2 from https://releases.nixos.org/nix/nix-2.2/install leads to error.

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixos-homepage#742]
I'm opening this issue as suggested by @domenkozar in cachix/install-nix-action#99.
I tried to install Nix 1.2 in CI (using install-nix-action) by relying on the URL: https://releases.nixos.org/nix/nix-2.2/install
However, it fails with the following error:

```
/dev/fd/63: SHA-256 hash mismatch in 'https://nixos.org/releases/nix/nix-2.2/nix-2.2-x86_64-darwin.tar.bz2';
expected sha256-1zRgN1HUvaA+FJjOLSVlLv5+f9bdHBbBVKTBYTpSj68=,
got d734603751d4bda03e1498ce2d25652efe7e7fd6dd1c16c154a4c1613a528faf
```

**Comment by garbas** [comment]
I think you need to manually fix those install scripts. I assume some hashes changes. If you do fix it, please let me know and I'll make sure we update it.
