### ISSUE TITLE
Include non-English Communities to community page

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixos-homepage#743]
Nix non-English Communities are thriving
- It is easier to get low-middle level support at local communities than global.
- No language barrier.
- More helpful members by matching culture (social cues being more correct). 
- Communication platform matching local preference.

In Brazil, for example, the most active community is at Telegram. Which is not listed. It currently has 108 members.

Telegram - NixOS Brasil (language: portuguese): https://t.me/nixosbrasil
(managed by @jnetod)

The community page ( https://nixos.org/community/index.html ) should be updated to include non-English speaking communities.

- [ ] I already created a Pull Request

**Comment by garbas** [comment]
@superherointj The PR for this would be more than welcome.
