### ISSUE TITLE
Download page: Minimal 64-bit ISO doesn't match the sha256 checksum file

### ISSUE THREAD

**Issue by Necior** [NixOS/nixos-homepage#745]
**Introduce your stance**
As of now, when you download 64-bit ISO from https://nixos.org/download.html it doesn't match the checksum file.

**Describe the issue**
Currently the Minimal 64-bit ISO image links to `https://channels.nixos.org/nixos-21.05/latest-nixos-minimal-x86_64-linux.iso` which redirects to `https://releases.nixos.org/nixos/21.05/nixos-21.05.3468.92609f3d9bc/nixos-minimal-21.05.3468.92609f3d9bc-x86_64-linux.iso`.

That ISO's sha256 checksum is `93daa40d8e8f2ea9c088af60ff069b70f4fec8e30ff9a4a8dd339784e27daf7f`.

Provided on the page checksum file points to `https://channels.nixos.org/nixos-21.05/latest-nixos-minimal-x86_64-linux.iso.sha256` in which there is a different ISO (`nixos-minimal-21.05.3509.7daf35532d2-x86_64-linux.iso`) with a different checksum: `4d49a5441f71ec92a3743bb1091e046cd5d989d8d8f45b865c36c55799b9f3c3`.

**Page links**
- https://nixos.org/download.html

**Comment by Necior** [comment]
Slightly related: https://github.com/NixOS/nixos-homepage/issues/420.

**Comment by xbreak** [comment]
Same with GNOME version.

ISO link on download page
- https://channels.nixos.org/nixos-21.05/latest-nixos-gnome-x86_64-linux.iso is currently resolved to nixos-gnome-21.05.**3509.7daf35532d2**-x86_64-linux

whereas SHA-256 link 

- https://channels.nixos.org/nixos-21.05/latest-nixos-gnome-x86_64-linux.iso.sha256 is currently resolved to nixos-gnome-21.05.**3468.92609f3d9bc**-x86_64-linux.iso.sha256:
> 607241b27cae583b1d515c81dc90f3ead347b0b0a066b64282841acae0367021  nixos-gnome-21.05.3468.92609f3d9bc-x86_64-linux.iso

with a SHA-256 mismatch as a result.

**Comment by garbas** [comment]
I believe this is fixed now. Please reopen if this is not the case.
