### ISSUE TITLE
Advertise aarch64 installer image

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixos-homepage#747]
**Introduce your stance**
Aarch64 is an important architecture for NixOS and should receive better advertisement on the download page.

**Describe the issue**
The aarch64 installer image is missing from the download page. They are available on hydra, but otherwise hard to find.

**Page links**
https://nixos.org/download.html

**Additional context**
https://nixos.wiki/wiki/NixOS_on_ARM/UEFI#Getting_the_installer_image

- [ ] I already created a Pull Request

**Comment by garbas** [comment]
@mweinelt I would love to add the aarch64 images to the download page, but as far as I can tell aarch64 need to become part of the release job on hydra. Then `nixos-channels-scripts` needs to be updated and after that we can add it to the website.

For now I'm going to close this issue but I hope we will soon reopen it with a PR once all the work has been done.
