### ISSUE TITLE
Content: update Packet logo to Equinix Metal

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixos-homepage#754]
**Introduce your stance**

Packet has been renamed as Equinix Metal after an acquisition, and the
public web site should reflect that.

**Describe the issue**

The donate page at the following span

https://github.com/NixOS/nixos-homepage/blob/master/donate.tt#L119-L123 

references packet.com instead of metal.equinix.com, and the logo is the old logo.

**Page links**

https://nixos.org/donate.html

**Additional context**

A new logo will be needed as well

- [ ] I already created a Pull Request
- [ ] get approval for a new logo
- [ ] make changes to the link text

**Comment by samueldr** [comment]
Don't forget to delete the packet logo from the repo, once you have the replacement svg file :).
