### ISSUE TITLE
Broken links on Learn page

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixos-homepage#756]
**Introduce your stance**
N/A

**Describe the issue**
The 'quick links' to Nix manual sections on the Learn page are broken; they still assume the old single-page manual structure, and link to anchors rather than pages.

**Page links**
- https://nixos.org/learn.html

**Additional context**
N/A

- [ ] I already created a Pull Request

**Comment by Alejandro-Villa** [comment]
Not only the quick links are broken, also all the "Guides" section is broken. Right now the whole "Learn" section is unusable. I'm not very familiar with the infrastructure this is built with or where the files with the guides/information went, so I can't submit PR.

![2021-12-01-165205_1283x896_scrot](https://user-images.githubusercontent.com/43407560/144267285-eb116728-906a-4301-b76f-8dfca4c9b352.png)

**Comment by jtojnar** [comment]
The manual links should be fixed by https://github.com/NixOS/nixos-homepage/pull/761
