### ISSUE TITLE
Amazon EC2 region selection broken on download page

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixos-homepage#767]
**Introduce your stance**
N/A

**Describe the issue**
The "Choose region:" region dropdown on the Amzon EC2 section of the download page is broken: no options are visible or selectable. Consequently there is no  Root storage/Virtualisation/AMI information displayed.

**Page links**
https://nixos.org/download.html#nixos-amazon

**Additional context**
This worked a few days ago, so could have been broken by the 21.11 updates?

- [ ] I already created a Pull Request

**Comment by garbas** [comment]
This is now fixed. It takes some time (~day) so this options are updated.
