### ISSUE TITLE
Learn page guides are borked

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixos-homepage#768]
**Describe the glitch**
A clear and concise description of what the design glitch is.

Titles are invisible and buttons are squashed.

**Screenshots**
Please provide screenshots that show your observation. Annotating them is a plus.

![image](https://user-images.githubusercontent.com/18599032/144586994-50f78d79-770c-4f94-8b8f-b5c06995b03f.png)

**Additional context**

```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
```

**Comment by mou** [comment]
Can confirm. Also clicking on guide links (without text) lands on a page without content.

**Comment by mou** [comment]
Can not figure out the alternative location of such content. Want to learn details about Nix to adopt it, but fail due to broken guide section

**Comment by domenkozar** [comment]
All content comes from https://nix.dev

**Comment by mou** [comment]
@domenkozar thanks. these guides are awesome and helpful.

**Comment by Atemu** [comment]
Thanks!
