### ISSUE TITLE
Duplicate guide titles

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixos-homepage#792]
**Describe the glitch**
At https://nixos.org/learn.html, all guide titles are duplicated.

**Screenshots**

![image](https://user-images.githubusercontent.com/1663259/151679914-91b2299d-3c93-42aa-a5b1-eb4bed55dced.png)

**Additional context**
n/a

**Comment by garbas** [comment]
@joepie91 Thank you for opening the ticket!
