### ISSUE TITLE
Link not found `tutorials/install-nix.html`

### ISSUE THREAD

**Issue by Anindya-Prithvi** [NixOS/nixos-homepage#796]
When you view https://nixos.org/guides/ad-hoc-developer-environments.html , there is a direct link to https://nixos.org/guides/install-nix.html#install-nix labelled as: **Nix installed**. However the link is broken. I found that:
- The script which is supposed to copy all tutorials [copy-nix-dev-tutorials](https://github.com/NixOS/nixos-homepage/blob/master/scripts/copy-nix-dev-tutorials.sh) deliberately commented out the `install-nix` page (ref: [here](https://github.com/NixOS/nixos-homepage/blob/master/scripts/copy-nix-dev-tutorials.sh#L6))
- And on the nix-dev repository, `install-nix` still [exists](https://github.com/nix-dot-dev/nix.dev/search?q=%3Cinstall-nix%3E) 

**Screenshots**
---
![image](https://user-images.githubusercontent.com/29653551/152185145-8d832a6c-c3b9-4d11-8a63-cbfacd31beb1.png)
---
![image](https://user-images.githubusercontent.com/29653551/152185223-cedf2694-9819-4312-b3ce-035261ff04ff.png)
---
![image](https://user-images.githubusercontent.com/29653551/152186232-b5ca1adc-0e1a-403d-916e-c03c679013c0.png)
---

**Additional context**
I am new to nix and I was just looking.

---
Do tell me if I can submit a patch OR modify nix-dev in someway to not depend on it

**Comment by garbas** [comment]
@Anindya-Prithvi thank you for reporting.   I think I've missed this part when I was updating the downloads page.
