### ISSUE TITLE
Link to Nixpkgs (unstable) manual is broken

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixos-homepage#80]
The link to the latest version of the manual on 
http://nixos.org/nixpkgs/download.html
is broken.

The link http://hydra.nixos.org/job/nixpkgs/trunk/tarball/latest/download-by-type/doc/manual
should probably be replaced with
http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest

**Comment by domenkozar** [comment]
This depends on https://github.com/NixOS/hydra/issues/321

**Comment by davidak** [comment]
The linked hydra issue is fixed, but the link is still broken.

**Comment by davidak** [comment]
Still reproducible.

Who would be able to fix it? Can that person get pinged?
