### ISSUE TITLE
The Instructions for Installing an Unstable Package in the FAQ Do Not Work

### ISSUE THREAD

**Issue by MetalNeo** [NixOS/nixos-homepage#820]
**Introduce your stance**
I am a new user trying to install a package that is only available in the Unstable channel.

**Describe the issue**
I was unable to install the package using the instructions from the FAQ. I kept receiving errors over my use of let in `configuration.nix`. However, the instructions provided by the Cheat Sheet link did work and allow me to install my wanted package. I believe the FAQ should be updated to more closely resemble the instructions in the Cheat Sheet page.

**Page links**
https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F
https://nixos.wiki/wiki/Cheatsheet#Customizing_Packages

- [ ] I already created a Pull Request

**Comment by cole-h** [comment]
FYI: `nixos.wiki` is unrelated to `nixos.org` (which this repository is for).

**Comment by MetalNeo** [comment]
My mistake. I'll make the edit some other time.
