### ISSUE TITLE
Broken URLs to manuals

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#829]
**Introduce your stance**
Changing the rendering from single page to multiple pages broke most historic links to the manuals. This should be corrected either by setting up proper redirects (sounds tedious) or by providing an alternative rendering as a single page. Otherwise we will lose pathways into the documentation which are all over the internet.

**Describe the issue**
https://github.com/NixOS/nix/issues/7259 is only one of many examples where URLs point to the first page of the manual instead of to referenced content.

**Additional context**
While this is a technical problem that will ultimately be solved in the [Nix repo](https://github.com/NixOS/nix/), the issue is still one of communication.

It is also not clear to me how exactly the manual is hosted, i.e. where the deployment code lives.

**Comment by garbas** [comment]
This will be rather hard thing to do with existing server side redirects (look at `netlify.toml`) since `#` parts are only visible on the client side. This would require some sort of frontend javascript to help us redirect.

**Comment by fricklerhandwerk** [comment]
Closed by https://github.com/NixOS/nix/pull/7006
