### ISSUE TITLE
Academic papers not visible on the website

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#830]
Quite some time ago the research papers on Nix and NixOS were removed from the website. 
- https://github.com/NixOS/nixos-homepage/commit/748c41d19350dbbf9f6f747d20df794bf2d43be1
- https://github.com/NixOS/nixos-homepage/commit/552a59b4031bf1a7fb896a0cad4faa35511eee39

@edolstra What was the reason was to do that, except academic papers being "scary"? Most essential things in them are still true, but most importantly they are the only material which explain motivation, rationale and architecture of Nix and NixOS.

This is only my personal anecdatum, but the theses were the central resource for me to understand what Nix is and why it is conceptually superior to anything else out there. Otherwise I would not have bothered to fight my way into making use of it. Here is [what the research section looked like](http://web.archive.org/web/20170705180623/http://nixos.org/docs/papers.html) when I started out.

On top of that it's part of the project's and community's history. I agree with https://github.com/NixOS/nixos-homepage/issues/446#issuecomment-697486801 that it should be kept accessible.

Maybe we can find a nice spot for the papers somewhere?

**Comment by sambacha** [comment]
> Quite some time ago the research papers on Nix and NixOS were removed from the website.
> 
> * [748c41d](https://github.com/NixOS/nixos-homepage/commit/748c41d19350dbbf9f6f747d20df794bf2d43be1)
> * [552a59b](https://github.com/NixOS/nixos-homepage/commit/552a59b4031bf1a7fb896a0cad4faa35511eee39)
> 
> @edolstra What was the reason was to do that, except academic papers being "scary"? Most essential things in them are still true, but most importantly they are the only material which explain motivation, rationale and architecture of Nix and NixOS.
> 
> This is only my personal anecdatum, but the theses were the central resource for me to understand what Nix is and why it is conceptually superior to anything else out there. Otherwise I would not have bothered to fight my way into making use of it. Here is [what the research section looked like](http://web.archive.org/web/20170705180623/http://nixos.org/docs/papers.html) when I started out.
> 
> On top of that it's part of the project's and community's history. I agree with [#446 (comment)](https://github.com/NixOS/nixos-homepage/issues/446#issuecomment-697486801) that it should be kept accessible.
> 
> Maybe we can find a nice spot for the papers somewhere?

Preach Brother [fricklerhandwerk](https://github.com/fricklerhandwerk), this is kind of important

**Comment by lorenzleutgeb** [comment]
For posterity, here's a list of [dblp](https://dblp.org/) keys (in the same order as they have been the on website):

```
journals/scp/BurgD14

# MISSING: https://web.archive.org/web/20170705180623/https://github.com/qknight/Multi-PlatformSoftwarePackageManagement/raw/master/Multi-PlatformSoftwarePackageManagement.pdf

conf/issre/BurgD10
journals/jfp/DolstraLP08

# MISSING: https://web.archive.org/web/20170705180623/https://nixos.org/~eelco/pubs/icse-cloud09-final.pdf

conf/hotswup/BurgDJ08
conf/icfp/DolstraL08
# MISSING: https://web.archive.org/web/20160323063939/http://nixos.org/~eelco/pubs/buildfarm-wasdett2008-final.pdf
journals/entcs/Dolstra09

conf/hotos/DolstraH07
# MISSING: https://pure.tue.nl/ws/files/2239914/628612.pdf#page=76

# MISSING: http://www.cs.uu.nl/education/scripties/scriptie.php?SID=INF/SCR-2005-091
phd/basesearch/Dolstra06

conf/kbse/Dolstra05
conf/scm/DolstraBV05
conf/cbse/Dolstra05

conf/lisa/DolstraJV04
conf/icse/DolstraVJ04

conf/scm/Dolstra03
```

**Comment by tomberek** [comment]
Done
