### ISSUE TITLE
`nix-shell` fails on Darwin

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#836]
```
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```

The reason seems to be that there are `x86_64-darwin` outputs (similar to [this issue](https://github.com/NixOS/hydra/issues/782)), as [`x86_64-linux` is hardcoded](https://github.com/NixOS/nixos-homepage/blob/9dd52648e95e0988dc607c739e69fa49c5ed38dd/flake.nix#L31).

Hotfixing this by replacing the `system` string still yields:

```
Package ‘xidel-0.9.8’ in /nix/store/57y6djpqdmjglkdzgrbsdyjzqkn48ff1-source/pkgs/tools/text/xidel/default.nix:87 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

Hacking `xidel` into evaluating on Darwin reveals

```
error: Package ‘fpc-3.2.0’ in /nix/store/74wznb06asq3sls1902fbkm7ibzyvk7m-nixpkgs-21.05pre296212.530a53dcbc9/nixpkgs/pkgs/development/compilers/fpc/default.nix:44 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

and this is a bit of a harder nut to crack, because the [fpc builder](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/fpc/binary-builder.sh) can only extract `tar`, but [fpc Darwin binaries are packaged as `dmg`](https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.2/).

Related: https://github.com/NixOS/nixpkgs/issues/108532

**Comment by garbas** [comment]
The current build tools used for nixos website don't work on MacOS, saddly. But when we select new one this will be one of the criteria.

There was some attempt to at least gave instructions how to build things with Docker on MacOS, but was abandoned due to lack of time -> #816
