### ISSUE TITLE
RSS feed pubDate fields have invalid format

### ISSUE THREAD

**Issue by Munksgaard** [NixOS/nixos-homepage#842]
The [RSS standard](https://www.rssboard.org/rss-specification#optionalChannelElements) specifies that `pubDate` should follow the [RFC 822](https://www.w3.org/Protocols/rfc822/) format. The nixos.org feeds currently use "UTC" as the time zone, but that zone is not strictly supported by RFC 822. Instead, I suggest using GMT, UT or +0000 as the time zone.

Example:

```
$ curl --silent  https://nixos.org/blog/announcements-rss.xml | grep pubDate | head -n 1
    </description><pubDate>Thu, 21 Apr 2022 18:00:00 UTC</pubDate><guid isPermaLink="false">Thu, 21 Apr 2022 18:00:00 UTC</guid></item><item><title>
```

**Comment by Munksgaard** [comment]
In fact, some of the months are also wrong. The following should read "Tue, 1 Mar 2022 18:00:00 GMT": https://github.com/NixOS/nixos-homepage/blob/b698f967b723403bfdb3b703475f96ce7adcc3d9/blog/announcements.xml#L201

**Comment by fud** [comment]
This looks correct now, I think this PR can be closed.

```
❯ curl --silent  https://nixos.org/blog/announcements-rss.xml | xmlstarlet sel -t -m '//pubDate' -v . -n | head -5
Fri, 31 May 2024 11:00:00 GMT
Wed, 29 Nov 2023 11:00:00 GMT
Wed, 31 May 2023 11:00:00 GMT
Thu, 01 Dec 2022 11:00:00 GMT
Mon, 30 May 2022 19:00:00 GMT
```

**Comment by Munksgaard** [comment]
It does indeed, thank you for pointing that out @fud!
