### ISSUE TITLE
Hourly update [ci skip] spamming the commits

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#854]
e.g. https://github.com/NixOS/nixos-homepage/commit/45a5e300664f0e3817d5fcad18feceec187a3b28

you can't find actual commits anymore

**Comment by fricklerhandwerk** [comment]
The logo shuffling should definitely be on the front-end. If possible we should prune the history, even if it breaks clones.

**Comment by drupol** [comment]
Indeed, I think the shuffling should be made in Javascript, on the front-end.

This would:

1. Prevent spamming the commit log with hourly updates
2. Foster eco-programming and spare energy

Am I the only one worrying about those details?

**Comment by JulienMalka** [comment]
I have always found this situation to be ridiculous, I am favorable to changing this.

**Comment by drupol** [comment]
I just submitted a PR to fix this, let me know what you think.

**Comment by drupol** [comment]
This issue is fixed, it can now be closed.
