### ISSUE TITLE
Commercial support: `nix develop` output rendered on web site

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#858]
**Describe the issue**
Due to how [reshuffling the company logos](https://github.com/NixOS/nixos-homepage/blob/02fd9cadfd4f82c80f52c32c12f55a0d49ef531e/scripts/update.sh#L15) works, the [output](https://github.com/NixOS/nixos-homepage/blob/02fd9cadfd4f82c80f52c32c12f55a0d49ef531e/flake.nix#L175-L183) the `shellHook`[ ends up on the web page](https://github.com/NixOS/nixos-homepage/blob/02fd9cadfd4f82c80f52c32c12f55a0d49ef531e/community/commercial-support.html.in#L2-L8).

**Page links**
https://nixos.org/community/commercial-support.html

**Additional context**
Shuffling should happen in the front-end. Related: https://github.com/NixOS/nixos-homepage/issues/854

**Comment by timfenney** [comment]
Can this be closed @fricklerhandwerk ? I don't see the content on the contributors page, and I can't find it in the dom.
