### ISSUE TITLE
Install script not working on RHEL anymore

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixos-homepage#86]
Since dc30713b1 the install script fails on `rhel` with:
```
you do not have 'shasum' installed, which I need to verify the binary tarball
```
On `rhel 7.2`, `shasum` is not available (at least not directly) but there are  `sha512sum` and cie.

**Comment by domenkozar** [comment]
@PierreR so you have `sha256sum`?

**Comment by domenkozar** [comment]
cc @edolstra, any reason not to use `sha512sum`?

**Comment by edolstra** [comment]
`sha512sum` doesn't exist on OS X.

**Comment by PierreR** [comment]
One way to make the script generic would be to check if `sha512sum` exists and resort to `shasum -a 512` if it doesn't.

This is described here:

https://github.com/silpion/ansible-java/pull/15

**Comment by copumpkin** [comment]
Or just call `openssl dgst`, which should be present on almost all systems (Mac OS and all Linuxes I've ever tried)

**Comment by copumpkin** [comment]
@edolstra great, thanks!
