### ISSUE TITLE
Merge `nixos-common-styles` repository

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#892]
You won't believe how hard it is to figure out how this website is constructed.

I only tried to make a small change by [replacing an image](https://github.com/NixOS/nixos-common-styles/pull/17), but it took an hour to find where it was defined. Turns out, it was in an entirely different repository, and all that stuff is wired up at compile time.

@garbas Is anything speaking against merging [`nixos-common-styles`](https://github.com/NixOS/nixos-common-styles) into this repository? There is only one website, and even if there were more, we can still serve it from one repository.

Related: https://github.com/NixOS/nixos-homepage/issues/833

**Comment by garbas** [comment]
The common section was refractored out of this repo since it is planned to be reused for search.nixos.org and status.nixos.org. Sadly the work paused, but I hope to revive it soon.

And yes, we should address the complexity of how everything works together.
