### ISSUE TITLE
The title prefix is `Nix -` for all pages

### ISSUE THREAD

**Issue by a-kenji** [NixOS/nixos-homepage#900]
## Problem
This is confusing and might mislead potential users.

This problem is especially confusing when searching for manuals:
![image](https://user-images.githubusercontent.com/65275785/191920488-5002b483-2d4a-4aee-8c2d-b10bbd4f6a63.png)

## Proposal
I suggest removing the prefix.

---
Co-authored-by: @mightyiam

**Comment by fricklerhandwerk** [comment]
It would be a bit of work replacing the page titles for all the regular pages to make sense in that case, e.g. „Learn Nix“ instead of „Nix - Learn“. Which would definitely be good to have, so I appreciate any pull request in that direction!

**Comment by mightyiam** [comment]
Thank you, @garbas .

**Comment by garbas** [comment]
@mightyiam Don't thank me. @fricklerhandwerk did all the work. I was more on the way than any help really :)
