### ISSUE TITLE
Invalid link on https://nixos.org/guides/ad-hoc-developer-environments.html

### ISSUE THREAD

**Issue by chuangzhu** [NixOS/nixos-homepage#921]
**Introduce your stance**

I saw a Nix beginner complaining about the invalid link on nixos.org.

**Describe the issue**

The [Nix language basics](https://nixos.org/guides/nix-language.html#reading-nix-language) link below the Next steps section on the page is invalid.

**Page links**

https://nixos.org/guides/ad-hoc-developer-environments.html

**Additional context**

This page is copied from https://nix.dev/tutorials/ad-hoc-developer-environments.html, so it can either be solved by also copying https://nix.dev/tutorials/nix-language to nixos.org, or point the link directly to nix.dev.

- [ ] I already created a Pull Request

**Comment by garbas** [comment]
This is now fixed
