### ISSUE TITLE
Rewrite the website so regular people can update contents

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-homepage#924]
**Introduce your stance**
It is annoying to update contents.

Concretely, community teams need a central place to maintain their workflow, and the website is no good place for this.

**Proposal**

Use a well-known, off-the-shelf static site generator which parses markdown.
Give team leads commit access, then all teams could even handle their entire workflow on this repository. That would make team activities more discoverable by construction.

@bryanhonof

**Comment by lucperkins** [comment]
As new docs team lead and seasoned veteran of static site generation, I'm happy to take this on.

**Comment by garbas** [comment]
Thank you for bringing this up. 

We've discussed this several times at the marketing meetings and we'll shortly published the roadmap (website improvements is part of it).

@lucperkins if possible can you join the next marketing meeting and we can see where you can help?

**Comment by lucperkins** [comment]
@garbas Yes, more than happy to. Feel free to invite me (email address on my account page), as I see from the website that marketing team meetings are ad hoc.

**Comment by timfenney** [comment]
What is the status on this puppy?

**Comment by timfenney** [comment]
@lucperkins ☝️

**Comment by lucperkins** [comment]
I've been slowly chipping away at this but it's been tricky to find the bandwidth. I'm good with static site generators and that part has been fine so far but I'm less awesome with CSS and that's been a slow go. I'll try to provide a report in the next meeting. There may perhaps be a solution involving a division of labor.

**Comment by tomberek** [comment]
An astro re-write has been done. This should make it easier to contribute. Feel free to re-open if desired.
