### ISSUE TITLE
https://search.nixos.org/packages: installation suggestions for libraries are incorrect

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixos-homepage#932]
**Introduce your stance**
As an expert user I notice a mistake on the search page which will teach new users something that is incorrect and will not function.

**Describe the issue**
The packages search page shows for each package how to install it with `nix-env`, in your NixOS configuration or with `nix-shell`. This method is correct for executables, however, it is incorrect for everything else, especially libraries. Users will not get the behavior they would expect from it.

**Page links**
Any package on https://search.nixos.org/packages.

**Additional context**
We should probably tag packages with whether they provide executables so the website can use that as input to decide whether to show this example or not.

Whether to show these examples is a trade-off. It is convenient for a novice user to see the line they need to use or add, however, they likely will make the mistake adding libraries and get surprised it does not give them the behaviour they seek.

- [ ] I already created a Pull Request

**Comment by yukiisbored** [comment]
https://search.nixos.org is maintained in this repository: https://github.com/NixOS/nixos-search

nixos-homepage only covers the https://nixos.org website.

**Comment by FRidh** [comment]
Thanks! I see it has been reported there as https://github.com/NixOS/nixos-search/issues/506.
