### ISSUE TITLE
Make the Mastodon link easier to find.

### ISSUE THREAD

**Issue by akavel** [NixOS/nixos-homepage#943]
**Introduce your stance**
I am a Mastodon user who tried to find a Mastodon account of NixOS, to help myself stay up to date with NixOS news, and occasionally re-share NixOS messaging from that account for others.

**Describe the issue**
I tried to find a link to an official Mastodon account related to Nix/NixOS. I looked at the bottom of the NixOS page, and there I saw two groups of social links:
 1. "Connect with us" - listing twitter, youtube and github;
 2. "Get in Touch" - listing forum, matrix and commercial support.

Neither of them listed a Mastodon presence, so I assumed Nix/NixOS does not have one.

Since then, when I eventually stumbled upon https://mastodon.social/tags/nixos through other means. When I messaged the account about this issue, I was told that there's a *third* place with social links, namely a "Community" link at the *top* of the website, linking to https://nixos.org/community/ which then *does* list a Mastodon link.

It would be cool if:
 1. The "Connect with us" section at the bottom of the page included a Mastodon link.
 2. The "Get in Touch" section at the bottom included a link to the https://nixos.org/community/ page, so that further means of communication could be discovered there.

**Page links**
- https://nixos.org/
- https://nixos.org/community/
- etc., basically all pages using the same footer & header.

**Additional context**
Notably, I never used Twitter to communicate, but I do use Mastodon. Also, recently a noticeable number of people are migrating from Twitter to Mastodon, so it arguably starts to become a more recognizable communication & PR venue.

- [ ] I already created a Pull Request

**Comment by fricklerhandwerk** [comment]
Thanks for pointing this out. @bryanhonof @lucperkins

I think there should be a single source of truth for these channels. It's really weird that there are three different lists in different spots.

**Comment by tomberek** [comment]
These have been consolidated in other PRs.
