### ISSUE TITLE
500 error when connecting to hydra.nixos.org

### ISSUE THREAD

**Issue by awjamison** [NixOS/nixos-homepage#95]
> DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=hydra;user=hydra;','',...) failed: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"? at /nix/store/z3zxpa6b7wiaxs86117lmk7mr82xfp10-hydra-perl-deps/lib/perl5/site_perl/5.22.1/DBIx/Class/Storage/DBI.pm line 1489. at /nix/store/129hj3i7lafa1p3bm5v5vhvpda8wivkx-hydra-0.1.1234.abcdef/libexec/hydra/lib/Hydra/Helper/CatalystUtils.pm line 357

**Comment by domenkozar** [comment]
Fixed

**Comment by masaeedu** [comment]
It seems there's a lot of bugs where you see this issue, then someone responds "now it works", and the issue pops up again some time later. E.g. hydra.nixos.org is broken [right now](https://archive.fo/TScoX), the error message looks very similar:

```
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=hydra;user=hydra;','',...) failed: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"? at /nix/store/8a6fqvf6plwfwah70jri9njpzrgrzsgx-hydra-perl-deps/lib/perl5/site_perl/5.24.3/DBIx/Class/Storage/DBI.pm line 1517. at /nix/store/3iqfxbmgcn76na9xsj6gb7h33n1d0d4a-hydra-0.1.1234.abcdef/libexec/hydra/lib/Hydra/Helper/CatalystUtils.pm line 374
```

but based on prior resolutions of the issue I don't really know what's wrong or how it might be fixed.
