### ISSUE TITLE
Destination link on https://nixos.org/guides/contributing.html is broken.

### ISSUE THREAD

**Issue by mipmip** [NixOS/nixos-homepage#958]
Link on `https://nixos.org/guides/contributing.html` points to `https://nix.dev/tutorials/contributing.html` which is broken.

![Screenshot from 2022-12-09 11-19-25](https://user-images.githubusercontent.com/658612/206679942-6f9e65c9-2eb7-4aa6-a094-e6dbd35a17cd.png)

It should point to `https://nix.dev/tutorials/contributing`. All links to `https://nix.dev/tutorials` don't end with `.html`

**Comment by timfenney** [comment]
I don't know if something changed, but I can't find that link, and also, there is a broken link there now.

I will add to this issue for now, unless you want another one :P
![nix-link-bug-1](https://user-images.githubusercontent.com/654400/216490295-af9e9ac6-e9a6-4c13-84b2-33508055894a.png)

The linked page shows the link is broken:
![Screenshot from 2023-02-02 18-34-38](https://user-images.githubusercontent.com/654400/216490368-79b8d8d0-9e72-4ee3-aa6b-c20207c5af6a.png)

**Comment by sogreatandpowerfull** [comment]
Can confirm, https://nixos.org/guides/documentation.html doesn't exist.

**Comment by flyfloh** [comment]
Looks like `/guides/contributing` got removed when the website was re-done.
