### ISSUE TITLE
The nix package search tool should display catagories for packages instead of nothing if you don't search for anything

### ISSUE THREAD

**Issue by dnkmmr69420** [NixOS/nixos-homepage#995]
**Introduce your stance**
I wan't to know what other packages are available for nix but it shows nothing unless you search. You should be able to select on categories then it shows the packages for that category. there should be an all category for all packages too.

**Describe the issue**
I find it hard to discover new packages on the nix packages repository

**Page links**
https://search.nixos.org/packages

**Additional context**
Have it similar to [Gentoo Packages](https://packages.gentoo.org/) I think nix should have its package browser just like gentoos package browser on the website

- [ ] I already created a Pull Request

**Comment by fricklerhandwerk** [comment]
@domenkozar could you please move this to https://github.com/NixOS/nixos-search? I don't have permissions.

**Comment by dnkmmr69420** [comment]
sure, will do that.
